//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class CallOutcome
    {
        public int Id { get; set; }
        public string Reference { get; set; }
        public int OutcomeId { get; set; }

        [Display(Name = "Outcome Of Call")]
        public string OutcomeName { get; set; }

        [Display(Name = "Call Back Date")]

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> CallBackDate { get; set; }
        public Nullable<System.DateTime> LastCalled { get; set; }

        public IEnumerable<SelectListItem> Outcomes { get; set; }

        public virtual CallOutcomeList CallOutcomeList { get; set; }
    }
}
