//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_brpolicy
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public string Refno { get; set; }
        public string Short_polref { get; set; }
        public Nullable<int> Status { get; set; }
        public string Frame { get; set; }
        public Nullable<int> Insco_INSC_VTId { get; set; }
        public string Polno { get; set; }
        public string C_Exec { get; set; }
        public string Comtype { get; set; }
        public Nullable<int> Pol_term { get; set; }
        public Nullable<decimal> Anprem { get; set; }
        public Nullable<System.DateTime> Rdat { get; set; }
        public Nullable<System.DateTime> Idat { get; set; }
        public Nullable<System.DateTime> Term_date { get; set; }
        public string Term_code { get; set; }
        public Nullable<decimal> Agent_comm { get; set; }
        public string Omit { get; set; }
        public string Agent { get; set; }
        public Nullable<int> Rqinsco_INSC_VTId { get; set; }
        public Nullable<decimal> Rqprem { get; set; }
        public Nullable<System.DateTime> Rqdate { get; set; }
        public string Notes1 { get; set; }
        public string Notes2 { get; set; }
        public string Policyholder { get; set; }
        public string Detflag { get; set; }
        public string Ptype { get; set; }
        public string Frame1 { get; set; }
        public string Frame2 { get; set; }
        public Nullable<int> Le_ins_INSC_VTId { get; set; }
        public string Le_pol { get; set; }
        public string Access { get; set; }
        public Nullable<int> Office_IOFF_VTId { get; set; }
        public string Direct { get; set; }
        public string Access1 { get; set; }
        public string Access2 { get; set; }
        public string Access3 { get; set; }
        public string Access4 { get; set; }
        public string Access5 { get; set; }
        public string Access6 { get; set; }
        public Nullable<decimal> Comm_rate { get; set; }
        public string Owner { get; set; }
        public Nullable<int> C_Sequence { get; set; }
        public string Vstatus { get; set; }
        public string Pay_by_pc { get; set; }
        public Nullable<int> Finance_provider_B006_VTId { get; set; }
        public string Cust_class { get; set; }
        public string Exec2 { get; set; }
        public Nullable<int> Underwriter_INSC_VTId { get; set; }
        public string Fc_edi { get; set; }
        public string Trans_ref { get; set; }
        public string No_agcomm { get; set; }
        public string Pay_method { get; set; }
        public string Code1_yn { get; set; }
        public string Code2_yn { get; set; }
        public string Policy_stop { get; set; }
        public string Renewalstatus { get; set; }
        public string Apm_ref_link { get; set; }
        public Nullable<int> Apm_branch_link { get; set; }
        public string Division { get; set; }
        public string Apm_reserved { get; set; }
        public string Trader_ref { get; set; }
        public Nullable<System.DateTime> Conversion_date { get; set; }
        public string Cliref { get; set; }
        public Nullable<decimal> Trader_comm_amt { get; set; }
        public Nullable<decimal> Trader_comm_pc { get; set; }
        public string Agg_short_code { get; set; }
        public string Agg_quote_ref { get; set; }
        public string Agg_ntu_yn { get; set; }
        public string Brandch { get; set; }
        public string Nextzerocommission { get; set; }
        public Nullable<decimal> Nextpremium { get; set; }
        public Nullable<decimal> Nextcommission { get; set; }
        public Nullable<int> Brand_QCBR_VTId { get; set; }
        public Nullable<int> Stream_QCST_VTId { get; set; }
        public string Activeq { get; set; }
        public string Aqnonedi { get; set; }
        public Nullable<int> Ultins_INSC_VTId { get; set; }
        public Nullable<int> Ultins01_INSC_VTId { get; set; }
        public Nullable<int> Ultins02_INSC_VTId { get; set; }
        public Nullable<int> Ultins03_INSC_VTId { get; set; }
        public Nullable<int> Ultins04_INSC_VTId { get; set; }
        public Nullable<int> Ultins05_INSC_VTId { get; set; }
        public Nullable<int> Ultins06_INSC_VTId { get; set; }
        public Nullable<int> Ultins07_INSC_VTId { get; set; }
        public Nullable<int> Ultins08_INSC_VTId { get; set; }
        public Nullable<int> Ultins09_INSC_VTId { get; set; }
        public Nullable<int> Ultins10_INSC_VTId { get; set; }
        public Nullable<int> Agg_conv_units { get; set; }
        public Nullable<decimal> Next_insfee { get; set; }
        public string Next_insfee_ipt { get; set; }
        public string Next_insfee_comm { get; set; }
        public string Owm { get; set; }
        public string Owm_disp { get; set; }
        public Nullable<int> Unit_type_B014_VTId { get; set; }
        public Nullable<int> Units_per_convert { get; set; }
        public string Alt_polref { get; set; }
        public Nullable<int> Alt_branch { get; set; }
        public string Trader_proc { get; set; }
        public Nullable<int> Trader_market_BRTM_VTId { get; set; }
        public Nullable<int> Lc_reason_BCL1_VTId { get; set; }
        public Nullable<int> Lc_goneto_BCL3_VTId { get; set; }
        public Nullable<decimal> Lc_premium { get; set; }
        public string Exec3 { get; set; }
        public string Info { get; set; }
        public string Mp_finance_plan { get; set; }
        public Nullable<int> Mp_finance_planid { get; set; }
        public string Mp_finance_plan_lock { get; set; }
        public string Mp_l2_type { get; set; }
        public string Hostedaddons { get; set; }
        public string Ishostedaddon { get; set; }
        public Nullable<int> Aomquoteid { get; set; }
        public string Aommainpol { get; set; }
        public Nullable<System.DateTime> Csdat { get; set; }
        public Nullable<System.DateTime> Sourcedate { get; set; }
        public string Sourceref { get; set; }
        public Nullable<int> Sourcebranch { get; set; }
        public Nullable<System.DateTime> Expiry_date { get; set; }
        public string Expiry_time { get; set; }
        public string Expiry_hh { get; set; }
        public string Expiry_time_sep { get; set; }
        public string Expiry_mm { get; set; }
        public string St_omit { get; set; }
        public string Trans_from { get; set; }
        public Nullable<decimal> Last_year_prem { get; set; }
        public Nullable<int> Consec_years { get; set; }
        public Nullable<decimal> Annualised { get; set; }
        public Nullable<System.DateTime> Base_consec_years { get; set; }
        public Nullable<System.DateTime> Base_consec_year { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
