//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_yyinsaddr
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public Nullable<int> Insco_INSC_VTId { get; set; }
        public Nullable<int> Rectype { get; set; }
        public Nullable<int> Office_IOFF_VTId { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string Addr3 { get; set; }
        public string Addr4 { get; set; }
        public string Pcode { get; set; }
        public string Tel { get; set; }
        public string Contact { get; set; }
        public string Telex { get; set; }
        public string Fax { get; set; }
        public string Agency { get; set; }
        public string Nickname { get; set; }
        public string C_Key { get; set; }
        public string Email { get; set; }
        public string Intdiary { get; set; }
        public string Contactpref { get; set; }
        public string Intermed { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
