//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_AO
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Addon_id { get; set; }
        public string Addon_desc { get; set; }
        public Nullable<decimal> Addon_gross { get; set; }
        public Nullable<int> Addon_incl_YENO_VTId { get; set; }
        public Nullable<decimal> Addon_tax { get; set; }
        public Nullable<decimal> Addon_net { get; set; }
        public string Addon_broomsref { get; set; }
        public string Addon_poltype { get; set; }
        public Nullable<int> Addon_insco_INSC_VTId { get; set; }
        public Nullable<int> Addon_terminate_YENO_VTId { get; set; }
        public string Addon_id1 { get; set; }
        public string Addon_id2 { get; set; }
        public string Addon_id3 { get; set; }
        public string Addon_id4 { get; set; }
        public string Addon_id5 { get; set; }
        public string Addon_id6 { get; set; }
        public string Addon_id7 { get; set; }
        public string Addon_id8 { get; set; }
        public string Addon_id9 { get; set; }
        public string Addon_id10 { get; set; }
        public string Addon_desc1 { get; set; }
        public string Addon_desc2 { get; set; }
        public string Addon_desc3 { get; set; }
        public string Addon_desc4 { get; set; }
        public string Addon_desc5 { get; set; }
        public string Addon_desc6 { get; set; }
        public string Addon_desc7 { get; set; }
        public string Addon_desc8 { get; set; }
        public string Addon_desc9 { get; set; }
        public string Addon_desc10 { get; set; }
        public Nullable<decimal> Addon_gross1 { get; set; }
        public Nullable<decimal> Addon_gross2 { get; set; }
        public Nullable<decimal> Addon_gross3 { get; set; }
        public Nullable<decimal> Addon_gross4 { get; set; }
        public Nullable<decimal> Addon_gross5 { get; set; }
        public Nullable<decimal> Addon_gross6 { get; set; }
        public Nullable<decimal> Addon_gross7 { get; set; }
        public Nullable<decimal> Addon_gross8 { get; set; }
        public Nullable<decimal> Addon_gross9 { get; set; }
        public Nullable<decimal> Addon_gross10 { get; set; }
        public Nullable<int> Addon_incl1_YENO_VTId { get; set; }
        public Nullable<int> Addon_incl2_YENO_VTId { get; set; }
        public Nullable<int> Addon_incl3_YENO_VTId { get; set; }
        public Nullable<int> Addon_incl4_YENO_VTId { get; set; }
        public Nullable<int> Addon_incl5_YENO_VTId { get; set; }
        public Nullable<int> Addon_incl6_YENO_VTId { get; set; }
        public Nullable<int> Addon_incl7_YENO_VTId { get; set; }
        public Nullable<int> Addon_incl8_YENO_VTId { get; set; }
        public Nullable<int> Addon_incl9_YENO_VTId { get; set; }
        public Nullable<int> Addon_incl10_YENO_VTId { get; set; }
        public Nullable<decimal> Addon_tax1 { get; set; }
        public Nullable<decimal> Addon_tax2 { get; set; }
        public Nullable<decimal> Addon_tax3 { get; set; }
        public Nullable<decimal> Addon_tax4 { get; set; }
        public Nullable<decimal> Addon_tax5 { get; set; }
        public Nullable<decimal> Addon_tax6 { get; set; }
        public Nullable<decimal> Addon_tax7 { get; set; }
        public Nullable<decimal> Addon_tax8 { get; set; }
        public Nullable<decimal> Addon_tax9 { get; set; }
        public Nullable<decimal> Addon_tax10 { get; set; }
        public Nullable<decimal> Addon_net1 { get; set; }
        public Nullable<decimal> Addon_net2 { get; set; }
        public Nullable<decimal> Addon_net3 { get; set; }
        public Nullable<decimal> Addon_net4 { get; set; }
        public Nullable<decimal> Addon_net5 { get; set; }
        public Nullable<decimal> Addon_net6 { get; set; }
        public Nullable<decimal> Addon_net7 { get; set; }
        public Nullable<decimal> Addon_net8 { get; set; }
        public Nullable<decimal> Addon_net9 { get; set; }
        public Nullable<decimal> Addon_net10 { get; set; }
        public string Addon_broomsref1 { get; set; }
        public string Addon_broomsref2 { get; set; }
        public string Addon_broomsref3 { get; set; }
        public string Addon_broomsref4 { get; set; }
        public string Addon_broomsref5 { get; set; }
        public string Addon_broomsref6 { get; set; }
        public string Addon_broomsref7 { get; set; }
        public string Addon_broomsref8 { get; set; }
        public string Addon_broomsref9 { get; set; }
        public string Addon_broomsref10 { get; set; }
        public string Addon_poltype1 { get; set; }
        public string Addon_poltype2 { get; set; }
        public string Addon_poltype3 { get; set; }
        public string Addon_poltype4 { get; set; }
        public string Addon_poltype5 { get; set; }
        public string Addon_poltype6 { get; set; }
        public string Addon_poltype7 { get; set; }
        public string Addon_poltype8 { get; set; }
        public string Addon_poltype9 { get; set; }
        public string Addon_poltype10 { get; set; }
        public Nullable<int> Addon_insco1_INSC_VTId { get; set; }
        public Nullable<int> Addon_insco2_INSC_VTId { get; set; }
        public Nullable<int> Addon_insco3_INSC_VTId { get; set; }
        public Nullable<int> Addon_insco4_INSC_VTId { get; set; }
        public Nullable<int> Addon_insco5_INSC_VTId { get; set; }
        public Nullable<int> Addon_insco6_INSC_VTId { get; set; }
        public Nullable<int> Addon_insco7_INSC_VTId { get; set; }
        public Nullable<int> Addon_insco8_INSC_VTId { get; set; }
        public Nullable<int> Addon_insco9_INSC_VTId { get; set; }
        public Nullable<int> Addon_insco10_INSC_VTId { get; set; }
        public Nullable<int> Addon_terminate1_YENO_VTId { get; set; }
        public Nullable<int> Addon_terminate2_YENO_VTId { get; set; }
        public Nullable<int> Addon_terminate3_YENO_VTId { get; set; }
        public Nullable<int> Addon_terminate4_YENO_VTId { get; set; }
        public Nullable<int> Addon_terminate5_YENO_VTId { get; set; }
        public Nullable<int> Addon_terminate6_YENO_VTId { get; set; }
        public Nullable<int> Addon_terminate7_YENO_VTId { get; set; }
        public Nullable<int> Addon_terminate8_YENO_VTId { get; set; }
        public Nullable<int> Addon_terminate9_YENO_VTId { get; set; }
        public Nullable<int> Addon_terminate10_YENO_VTId { get; set; }
        public string F_111 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
