//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_EV_HU
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Suffix_ { get; set; }
        public Nullable<System.DateTime> From_date { get; set; }
        public Nullable<int> Hq_status_H00G_VTId { get; set; }
        public string Scheme_id { get; set; }
        public Nullable<int> Hf_status_H00I_VTId { get; set; }
        public Nullable<int> Doc_type_H00H_VTId { get; set; }
        public Nullable<System.DateTime> Orig_partial { get; set; }
        public Nullable<int> Doc_bus_H00J_VTId { get; set; }
        public Nullable<System.DateTime> Orig_pending { get; set; }
        public Nullable<System.DateTime> Doc_date_eff { get; set; }
        public string Doc_htime_eff { get; set; }
        public string Doc_mtime_eff { get; set; }
        public Nullable<System.DateTime> Orig_completed { get; set; }
        public Nullable<System.DateTime> Doc_date_exp { get; set; }
        public string Doc_htime_exp { get; set; }
        public string Doc_mtime_exp { get; set; }
        public string Reason { get; set; }
        public Nullable<decimal> Orig_prem { get; set; }
        public Nullable<decimal> Orig_ipt { get; set; }
        public Nullable<decimal> Add_prem { get; set; }
        public Nullable<decimal> Add_ipt { get; set; }
        public Nullable<decimal> Act_prem { get; set; }
        public Nullable<decimal> Act_ipt { get; set; }
        public Nullable<System.DateTime> First_on { get; set; }
        public Nullable<int> First_in { get; set; }
        public string First_to { get; set; }
        public Nullable<System.DateTime> Last_on { get; set; }
        public Nullable<int> Last_in { get; set; }
        public string Last_to { get; set; }
        public Nullable<System.DateTime> Partial_end { get; set; }
        public Nullable<System.DateTime> Pending_end { get; set; }
        public string C_From { get; set; }
        public string C_To { get; set; }
        public string Copy_proposal { get; set; }
        public string Copy_schedule { get; set; }
        public string Print_proposal { get; set; }
        public string Print_schedule { get; set; }
        public Nullable<System.DateTime> Print_date { get; set; }
        public string End_rec { get; set; }
        public string Print_rnotice { get; set; }
        public string Print_rnotice_copy { get; set; }
        public string Print_phnotice { get; set; }
        public string Print_phnotice_copy { get; set; }
        public string Renewalaction { get; set; }
        public string Print_renconfdoc { get; set; }
        public string Print_renconfdoc_copy { get; set; }
        public string Print_rendecdoc { get; set; }
        public string Print_rendecdoc_copy { get; set; }
        public string Printdocument { get; set; }
        public string Printdocument_copy { get; set; }
        public Nullable<int> Relatedrecordbatch { get; set; }
        public Nullable<int> Relatedmtaptr { get; set; }
        public string Reasonforissue { get; set; }
        public Nullable<System.DateTime> Printeddatetime { get; set; }
        public Nullable<int> Hqstatus_H00G_VTId { get; set; }
        public Nullable<int> Hfstatus_H00I_VTId { get; set; }
        public string Fdf_version { get; set; }
        public string Reprint { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
