//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_H3
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<System.DateTime> C_From { get; set; }
        public Nullable<int> Binsurer_QR54_VTId { get; set; }
        public string Bpolicy_no { get; set; }
        public Nullable<System.DateTime> Bdate_lapsed { get; set; }
        public Nullable<int> Bncb_years { get; set; }
        public string Bncb_proof { get; set; }
        public string Binsurer_same { get; set; }
        public string Binsurername { get; set; }
        public string Buildpol { get; set; }
        public string Bbstfeepaid { get; set; }
        public string Buildsurvey { get; set; }
        public string Buildindex { get; set; }
        public string Buildstorm { get; set; }
        public string Buildlandslip { get; set; }
        public string Buildbuyback { get; set; }
        public string Cover { get; set; }
        public string Bbstproof { get; set; }
        public Nullable<int> Buildvolxs { get; set; }
        public Nullable<int> Buildtotxs { get; set; }
        public Nullable<int> C_Sequence { get; set; }
        public Nullable<int> Buildcover { get; set; }
        public Nullable<System.DateTime> Buildlastindex { get; set; }
        public string Btransfer_proof { get; set; }
        public Nullable<int> Buildcompxs { get; set; }
        public Nullable<int> Buildsubxs { get; set; }
        public Nullable<System.DateTime> Bncbbasedate { get; set; }
        public Nullable<decimal> Buildpremium { get; set; }
        public string End_of_record { get; set; }
        public Nullable<int> Bularea { get; set; }
        public string Subarea { get; set; }
        public Nullable<int> Buildingsyearsinsured { get; set; }
        public string Creationsource { get; set; }
        public string Updatedbyuser { get; set; }
        public Nullable<System.DateTime> Byearsinsured_basedate { get; set; }
        public Nullable<int> Byearsncb { get; set; }
        public Nullable<int> Byearsinsured { get; set; }
        public string Reqbuildpol { get; set; }
        public Nullable<int> Reqbuildcover { get; set; }
        public Nullable<int> Reqbuildvolxs { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
