//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_FL
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> F_1 { get; set; }
        public string Fleet1 { get; set; }
        public string Make1 { get; set; }
        public string Model1 { get; set; }
        public string Reg1 { get; set; }
        public Nullable<System.DateTime> RegDate1 { get; set; }
        public Nullable<int> Val1 { get; set; }
        public Nullable<int> Exc1 { get; set; }
        public Nullable<int> ESize1 { get; set; }
        public Nullable<int> Captn1 { get; set; }
        public Nullable<int> Capcwt1 { get; set; }
        public Nullable<int> Wttn1 { get; set; }
        public Nullable<int> Wtcwt1 { get; set; }
        public string Cover1 { get; set; }
        public string Type1 { get; set; }
        public Nullable<int> Rad1 { get; set; }
        public Nullable<System.DateTime> Ondate1 { get; set; }
        public Nullable<System.DateTime> Offdate1 { get; set; }
        public string Fleet2 { get; set; }
        public string Make2 { get; set; }
        public string Model2 { get; set; }
        public string Reg2 { get; set; }
        public Nullable<System.DateTime> Regdate2 { get; set; }
        public Nullable<int> Val2 { get; set; }
        public Nullable<int> Exc2 { get; set; }
        public Nullable<int> Esize2 { get; set; }
        public Nullable<int> Captn2 { get; set; }
        public Nullable<int> Capcwt2 { get; set; }
        public Nullable<int> Wttn2 { get; set; }
        public Nullable<int> Wtcwt2 { get; set; }
        public string Cover2 { get; set; }
        public string Type2 { get; set; }
        public Nullable<int> Rad2 { get; set; }
        public Nullable<System.DateTime> Ondate2 { get; set; }
        public Nullable<System.DateTime> Offdate2 { get; set; }
        public string Fleet3 { get; set; }
        public string Make3 { get; set; }
        public string Model3 { get; set; }
        public string Reg3 { get; set; }
        public Nullable<System.DateTime> Regdate3 { get; set; }
        public Nullable<int> Val3 { get; set; }
        public Nullable<int> Exc3 { get; set; }
        public Nullable<int> ESize3 { get; set; }
        public Nullable<int> Captn3 { get; set; }
        public Nullable<int> Capcwt3 { get; set; }
        public Nullable<int> Wttn3 { get; set; }
        public Nullable<int> Wtcwt3 { get; set; }
        public string Cover3 { get; set; }
        public string Type3 { get; set; }
        public Nullable<int> Rad3 { get; set; }
        public Nullable<System.DateTime> Ondate3 { get; set; }
        public Nullable<System.DateTime> Offdate3 { get; set; }
        public string Fleet4 { get; set; }
        public string Make4 { get; set; }
        public string Model4 { get; set; }
        public string Reg4 { get; set; }
        public Nullable<System.DateTime> Regdate4 { get; set; }
        public Nullable<int> Val4 { get; set; }
        public Nullable<int> Exc4 { get; set; }
        public Nullable<int> ESize4 { get; set; }
        public Nullable<int> Captn4 { get; set; }
        public Nullable<int> Capcwt4 { get; set; }
        public Nullable<int> Wttn4 { get; set; }
        public Nullable<int> Wtcwt4 { get; set; }
        public string Cover4 { get; set; }
        public string Type4 { get; set; }
        public Nullable<int> Rad4 { get; set; }
        public Nullable<System.DateTime> Ondate4 { get; set; }
        public Nullable<System.DateTime> Offdate4 { get; set; }
        public string Fleet5 { get; set; }
        public string Make5 { get; set; }
        public string Model5 { get; set; }
        public string Reg { get; set; }
        public Nullable<System.DateTime> Regdate5 { get; set; }
        public Nullable<int> Val5 { get; set; }
        public Nullable<int> Exc5 { get; set; }
        public Nullable<int> ESize5 { get; set; }
        public Nullable<int> Captn55 { get; set; }
        public Nullable<int> Capcwt5 { get; set; }
        public Nullable<int> Wttn5 { get; set; }
        public Nullable<int> Wtcwt5 { get; set; }
        public string Cover5 { get; set; }
        public string Type5 { get; set; }
        public Nullable<int> Rad5 { get; set; }
        public Nullable<System.DateTime> Ondate5 { get; set; }
        public Nullable<System.DateTime> Offdate5 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
