//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_ERH_History
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> Buffersizeinwords { get; set; }
        public Nullable<int> Currenterh { get; set; }
        public Nullable<int> Totalerh { get; set; }
        public string C_Result { get; set; }
        public string Quotesource { get; set; }
        public string Insurererrormsg1 { get; set; }
        public string Insurererrormsg2 { get; set; }
        public string Ogierrorcode { get; set; }
        public string Ogierrormsg1 { get; set; }
        public string Ogierrormsg2 { get; set; }
        public string Insurerscheme { get; set; }
        public string Enrichmentstring { get; set; }
        public string F_13 { get; set; }
        public string F_14 { get; set; }
        public string F_15 { get; set; }
        public string F_16 { get; set; }
        public string Enrichmentrequestid { get; set; }
        public Nullable<System.DateTime> Enrichmentdate { get; set; }
        public string Enrichmenttime { get; set; }
        public string Quotereference { get; set; }
        public string Ogixmllogid { get; set; }
        public Nullable<int> Enrichmenttimeinsecs { get; set; }
        public string F_23 { get; set; }
        public string F_24 { get; set; }
        public string F_25 { get; set; }
        public string F_26 { get; set; }
        public string Fprversion { get; set; }
        public string Service { get; set; }
        public string Endofrecord { get; set; }
        public string Bericprovider { get; set; }
        public Nullable<System.DateTime> History_ { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
