//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_brcshbk1
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string C_Key { get; set; }
        public string C_key1 { get; set; }
        public Nullable<decimal> C_nb { get; set; }
        public Nullable<decimal> C_transfnb { get; set; }
        public Nullable<decimal> C_renewal { get; set; }
        public Nullable<decimal> C_endorse { get; set; }
        public Nullable<decimal> C_cancel { get; set; }
        public Nullable<decimal> C_charges { get; set; }
        public Nullable<decimal> C_inspol { get; set; }
        public Nullable<decimal> C_lapses { get; set; }
        public Nullable<decimal> C_adjust { get; set; }
        public Nullable<decimal> C_journal { get; set; }
        public Nullable<decimal> C_interest { get; set; }
        public Nullable<decimal> C_cash { get; set; }
        public Nullable<decimal> C_discount { get; set; }
        public Nullable<decimal> C_claims { get; set; }
        public Nullable<decimal> C_unallcash { get; set; }
        public Nullable<decimal> C_bcf { get; set; }
        public string X_rtype { get; set; }
        public string X_ttype { get; set; }
        public Nullable<int> X_keysuffix { get; set; }
        public string X_polref { get; set; }
        public Nullable<System.DateTime> X_dat { get; set; }
        public string X_time { get; set; }
        public Nullable<decimal> X_val1 { get; set; }
        public Nullable<decimal> X_val2 { get; set; }
        public string X_tref { get; set; }
        public Nullable<int> X_stat { get; set; }
        public Nullable<decimal> X_comm { get; set; }
        public Nullable<int> X_ins_INSC_VTId { get; set; }
        public string R0_rtype { get; set; }
        public Nullable<int> R0_payr { get; set; }
        public Nullable<int> R0_keysuffix { get; set; }
        public string R0_polref { get; set; }
        public Nullable<System.DateTime> R0_dat { get; set; }
        public string R0_tref { get; set; }
        public string R0_ttype { get; set; }
        public string R0_pm { get; set; }
        public Nullable<decimal> R0_amt { get; set; }
        public Nullable<decimal> R0_chg { get; set; }
        public Nullable<decimal> R0_int { get; set; }
        public Nullable<decimal> R0_disc { get; set; }
        public string X_rectype { get; set; }
        public string Poltype { get; set; }
        public Nullable<System.DateTime> X_date1 { get; set; }
        public Nullable<System.DateTime> X_date2 { get; set; }
        public string X_pay_direct { get; set; }
        public Nullable<int> C_serialnum { get; set; }
        public Nullable<int> X_linked { get; set; }
        public string X_poltype { get; set; }
        public string Operator { get; set; }
        public Nullable<int> Vdu_no { get; set; }
        public Nullable<int> Insco_INSC_VTId { get; set; }
        public string R0_time { get; set; }
        public string R0_paystat { get; set; }
        public Nullable<int> X_ccode { get; set; }
        public string X_paystat { get; set; }
        public Nullable<int> R0_receipt_num { get; set; }
        public Nullable<decimal> R0_ag_comm { get; set; }
        public Nullable<decimal> X_ag_comm { get; set; }
        public Nullable<System.DateTime> Ldg_effect_date { get; set; }
        public Nullable<int> Ldg_suffix { get; set; }
        public string Comm_processed { get; set; }
        public string Payment_conf { get; set; }
        public Nullable<int> X_l_suffix { get; set; }
        public Nullable<decimal> Preipt_amt { get; set; }
        public string Sh_tran_ref { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
