//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_PL_History
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> NoEmp1 { get; set; }
        public Nullable<int> Wg1 { get; set; }
        public Nullable<decimal> Rate1 { get; set; }
        public Nullable<decimal> Prem1 { get; set; }
        public Nullable<int> NoEmp2 { get; set; }
        public Nullable<int> Wg2 { get; set; }
        public Nullable<decimal> Rate2 { get; set; }
        public Nullable<decimal> Prem2 { get; set; }
        public Nullable<int> NoEmp3 { get; set; }
        public Nullable<int> Wg3 { get; set; }
        public Nullable<decimal> Rate3 { get; set; }
        public Nullable<decimal> Prem3 { get; set; }
        public Nullable<int> Limacc { get; set; }
        public Nullable<int> Limyrc { get; set; }
        public Nullable<int> Exc { get; set; }
        public string Rem1 { get; set; }
        public string Rem2 { get; set; }
        public string UK { get; set; }
        public string Wrld { get; set; }
        public Nullable<int> F_20 { get; set; }
        public string Rtbas1 { get; set; }
        public Nullable<int> Rtno1 { get; set; }
        public Nullable<int> Rtamm1 { get; set; }
        public Nullable<decimal> Rt1 { get; set; }
        public Nullable<decimal> Pr1 { get; set; }
        public string Rtbas2 { get; set; }
        public Nullable<int> Rtno2 { get; set; }
        public Nullable<int> Rtamm2 { get; set; }
        public Nullable<decimal> Rt2 { get; set; }
        public Nullable<decimal> Pr2 { get; set; }
        public string Rtbas3 { get; set; }
        public Nullable<int> Rtno3 { get; set; }
        public Nullable<int> Rtamm3 { get; set; }
        public Nullable<decimal> Rt3 { get; set; }
        public Nullable<decimal> Pr3 { get; set; }
        public string Rtbas4 { get; set; }
        public Nullable<int> Rtno4 { get; set; }
        public Nullable<int> Rtamm4 { get; set; }
        public Nullable<decimal> Rt4 { get; set; }
        public Nullable<decimal> Pr4 { get; set; }
        public string Rtbas5 { get; set; }
        public Nullable<int> Rtno5 { get; set; }
        public Nullable<int> Rtamm5 { get; set; }
        public Nullable<decimal> Rt5 { get; set; }
        public Nullable<decimal> Pr5 { get; set; }
        public string Rtbas6 { get; set; }
        public Nullable<int> Rtno6 { get; set; }
        public Nullable<int> Rtamm6 { get; set; }
        public Nullable<decimal> Rt6 { get; set; }
        public Nullable<decimal> Pr6 { get; set; }
        public Nullable<System.DateTime> History_ { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
