//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_DC
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<decimal> Paid_amt { get; set; }
        public string Paymethod { get; set; }
        public Nullable<int> Use_pf_YENO_VTId { get; set; }
        public Nullable<int> Card_paid_YENO_VTId { get; set; }
        public string Reference { get; set; }
        public Nullable<int> Use_bacs_YENO_VTId { get; set; }
        public string Br_client { get; set; }
        public Nullable<int> Branches_YENO_VTId { get; set; }
        public Nullable<int> Br_branch_no { get; set; }
        public string Op_code { get; set; }
        public string Wp_operator { get; set; }
        public string Sh_txn_no { get; set; }
        public string Sh_sub_no { get; set; }
        public Nullable<int> Receipt_rqd_YENO_VTId { get; set; }
        public Nullable<int> Settle_charge_YENO_VTId { get; set; }
        public Nullable<int> Processed_YENO_VTId { get; set; }
        public string Diary_exec { get; set; }
        public string Override_odc_queue { get; set; }
        public string Auth_value { get; set; }
        public Nullable<int> Ca_approved_YENO_VTId { get; set; }
        public string Card_suffix { get; set; }
        public string Card_expiry { get; set; }
        public string Card_holder { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public string Card_type { get; set; }
        public string Card_holder_addr1 { get; set; }
        public string Card_holder_addr2 { get; set; }
        public string Card_holder_addr3 { get; set; }
        public string Card_holder_addr4 { get; set; }
        public string Card_holder_addr5 { get; set; }
        public string Card_holder_pcode { get; set; }
        public string Merchant { get; set; }
        public string Process_type { get; set; }
    }
}
