//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_HRS
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string F_1 { get; set; }
        public Nullable<int> F_2 { get; set; }
        public string F_3 { get; set; }
        public string F_4 { get; set; }
        public Nullable<int> F_5 { get; set; }
        public string F_6 { get; set; }
        public string F_7 { get; set; }
        public Nullable<int> F_8 { get; set; }
        public Nullable<int> F_9 { get; set; }
        public Nullable<int> F_10 { get; set; }
        public string F_11 { get; set; }
        public Nullable<decimal> F_12 { get; set; }
        public Nullable<System.DateTime> F_13 { get; set; }
        public string F_14 { get; set; }
        public string F_15 { get; set; }
        public string F_16 { get; set; }
        public string F_17 { get; set; }
        public Nullable<System.DateTime> F_18 { get; set; }
        public string F_19 { get; set; }
        public Nullable<int> F_20 { get; set; }
        public string F_21 { get; set; }
        public Nullable<System.DateTime> F_22 { get; set; }
        public string F_23 { get; set; }
        public Nullable<int> F_24 { get; set; }
        public string F_25 { get; set; }
        public Nullable<System.DateTime> F_26 { get; set; }
        public string F_27 { get; set; }
        public Nullable<int> F_28 { get; set; }
        public string F_29 { get; set; }
        public Nullable<System.DateTime> F_30 { get; set; }
        public string F_31 { get; set; }
        public Nullable<int> F_32 { get; set; }
        public string F_33 { get; set; }
        public Nullable<System.DateTime> F_34 { get; set; }
        public string F_35 { get; set; }
        public Nullable<int> F_36 { get; set; }
        public Nullable<int> F_37 { get; set; }
        public string F_38 { get; set; }
        public Nullable<System.DateTime> F_39 { get; set; }
        public string F_40 { get; set; }
        public Nullable<int> F_41 { get; set; }
        public Nullable<int> F_42 { get; set; }
        public string F_43 { get; set; }
        public Nullable<System.DateTime> F_44 { get; set; }
        public string F_45 { get; set; }
        public Nullable<int> F_46 { get; set; }
        public Nullable<int> F_47 { get; set; }
        public string F_48 { get; set; }
        public Nullable<System.DateTime> F_49 { get; set; }
        public string F_50 { get; set; }
        public Nullable<int> F_51 { get; set; }
        public Nullable<int> F_52 { get; set; }
        public string F_53 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
