//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_RP07
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string OccupiedOvernig { get; set; }
        public string InsideShoppingC { get; set; }
        public string FireAlarm { get; set; }
        public string TwentyFourSecur { get; set; }
        public string SprinklerInstal { get; set; }
        public string CCTV { get; set; }
        public string CCTVType { get; set; }
        public string IntruderAlarm { get; set; }
        public string TypeOfAlarm { get; set; }
        public string SignallingMetho { get; set; }
        public string GrillesBarsShut { get; set; }
        public string LockableDoors { get; set; }
        public string WorkshopInPremi { get; set; }
        public string WorkAwayPremise { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
