//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DE_NOTE
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Suffix_ { get; set; }
        public string C_from { get; set; }
        public string C_to { get; set; }
        public Nullable<System.DateTime> C_date { get; set; }
        public string det1 { get; set; }
        public string det2 { get; set; }
        public string det3 { get; set; }
        public string det4 { get; set; }
        public string det5 { get; set; }
        public string det6 { get; set; }
        public string C_action { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
