//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_braccesshist
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string Client_ref { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public Nullable<int> Suffix { get; set; }
        public string C_Key { get; set; }
        public string C_Time { get; set; }
        public string Short_polref { get; set; }
        public string Opcode { get; set; }
        public string Opname { get; set; }
        public Nullable<int> Vdu_no { get; set; }
        public string C_Action { get; set; }
        public Nullable<int> Claim_id { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
