//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BF_HJ
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<System.DateTime> C_From { get; set; }
        public Nullable<int> Cinsurer_QR54_VTId { get; set; }
        public string Cpolicy_no { get; set; }
        public Nullable<System.DateTime> Cdate_lapsed { get; set; }
        public Nullable<int> Cncb_years { get; set; }
        public string Cncb_proof { get; set; }
        public Nullable<int> Conarea { get; set; }
        public Nullable<int> C_Sequence { get; set; }
        public string Cinsurername { get; set; }
        public string Contspol { get; set; }
        public Nullable<int> Contsgoods { get; set; }
        public Nullable<int> Contsgoodslimit { get; set; }
        public Nullable<int> Contsvals { get; set; }
        public Nullable<int> Contsvalslimit { get; set; }
        public Nullable<int> Contsvolxs { get; set; }
        public string Allrisksflag { get; set; }
        public string Contsindex { get; set; }
        public string Contsbuyback { get; set; }
        public string Ctransfer_proof { get; set; }
        public Nullable<int> Contstotxs { get; set; }
        public Nullable<System.DateTime> Contslastindex { get; set; }
        public Nullable<int> Totspecitems { get; set; }
        public Nullable<int> Contscompxs { get; set; }
        public Nullable<System.DateTime> Cncbbasedate { get; set; }
        public Nullable<decimal> Contspremium { get; set; }
        public Nullable<int> Contstot { get; set; }
        public Nullable<decimal> Specitempremium { get; set; }
        public string End_of_record { get; set; }
        public Nullable<int> Contentsyearsinsured { get; set; }
        public string Creationsource { get; set; }
        public string Updatedbyuser { get; set; }
        public Nullable<System.DateTime> Cyearsinsured_basedate { get; set; }
        public string Newendofrecord { get; set; }
        public Nullable<int> Cyearsncb { get; set; }
        public Nullable<int> Cyearsinsured { get; set; }
        public string Reqcontspol { get; set; }
        public Nullable<int> Reqcontsgoods { get; set; }
        public Nullable<int> Reqcontsgoodslimit { get; set; }
        public Nullable<int> Reqcontsvals { get; set; }
        public Nullable<int> Reqcontsvalslimit { get; set; }
        public Nullable<int> Reqcontsvolxs { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
