//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_dpstpaudit
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public Nullable<System.DateTime> Audit_date { get; set; }
        public string Audit_time { get; set; }
        public Nullable<int> Taskid { get; set; }
        public Nullable<int> Suffix { get; set; }
        public string Product_line { get; set; }
        public string Apm_ref { get; set; }
        public string Event { get; set; }
        public Nullable<decimal> Queue_time { get; set; }
        public Nullable<decimal> Conv_time { get; set; }
        public string Brooms_ref { get; set; }
        public Nullable<int> Brooms_branch { get; set; }
        public string Message { get; set; }
        public string Client_name { get; set; }
        public Nullable<decimal> Aqorigpreminclipt { get; set; }
        public Nullable<decimal> Aqnewpreminclipt { get; set; }
        public Nullable<decimal> Aqdiffpreminclipt { get; set; }
        public string Scheme { get; set; }
        public string C_Key { get; set; }
        public string Apm_prosp_ref { get; set; }
        public string Apm_ptype { get; set; }
        public string Childkey { get; set; }
        public string Contrec { get; set; }
        public string Ecommerce { get; set; }
        public string Brooms_client_ref { get; set; }
        public string Brooms_ptype { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
