//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_CP
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Dam1 { get; set; }
        public string Brkdn1 { get; set; }
        public string F_3 { get; set; }
        public string Fire { get; set; }
        public Nullable<int> Si1 { get; set; }
        public Nullable<int> Deduc1 { get; set; }
        public Nullable<decimal> Rate1 { get; set; }
        public string Name2 { get; set; }
        public Nullable<int> Si2 { get; set; }
        public Nullable<int> Deduc2 { get; set; }
        public Nullable<decimal> Rate2 { get; set; }
        public string Name3 { get; set; }
        public Nullable<int> Si3 { get; set; }
        public Nullable<int> Deduc3 { get; set; }
        public Nullable<decimal> Rate3 { get; set; }
        public string Name4 { get; set; }
        public Nullable<int> Si4 { get; set; }
        public Nullable<int> Deduc4 { get; set; }
        public Nullable<decimal> Rate4 { get; set; }
        public string Name5 { get; set; }
        public Nullable<int> Si5 { get; set; }
        public Nullable<int> Deduc5 { get; set; }
        public Nullable<decimal> Rate5 { get; set; }
        public string Dam2 { get; set; }
        public string Brkdn2 { get; set; }
        public string Accid { get; set; }
        public string F_27 { get; set; }
        public string Firligt { get; set; }
        public Nullable<int> Gprof { get; set; }
        public Nullable<int> Rev { get; set; }
        public Nullable<int> Inccost { get; set; }
        public Nullable<int> Reinst { get; set; }
        public string F_33 { get; set; }
        public string Franchpe { get; set; }
        public Nullable<int> Indempe { get; set; }
        public string Excess { get; set; }
        public Nullable<int> Deduc { get; set; }
        public string F_38 { get; set; }
        public string Rem1 { get; set; }
        public string Rem2 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
