//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_TEST
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Field1 { get; set; }
        public Nullable<int> Field2 { get; set; }
        public string Field3 { get; set; }
        public string Field4 { get; set; }
        public Nullable<System.DateTime> Field5 { get; set; }
        public string Field6 { get; set; }
        public string Field7 { get; set; }
        public string Field8 { get; set; }
        public string Field9 { get; set; }
        public string Field10 { get; set; }
        public string Field11 { get; set; }
        public string Field12 { get; set; }
        public string Field13 { get; set; }
        public string Field14 { get; set; }
        public string Field15 { get; set; }
        public string Field16 { get; set; }
        public Nullable<System.DateTime> Field17 { get; set; }
        public string Field18 { get; set; }
        public string Field19 { get; set; }
        public Nullable<System.DateTime> Field20 { get; set; }
        public string Field21 { get; set; }
        public string Field22 { get; set; }
        public Nullable<System.DateTime> Field23 { get; set; }
        public string Field24 { get; set; }
        public string Field25 { get; set; }
        public string Test { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
