//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_RP05
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string EmpAndPubLiaReq { get; set; }
        public Nullable<int> EmpLiab { get; set; }
        public Nullable<int> PubLiab { get; set; }
        public Nullable<int> AnnualTurnover { get; set; }
        public Nullable<int> WageBill { get; set; }
        public Nullable<int> BookDebts { get; set; }
        public string ManualWorkAway { get; set; }
        public string TheftCoverEmp { get; set; }
        public Nullable<int> NumberOfEmploye { get; set; }
        public string ReferencesEmp { get; set; }
        public string CheckStockMoney { get; set; }
        public Nullable<int> GoodsInTransit { get; set; }
        public string TerrorismCover { get; set; }
        public Nullable<int> ClaimsInLast5Yr { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
