//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_yydatedinsco
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string C_Key { get; set; }
        public Nullable<int> Insco_INSC_VTId { get; set; }
        public Nullable<int> Rectype { get; set; }
        public string Poltype { get; set; }
        public string Ptype { get; set; }
        public Nullable<System.DateTime> From_dt { get; set; }
        public Nullable<decimal> Com_rate1 { get; set; }
        public Nullable<decimal> Com_rate2 { get; set; }
        public Nullable<int> Pr_split1 { get; set; }
        public Nullable<int> Pr_split2 { get; set; }
        public Nullable<int> Upd_seq { get; set; }
        public Nullable<decimal> Prem_per { get; set; }
        public Nullable<decimal> Comm_per { get; set; }
        public Nullable<decimal> Prem_year { get; set; }
        public Nullable<decimal> Comm_year { get; set; }
        public Nullable<int> Yoa_day { get; set; }
        public Nullable<int> Yoa_month { get; set; }
        public string Act_agent { get; set; }
        public string Defcomcalc { get; set; }
        public string Reason { get; set; }
        public string Insfee_basedon { get; set; }
        public Nullable<int> Eol_insurer_INSC_VTId { get; set; }
        public Nullable<decimal> Insfee_nb_amt { get; set; }
        public Nullable<decimal> Insfee_rnl_amt { get; set; }
        public Nullable<decimal> Insfee_mta_amt { get; set; }
        public Nullable<decimal> Nb_rate { get; set; }
        public Nullable<decimal> Re_rate { get; set; }
        public string C_Desc { get; set; }
        public string Insfee_ipt { get; set; }
        public string Insfee_comm { get; set; }
        public string Bkrecsch { get; set; }
        public string Bkrecschpr { get; set; }
        public Nullable<int> Ultins01_INSU_VTId { get; set; }
        public Nullable<int> Ultins02_INSU_VTId { get; set; }
        public Nullable<int> Ultins03_INSU_VTId { get; set; }
        public Nullable<int> Ultins04_INSU_VTId { get; set; }
        public Nullable<int> Ultins05_INSU_VTId { get; set; }
        public Nullable<int> Ultins06_INSU_VTId { get; set; }
        public Nullable<int> Ultins07_INSU_VTId { get; set; }
        public Nullable<int> Ultins08_INSU_VTId { get; set; }
        public Nullable<int> Ultins09_INSU_VTId { get; set; }
        public Nullable<int> Ultins10_INSU_VTId { get; set; }
        public Nullable<decimal> Insfee_nb_amt_1 { get; set; }
        public Nullable<decimal> Insfee_rnl_amt_1 { get; set; }
        public Nullable<decimal> Insfee_mta_amt_1 { get; set; }
        public Nullable<decimal> Nb_rate_1 { get; set; }
        public Nullable<decimal> Re_rate_1 { get; set; }
        public string Desc_1 { get; set; }
        public string Insfee_ipt_1 { get; set; }
        public string Insfee_comm_1 { get; set; }
        public Nullable<decimal> Insfee_nb_amt_2 { get; set; }
        public Nullable<decimal> Insfee_rnl_amt_2 { get; set; }
        public Nullable<decimal> Insfee_mta_amt_2 { get; set; }
        public Nullable<decimal> Nb_rate_2 { get; set; }
        public Nullable<decimal> Re_rate_2 { get; set; }
        public string Desc_2 { get; set; }
        public string Insfee_ipt_2 { get; set; }
        public string Insfee_comm_2 { get; set; }
        public Nullable<decimal> Insfee_nb_amt_3 { get; set; }
        public Nullable<decimal> Insfee_rnl_amt_3 { get; set; }
        public Nullable<decimal> Insfee_mta_amt_3 { get; set; }
        public Nullable<decimal> Nb_rate_3 { get; set; }
        public Nullable<decimal> Re_rate_3 { get; set; }
        public string Desc_3 { get; set; }
        public string Insfee_ipt_3 { get; set; }
        public string Insfee_comm_3 { get; set; }
        public Nullable<decimal> Insfee_nb_amt_4 { get; set; }
        public Nullable<decimal> Insfee_rnl_amt_4 { get; set; }
        public Nullable<decimal> Insfee_mta_amt_4 { get; set; }
        public Nullable<decimal> Nb_rate_4 { get; set; }
        public Nullable<decimal> Re_rate_4 { get; set; }
        public string Desc_4 { get; set; }
        public string Insfee_ipt_4 { get; set; }
        public string Insfee_comm_4 { get; set; }
        public Nullable<decimal> Insfee_nb_amt_5 { get; set; }
        public Nullable<decimal> Insfee_rnl_amt_5 { get; set; }
        public Nullable<decimal> Insfee_mta_amt_5 { get; set; }
        public Nullable<decimal> Nb_rate_5 { get; set; }
        public Nullable<decimal> Re_rate_5 { get; set; }
        public string Desc_5 { get; set; }
        public string Insfee_ipt_5 { get; set; }
        public string Insfee_comm_5 { get; set; }
        public Nullable<decimal> Insfee_nb_amt_6 { get; set; }
        public Nullable<decimal> Insfee_rnl_amt_6 { get; set; }
        public Nullable<decimal> Insfee_mta_amt_6 { get; set; }
        public Nullable<decimal> Nb_rate_6 { get; set; }
        public Nullable<decimal> Re_rate_6 { get; set; }
        public string Desc_6 { get; set; }
        public string Insfee_ipt_6 { get; set; }
        public string Insfee_comm_6 { get; set; }
        public Nullable<decimal> Insfee_nb_amt_7 { get; set; }
        public Nullable<decimal> Insfee_rnl_amt_7 { get; set; }
        public Nullable<decimal> Insfee_mta_amt_7 { get; set; }
        public Nullable<decimal> Nb_rate_7 { get; set; }
        public Nullable<decimal> Re_rate_7 { get; set; }
        public string Desc_7 { get; set; }
        public string Insfee_ipt_7 { get; set; }
        public string Insfee_comm_7 { get; set; }
        public Nullable<decimal> Insfee_nb_amt_8 { get; set; }
        public Nullable<decimal> Insfee_rnl_amt_8 { get; set; }
        public Nullable<decimal> Insfee_mta_amt_8 { get; set; }
        public Nullable<decimal> Nb_rate_8 { get; set; }
        public Nullable<decimal> Re_rate_8 { get; set; }
        public string Desc_8 { get; set; }
        public string Insfee_ipt_8 { get; set; }
        public string Insfee_comm_8 { get; set; }
        public Nullable<decimal> Insfee_nb_amt_9 { get; set; }
        public Nullable<decimal> Insfee_rnl_amt_9 { get; set; }
        public Nullable<decimal> Insfee_mta_amt_9 { get; set; }
        public Nullable<decimal> Nb_rate_9 { get; set; }
        public Nullable<decimal> Re_rate_9 { get; set; }
        public string Desc_9 { get; set; }
        public string Insfee_ipt_9 { get; set; }
        public string Insfee_comm_9 { get; set; }
        public Nullable<decimal> Insfee_nb_amt_10 { get; set; }
        public Nullable<decimal> Insfee_rnl_amt_10 { get; set; }
        public Nullable<decimal> Insfee_mta_amt_10 { get; set; }
        public Nullable<decimal> Nb_rate_10 { get; set; }
        public Nullable<decimal> Re_rate_10 { get; set; }
        public string Desc_10 { get; set; }
        public string Insfee_ipt_10 { get; set; }
        public string Insfee_comm_10 { get; set; }
        public Nullable<decimal> Insfee_nb_amt_11 { get; set; }
        public Nullable<decimal> Insfee_rnl_amt_11 { get; set; }
        public Nullable<decimal> Insfee_mta_amt_11 { get; set; }
        public Nullable<decimal> Nb_rate_11 { get; set; }
        public Nullable<decimal> Re_rate_11 { get; set; }
        public string Desc_11 { get; set; }
        public string Insfee_ipt_11 { get; set; }
        public string Insfee_comm_11 { get; set; }
        public Nullable<decimal> Insfee_nb_amt_12 { get; set; }
        public Nullable<decimal> Insfee_rnl_amt_12 { get; set; }
        public Nullable<decimal> Insfee_mta_amt_12 { get; set; }
        public Nullable<decimal> Nb_rate_12 { get; set; }
        public Nullable<decimal> Re_rate_12 { get; set; }
        public string Desc_12 { get; set; }
        public string Insfee_ipt_12 { get; set; }
        public string Insfee_comm_12 { get; set; }
        public string Bkrecsch_1 { get; set; }
        public string Bkrecsch_2 { get; set; }
        public string Bkrecsch_3 { get; set; }
        public string Bkrecsch_4 { get; set; }
        public string Bkrecsch_5 { get; set; }
        public string Bkrecsch_6 { get; set; }
        public string Bkrecsch_7 { get; set; }
        public string Bkrecsch_8 { get; set; }
        public string Bkrecsch_9 { get; set; }
        public string Bkrecsch_10 { get; set; }
        public string Bkrecsch_11 { get; set; }
        public string Bkrecsch_12 { get; set; }
        public string Bkrecschpr_1 { get; set; }
        public string Bkrecschpr_2 { get; set; }
        public string Bkrecschpr_3 { get; set; }
        public string Bkrecschpr_4 { get; set; }
        public string Bkrecschpr_5 { get; set; }
        public string Bkrecschpr_6 { get; set; }
        public string Bkrecschpr_7 { get; set; }
        public string Bkrecschpr_8 { get; set; }
        public string Bkrecschpr_9 { get; set; }
        public string Bkrecschpr_10 { get; set; }
        public string Bkrecschpr_11 { get; set; }
        public string Bkrecschpr_12 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
