//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_HIN
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<System.DateTime> C_From { get; set; }
        public Nullable<int> C_Sequence { get; set; }
        public Nullable<int> Interestno { get; set; }
        public Nullable<int> Interest_H00E_VTId { get; set; }
        public string Interestunlist { get; set; }
        public string Interestaddr1 { get; set; }
        public string Interestaddr2 { get; set; }
        public string Interestaddr3 { get; set; }
        public string Interestaddr4 { get; set; }
        public string Interestpcode { get; set; }
        public string Reference { get; set; }
        public Nullable<int> Interestname_H00F_VTId { get; set; }
        public string End_of_record { get; set; }
        public string Creationsource { get; set; }
        public string Updatedbyuser { get; set; }
        public string Interesteircode { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
