//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_TAX2_History
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string F_1 { get; set; }
        public string F_2 { get; set; }
        public string F_3 { get; set; }
        public string F_4 { get; set; }
        public string F_5 { get; set; }
        public string F_6 { get; set; }
        public string F_7 { get; set; }
        public string F_8 { get; set; }
        public string F_9 { get; set; }
        public string F_10 { get; set; }
        public string F_11 { get; set; }
        public string F_12 { get; set; }
        public string F_13 { get; set; }
        public string F_14 { get; set; }
        public string F_15 { get; set; }
        public string F_16 { get; set; }
        public string F_17 { get; set; }
        public string F_18 { get; set; }
        public string F_19 { get; set; }
        public string F_20 { get; set; }
        public string F_21 { get; set; }
        public string F_22 { get; set; }
        public string F_23 { get; set; }
        public string F_24 { get; set; }
        public string F_25 { get; set; }
        public string F_26 { get; set; }
        public Nullable<System.DateTime> F_27 { get; set; }
        public Nullable<System.DateTime> F_28 { get; set; }
        public Nullable<System.DateTime> F_29 { get; set; }
        public Nullable<System.DateTime> F_30 { get; set; }
        public Nullable<System.DateTime> F_31 { get; set; }
        public Nullable<int> F_32 { get; set; }
        public Nullable<int> F_33 { get; set; }
        public Nullable<int> F_34 { get; set; }
        public Nullable<int> F_35 { get; set; }
        public Nullable<int> F_36 { get; set; }
        public Nullable<int> F_37 { get; set; }
        public Nullable<int> F_38 { get; set; }
        public Nullable<int> F_39 { get; set; }
        public Nullable<int> F_40 { get; set; }
        public Nullable<int> F_41 { get; set; }
        public string F_42 { get; set; }
        public string F_43 { get; set; }
        public string F_44 { get; set; }
        public string F_45 { get; set; }
        public string F_46 { get; set; }
        public Nullable<int> F_47 { get; set; }
        public Nullable<int> F_48 { get; set; }
        public Nullable<int> F_49 { get; set; }
        public Nullable<int> F_50 { get; set; }
        public Nullable<int> F_51 { get; set; }
        public string F_52 { get; set; }
        public string F_53 { get; set; }
        public string F_54 { get; set; }
        public string F_55 { get; set; }
        public string F_56 { get; set; }
        public string F_57 { get; set; }
        public string F_58 { get; set; }
        public string F_59 { get; set; }
        public string F_60 { get; set; }
        public string F_61 { get; set; }
        public string F_62 { get; set; }
        public string F_63 { get; set; }
        public string F_64 { get; set; }
        public string F_65 { get; set; }
        public string F_66 { get; set; }
        public string F_67 { get; set; }
        public string F_68 { get; set; }
        public string F_69 { get; set; }
        public string F_70 { get; set; }
        public string F_71 { get; set; }
        public string F_72 { get; set; }
        public string F_73 { get; set; }
        public string F_74 { get; set; }
        public string F_75 { get; set; }
        public string F_76 { get; set; }
        public string F_77 { get; set; }
        public string F_78 { get; set; }
        public string F_79 { get; set; }
        public string F_80 { get; set; }
        public string F_81 { get; set; }
        public Nullable<System.DateTime> History_ { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
