//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_TH
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> Ammlss { get; set; }
        public Nullable<int> Totrsk { get; set; }
        public string Plnref { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string Addr3 { get; set; }
        public string Addr4 { get; set; }
        public Nullable<int> SI1 { get; set; }
        public Nullable<decimal> Rate1 { get; set; }
        public Nullable<decimal> Prem1 { get; set; }
        public Nullable<int> SI2 { get; set; }
        public Nullable<decimal> Rate2 { get; set; }
        public Nullable<decimal> Prem2 { get; set; }
        public Nullable<int> SI3 { get; set; }
        public Nullable<decimal> Rate3 { get; set; }
        public Nullable<decimal> Prem3 { get; set; }
        public Nullable<int> SI4 { get; set; }
        public Nullable<decimal> Rate4 { get; set; }
        public Nullable<decimal> Prem4 { get; set; }
        public Nullable<int> SI5 { get; set; }
        public Nullable<decimal> Rate5 { get; set; }
        public Nullable<decimal> Prem5 { get; set; }
        public Nullable<int> SI6 { get; set; }
        public Nullable<decimal> Rate6 { get; set; }
        public Nullable<decimal> Prem6 { get; set; }
        public Nullable<int> SI7 { get; set; }
        public Nullable<decimal> Rate7 { get; set; }
        public Nullable<decimal> Prem7 { get; set; }
        public Nullable<int> SI8 { get; set; }
        public Nullable<decimal> Rate8 { get; set; }
        public Nullable<decimal> Prem8 { get; set; }
        public Nullable<int> SI9 { get; set; }
        public Nullable<decimal> Rate9 { get; set; }
        public Nullable<decimal> Prem9 { get; set; }
        public Nullable<int> SI10 { get; set; }
        public Nullable<decimal> Rate10 { get; set; }
        public Nullable<decimal> Prem10 { get; set; }
        public Nullable<int> SI11 { get; set; }
        public Nullable<decimal> Rate11 { get; set; }
        public Nullable<decimal> Prem11 { get; set; }
        public string Addtn1 { get; set; }
        public string Addtn2 { get; set; }
        public string Addtn3 { get; set; }
        public string Addtn4 { get; set; }
        public string Addtn5 { get; set; }
        public string Rem1 { get; set; }
        public string Rem2 { get; set; }
        public string Rem3 { get; set; }
        public string Wrr1 { get; set; }
        public string Wrr2 { get; set; }
        public string Wrr3 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
