//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_brAgentdtls
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string Code { get; set; }
        public string Sortcode { get; set; }
        public string C_Name { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string Addr3 { get; set; }
        public string Addr4 { get; set; }
        public string Pcode { get; set; }
        public string Tel { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> Defcom { get; set; }
        public string Pol { get; set; }
        public Nullable<decimal> Com { get; set; }
        public string Text1 { get; set; }
        public string Del_flag { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public string Fax { get; set; }
        public string Contact { get; set; }
        public string Name2 { get; set; }
        public string Status { get; set; }
        public string Email { get; set; }
        public Nullable<int> Due_days { get; set; }
        public string Text4 { get; set; }
        public Nullable<decimal> Ren_defcom { get; set; }
        public string Ren_pol { get; set; }
        public Nullable<decimal> Ren_com { get; set; }
        public Nullable<int> Agent_type_ATM1_VTId { get; set; }
        public string Client_pay_def { get; set; }
        public string Franchise { get; set; }
        public string C_Group { get; set; }
        public string Area { get; set; }
        public string Pol1 { get; set; }
        public Nullable<decimal> Com1 { get; set; }
        public string Pol2 { get; set; }
        public Nullable<decimal> Com2 { get; set; }
        public string Pol3 { get; set; }
        public Nullable<decimal> Com3 { get; set; }
        public string Pol4 { get; set; }
        public Nullable<decimal> Com4 { get; set; }
        public string Pol5 { get; set; }
        public Nullable<decimal> Com5 { get; set; }
        public string Pol6 { get; set; }
        public Nullable<decimal> Com6 { get; set; }
        public string Pol7 { get; set; }
        public Nullable<decimal> Com7 { get; set; }
        public string Pol8 { get; set; }
        public Nullable<decimal> Com8 { get; set; }
        public string Pol9 { get; set; }
        public Nullable<decimal> Com9 { get; set; }
        public string Pol10 { get; set; }
        public Nullable<decimal> Com10 { get; set; }
        public string Pol11 { get; set; }
        public Nullable<decimal> Com11 { get; set; }
        public string Pol12 { get; set; }
        public Nullable<decimal> Com12 { get; set; }
        public string Pol13 { get; set; }
        public Nullable<decimal> Com13 { get; set; }
        public string Pol14 { get; set; }
        public Nullable<decimal> Com14 { get; set; }
        public string Pol15 { get; set; }
        public Nullable<decimal> Com15 { get; set; }
        public string Pol16 { get; set; }
        public Nullable<decimal> Com16 { get; set; }
        public string Pol17 { get; set; }
        public Nullable<decimal> Com17 { get; set; }
        public string Pol18 { get; set; }
        public Nullable<decimal> Com18 { get; set; }
        public string Pol19 { get; set; }
        public Nullable<decimal> Com19 { get; set; }
        public string Pol20 { get; set; }
        public Nullable<decimal> Com20 { get; set; }
        public string Ren_pol1 { get; set; }
        public Nullable<decimal> Ren_com1 { get; set; }
        public string Ren_pol2 { get; set; }
        public Nullable<decimal> Ren_com2 { get; set; }
        public string Ren_pol3 { get; set; }
        public Nullable<decimal> Ren_com3 { get; set; }
        public string Ren_pol4 { get; set; }
        public Nullable<decimal> Ren_com4 { get; set; }
        public string Ren_pol5 { get; set; }
        public Nullable<decimal> Ren_com5 { get; set; }
        public string Ren_pol6 { get; set; }
        public Nullable<decimal> Ren_com6 { get; set; }
        public string Ren_pol7 { get; set; }
        public Nullable<decimal> Ren_com7 { get; set; }
        public string Ren_pol8 { get; set; }
        public Nullable<decimal> Ren_com8 { get; set; }
        public string Ren_pol9 { get; set; }
        public Nullable<decimal> Ren_com9 { get; set; }
        public string Ren_pol0 { get; set; }
        public Nullable<decimal> Ren_com10 { get; set; }
        public string Ren_pol11 { get; set; }
        public Nullable<decimal> Ren_com11 { get; set; }
        public string Ren_pol12 { get; set; }
        public Nullable<decimal> Ren_com12 { get; set; }
        public string Ren_pol13 { get; set; }
        public Nullable<decimal> Ren_com13 { get; set; }
        public string Ren_pol14 { get; set; }
        public Nullable<decimal> Ren_com14 { get; set; }
        public string Ren_pol15 { get; set; }
        public Nullable<decimal> Ren_com15 { get; set; }
        public string Ren_pol16 { get; set; }
        public Nullable<decimal> Ren_com16 { get; set; }
        public string Ren_pol17 { get; set; }
        public Nullable<decimal> Ren_com17 { get; set; }
        public string Ren_pol18 { get; set; }
        public Nullable<decimal> Ren_com18 { get; set; }
        public string Ren_pol19 { get; set; }
        public Nullable<decimal> Ren_com19 { get; set; }
        public string Ren_pol20 { get; set; }
        public Nullable<decimal> Ren_com20 { get; set; }
        public string Grp { get; set; }
        public string Agent_pay { get; set; }
        public string C_Class { get; set; }
        public Nullable<int> Subclass_ATM1_VTId { get; set; }
        public string Mainagent { get; set; }
        public string Commbasis { get; set; }
        public string Howpaid { get; set; }
        public string Contactemail1 { get; set; }
        public string Contactemail2 { get; set; }
        public string Contactemail3 { get; set; }
        public string Contactemail4 { get; set; }
        public string Contactemail5 { get; set; }
        public string Contactemail { get; set; }
        public Nullable<int> Contactinfo1_B038_VTId { get; set; }
        public Nullable<int> Contactinfo2_B038_VTId { get; set; }
        public Nullable<int> Contactinfo3_B038_VTId { get; set; }
        public Nullable<int> Contactinfo4_B038_VTId { get; set; }
        public Nullable<int> Contactinfo5_B038_VTId { get; set; }
        public Nullable<int> Contactinfo_B038_VTId { get; set; }
        public string Notes1 { get; set; }
        public string Notes2 { get; set; }
        public string Notes3 { get; set; }
        public string Notes4 { get; set; }
        public string Notes5 { get; set; }
        public string Notes6 { get; set; }
        public string Notes7 { get; set; }
        public string Notes8 { get; set; }
        public string Notes9 { get; set; }
        public string Notes10 { get; set; }
        public string Notes11 { get; set; }
        public string Notes12 { get; set; }
        public string Notes13 { get; set; }
        public string Notes14 { get; set; }
        public string Notes15 { get; set; }
        public string Notes16 { get; set; }
        public string Notes17 { get; set; }
        public string Notes18 { get; set; }
        public string Notes19 { get; set; }
        public string Notes20 { get; set; }
        public string Notes { get; set; }
        public string Opcode { get; set; }
        public Nullable<System.DateTime> Lastdate { get; set; }
        public string Lasttime { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
