//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_DAPR
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<System.DateTime> Dpcdategiven1 { get; set; }
        public string Dpcconsentto1 { get; set; }
        public string Dpcconsenttype1 { get; set; }
        public Nullable<System.DateTime> Dpcdateretract1 { get; set; }
        public Nullable<System.DateTime> Dpcdategiven2 { get; set; }
        public string Dpcconsentto2 { get; set; }
        public string Dpcconsenttype2 { get; set; }
        public Nullable<System.DateTime> Dpcdateretract2 { get; set; }
        public Nullable<System.DateTime> Dpcdategiven3 { get; set; }
        public string Dpcconsentto3 { get; set; }
        public string Dpcconsenttype3 { get; set; }
        public Nullable<System.DateTime> Dpcdateretract3 { get; set; }
        public Nullable<System.DateTime> Mcdategiven1 { get; set; }
        public string Mcconsentto1 { get; set; }
        public string Mcconsenttype1 { get; set; }
        public Nullable<System.DateTime> Mcdateretract1 { get; set; }
        public Nullable<System.DateTime> Mcdategiven2 { get; set; }
        public string Mcconsentto2 { get; set; }
        public string Mcconsenttype2 { get; set; }
        public Nullable<System.DateTime> Mcdateretract2 { get; set; }
        public Nullable<int> Ccmsms_YENO_VTId { get; set; }
        public Nullable<int> Ccmemail_YENO_VTId { get; set; }
        public Nullable<int> Ccmtele_YENO_VTId { get; set; }
        public Nullable<int> Ccmpost_YENO_VTId { get; set; }
        public string Ccmsmsrequest { get; set; }
        public string Ccmemailrequest { get; set; }
        public string Ccmtelerequest { get; set; }
        public string Ccmpostrequest { get; set; }
        public string Ccmsmsretract { get; set; }
        public string Ccmemailretract { get; set; }
        public string Ccmteleretract { get; set; }
        public string Ccmpostretract { get; set; }
        public Nullable<System.DateTime> Ccmrequested1 { get; set; }
        public Nullable<System.DateTime> Ccmrequested2 { get; set; }
        public Nullable<System.DateTime> Ccmrequested3 { get; set; }
        public Nullable<System.DateTime> Ccmrequested4 { get; set; }
        public Nullable<System.DateTime> Ccmretracted1 { get; set; }
        public Nullable<System.DateTime> Ccmretracted2 { get; set; }
        public Nullable<System.DateTime> Ccmretracted3 { get; set; }
        public Nullable<System.DateTime> Ccmretracted4 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
