//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_HW
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<System.DateTime> C_From { get; set; }
        public string Riskaddr1 { get; set; }
        public string Riskaddr2 { get; set; }
        public string Riskaddr3 { get; set; }
        public string Riskaddr4 { get; set; }
        public string Riskpcode { get; set; }
        public string Commaddr1 { get; set; }
        public string Commaddr2 { get; set; }
        public string Commaddr3 { get; set; }
        public string Commaddr4 { get; set; }
        public string Commpcode { get; set; }
        public string Insurerscheme { get; set; }
        public string Hwcode { get; set; }
        public string Buildings { get; set; }
        public string Contents { get; set; }
        public string Allrisks { get; set; }
        public string Specitems { get; set; }
        public string C_Money { get; set; }
        public string Creditcards { get; set; }
        public string Freezercontents { get; set; }
        public string Legalexpenses { get; set; }
        public string Caravans { get; set; }
        public string Boats { get; set; }
        public Nullable<int> Buildingssi { get; set; }
        public Nullable<int> Contentssi { get; set; }
        public Nullable<int> Allriskssi { get; set; }
        public Nullable<int> Specitemssi { get; set; }
        public Nullable<int> Moneysi { get; set; }
        public Nullable<int> Creditcardssi { get; set; }
        public Nullable<int> Freezercontssi { get; set; }
        public Nullable<int> Legalexpensessi { get; set; }
        public Nullable<int> Caravanssi { get; set; }
        public Nullable<int> Boatssi { get; set; }
        public Nullable<int> Cyclessi { get; set; }
        public string Buildingscover { get; set; }
        public string Contentscover { get; set; }
        public string Cycles { get; set; }
        public string Notes1 { get; set; }
        public string Notes2 { get; set; }
        public Nullable<System.DateTime> Initialcoverdate { get; set; }
        public Nullable<int> Specifiedcontentstotal { get; set; }
        public Nullable<int> Singlearticlelimit { get; set; }
        public Nullable<int> Bikelimit { get; set; }
        public Nullable<int> Unspecifiedallriskstotal { get; set; }
        public Nullable<int> Specifiedallriskstotal { get; set; }
        public Nullable<int> Moneylimit { get; set; }
        public Nullable<int> Specifiedbikestotal { get; set; }
        public string Notes3 { get; set; }
        public Nullable<int> Speccontentssi { get; set; }
        public Nullable<int> Country { get; set; }
        public string End_of_record { get; set; }
        public string Riskeircode { get; set; }
        public string Commeircode { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
