//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_Dadiary
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Suffix_ { get; set; }
        public string Polref { get; set; }
        public string Policy { get; set; }
        public Nullable<int> Key_suffix { get; set; }
        public string C_Type { get; set; }
        public string Reply_stat { get; set; }
        public Nullable<System.DateTime> Entry_date { get; set; }
        public Nullable<System.DateTime> S_entry_date { get; set; }
        public Nullable<int> Doc_type_DOCT_VTId { get; set; }
        public Nullable<int> Reply_due { get; set; }
        public string C_Note { get; set; }
        public string Note_prefix { get; set; }
        public string Note_suffix { get; set; }
        public Nullable<int> No_of_copies { get; set; }
        public string C_Exec { get; set; }
        public string Operator { get; set; }
        public Nullable<int> Ins_co_INSC_VTId { get; set; }
        public string Note_prefix2 { get; set; }
        public string Note_suffix2 { get; set; }
        public string Note_suffix3 { get; set; }
        public Nullable<int> Office_IOFF_VTId { get; set; }
        public string Note_doc_type { get; set; }
        public string Nickname { get; set; }
        public string C_Key { get; set; }
        public Nullable<int> Btx_link { get; set; }
        public string Ch_seq_id { get; set; }
        public Nullable<int> Ch_seq_pos { get; set; }
        public string Permanent { get; set; }
        public string Event_type { get; set; }
        public string Owner { get; set; }
        public string Diary_type { get; set; }
        public string Apm_transfer { get; set; }
        public Nullable<int> Claim_ref { get; set; }
        public string Client_ref { get; set; }
        public Nullable<System.DateTime> Date_completed { get; set; }
        public string Completed_op { get; set; }
        public string Create_op { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public string Create_time { get; set; }
        public string Create_time_hh { get; set; }
        public string Create_time_mm { get; set; }
        public string Prospect { get; set; }
        public string Prosp_pol { get; set; }
        public string Wpiool { get; set; }
        public string Duetime { get; set; }
        public string Contactkey { get; set; }
        public string Ci_source { get; set; }
        public string Ci_sourceref { get; set; }
        public string Ci_brclientref { get; set; }
        public string Ci_prospectref { get; set; }
        public Nullable<int> Ci_suffix { get; set; }
        public string Sendtoemail { get; set; }
        public string Alloc_fromexec { get; set; }
        public string Alloc_byop { get; set; }
        public Nullable<System.DateTime> Alloc_date { get; set; }
        public string Alloc_time { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
