//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_HE
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<System.DateTime> C_From { get; set; }
        public Nullable<System.DateTime> Cover_on { get; set; }
        public string Cover_time_hh { get; set; }
        public string Cover_time_mm { get; set; }
        public Nullable<int> Proposal_H013_VTId { get; set; }
        public Nullable<int> Bst_fee_H013_VTId { get; set; }
        public Nullable<int> Security_H013_VTId { get; set; }
        public Nullable<int> Ncb_H013_VTId { get; set; }
        public Nullable<int> Nhbc_H013_VTId { get; set; }
        public Nullable<int> Structural_H013_VTId { get; set; }
        public Nullable<int> Survey_H013_VTId { get; set; }
        public Nullable<int> Valuation_H013_VTId { get; set; }
        public string Crtd_time_mm { get; set; }
        public string Crtd_time_hh { get; set; }
        public Nullable<System.DateTime> Crtd_on { get; set; }
        public string Cnvd_time_hh { get; set; }
        public string Cnvd_time_mm { get; set; }
        public string Crtd_op { get; set; }
        public Nullable<int> Edi_status_H014_VTId { get; set; }
        public string Refer_prem_adjust { get; set; }
        public string Signed_prop { get; set; }
        public string Will_decline { get; set; }
        public Nullable<System.DateTime> Cnvd_on { get; set; }
        public Nullable<System.DateTime> Tx_on { get; set; }
        public string Cnvd_op { get; set; }
        public Nullable<int> C_Sequence { get; set; }
        public Nullable<int> Edi_ptr { get; set; }
        public Nullable<System.DateTime> Edi_issue_dt { get; set; }
        public string Authorisation { get; set; }
        public string Incomplete { get; set; }
        public string End_of_record { get; set; }
        public Nullable<int> Menuoption_H024_VTId { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
