//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_13
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Driver { get; set; }
        public string Licence_restrict { get; set; }
        public Nullable<System.DateTime> Date_onset { get; set; }
        public string Diabetes { get; set; }
        public Nullable<int> Diab_years_stable { get; set; }
        public string Diab_coma { get; set; }
        public string Diab_control { get; set; }
        public string Deafness { get; set; }
        public string Epilepsy { get; set; }
        public string Blindness { get; set; }
        public string Blind_disease { get; set; }
        public string Heart_attack { get; set; }
        public string Heart_multi { get; set; }
        public string Heart_bypass { get; set; }
        public string Bypass_multi { get; set; }
        public string Loss_limb { get; set; }
        public string Car_modified { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
