//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_AR
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Arlim { get; set; }
        public Nullable<int> F_2 { get; set; }
        public string Item1 { get; set; }
        public Nullable<int> Sum1 { get; set; }
        public Nullable<decimal> Rate1 { get; set; }
        public string P1 { get; set; }
        public string F_7 { get; set; }
        public string Item2 { get; set; }
        public Nullable<int> Sum2 { get; set; }
        public Nullable<decimal> Rate2 { get; set; }
        public string P2 { get; set; }
        public string F_12 { get; set; }
        public string Item3 { get; set; }
        public Nullable<int> Sum3 { get; set; }
        public Nullable<decimal> Rate3 { get; set; }
        public string P3 { get; set; }
        public string F_17 { get; set; }
        public string Item4 { get; set; }
        public Nullable<int> Sum4 { get; set; }
        public Nullable<decimal> Rate4 { get; set; }
        public string P4 { get; set; }
        public string F_22 { get; set; }
        public string Item5 { get; set; }
        public Nullable<int> Sum5 { get; set; }
        public Nullable<decimal> Rate5 { get; set; }
        public string P5 { get; set; }
        public string F_27 { get; set; }
        public string Item6 { get; set; }
        public Nullable<int> Sum6 { get; set; }
        public Nullable<decimal> Rate6 { get; set; }
        public string P6 { get; set; }
        public string F_32 { get; set; }
        public string Item7 { get; set; }
        public Nullable<int> Sum7 { get; set; }
        public Nullable<decimal> Rate7 { get; set; }
        public string P7 { get; set; }
        public string F_37 { get; set; }
        public string Item8 { get; set; }
        public Nullable<int> Sum8 { get; set; }
        public Nullable<decimal> Rate8 { get; set; }
        public string P8 { get; set; }
        public string F_42 { get; set; }
        public string Item9 { get; set; }
        public Nullable<int> Sum9 { get; set; }
        public Nullable<decimal> Rate9 { get; set; }
        public string P9 { get; set; }
        public string F_47 { get; set; }
        public string Item10 { get; set; }
        public Nullable<int> Sum10 { get; set; }
        public Nullable<decimal> Rate10 { get; set; }
        public string P10 { get; set; }
        public string F_52 { get; set; }
        public string Item11 { get; set; }
        public Nullable<int> Sum11 { get; set; }
        public Nullable<decimal> Rate11 { get; set; }
        public string P11 { get; set; }
        public string F_57 { get; set; }
        public string Item12 { get; set; }
        public Nullable<int> Sum12 { get; set; }
        public Nullable<decimal> Rate12 { get; set; }
        public string P12 { get; set; }
        public string F_62 { get; set; }
        public string Item13 { get; set; }
        public Nullable<int> Sum13 { get; set; }
        public Nullable<decimal> Rate13 { get; set; }
        public string P13 { get; set; }
        public string F_67 { get; set; }
        public string Item14 { get; set; }
        public Nullable<int> Sum14 { get; set; }
        public Nullable<decimal> Rate14 { get; set; }
        public string P14 { get; set; }
        public string F_72 { get; set; }
        public string Item15 { get; set; }
        public Nullable<int> Sum15 { get; set; }
        public Nullable<decimal> Rate15 { get; set; }
        public string P15 { get; set; }
        public string F_77 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
