//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_THAE_History
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> END_1 { get; set; }
        public Nullable<int> END_2 { get; set; }
        public Nullable<int> END_3 { get; set; }
        public Nullable<int> END_4 { get; set; }
        public Nullable<int> END_5 { get; set; }
        public Nullable<int> END_6 { get; set; }
        public Nullable<int> END_7 { get; set; }
        public Nullable<int> END_8 { get; set; }
        public Nullable<int> END_9 { get; set; }
        public Nullable<int> END_10 { get; set; }
        public Nullable<int> END_11 { get; set; }
        public Nullable<int> END_12 { get; set; }
        public Nullable<int> END_13 { get; set; }
        public Nullable<int> END_14 { get; set; }
        public Nullable<int> END_15 { get; set; }
        public Nullable<int> END_16 { get; set; }
        public Nullable<int> END_17 { get; set; }
        public Nullable<int> END_18 { get; set; }
        public Nullable<int> END_19 { get; set; }
        public Nullable<int> END_20 { get; set; }
        public Nullable<int> END_21 { get; set; }
        public Nullable<int> END_22 { get; set; }
        public Nullable<int> END_23 { get; set; }
        public Nullable<int> END_24 { get; set; }
        public string ADD1 { get; set; }
        public string ADD2 { get; set; }
        public string ADD3 { get; set; }
        public string ADD4 { get; set; }
        public string ADD5 { get; set; }
        public string ADD6 { get; set; }
        public string ADD7 { get; set; }
        public string ADD8 { get; set; }
        public string ADD9 { get; set; }
        public string ADD10 { get; set; }
        public string ADD11 { get; set; }
        public string ADD12 { get; set; }
        public string ADD13 { get; set; }
        public Nullable<System.DateTime> History_ { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
