//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BF_HN
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<System.DateTime> C_From { get; set; }
        public Nullable<int> C_Sequence { get; set; }
        public Nullable<int> Propno { get; set; }
        public Nullable<int> Propsex_QR25_VTId { get; set; }
        public Nullable<int> Proptitle_H001_VTId { get; set; }
        public string Fullpart1 { get; set; }
        public string Fullpart2 { get; set; }
        public Nullable<int> Empstat1_QR07_VTId { get; set; }
        public Nullable<int> Empstat2_QR07_VTId { get; set; }
        public string Propsurname { get; set; }
        public string Propforenames { get; set; }
        public string Propexcluded { get; set; }
        public Nullable<System.DateTime> Propdob { get; set; }
        public string Propatrisk { get; set; }
        public Nullable<int> Proprelation_QR13_VTId { get; set; }
        public Nullable<int> Propage { get; set; }
        public Nullable<int> Occtype1_QR35_VTId { get; set; }
        public Nullable<int> Bustype1_QR38_VTId { get; set; }
        public Nullable<int> Occtype2_QR35_VTId { get; set; }
        public Nullable<int> Bustype2_QR38_VTId { get; set; }
        public Nullable<System.DateTime> Convdate { get; set; }
        public string Convpending { get; set; }
        public Nullable<int> Convtype_H01E_VTId { get; set; }
        public Nullable<System.DateTime> Convdate1 { get; set; }
        public string Convpending1 { get; set; }
        public Nullable<int> Convtype1_H01E_VTId { get; set; }
        public Nullable<System.DateTime> Convdate2 { get; set; }
        public string Convpending2 { get; set; }
        public Nullable<int> Convtype2_H01E_VTId { get; set; }
        public Nullable<System.DateTime> Convdate3 { get; set; }
        public string Convpending3 { get; set; }
        public Nullable<int> Convtype3_H01E_VTId { get; set; }
        public string Creationsource { get; set; }
        public string Updatedbyuser { get; set; }
        public string End_record { get; set; }
        public Nullable<int> Proposerchecksum { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
