//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_AGM
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Childrenunder16 { get; set; }
        public Nullable<int> Vehicleimported_CQ01_VTId { get; set; }
        public Nullable<int> Renewalprice { get; set; }
        public Nullable<int> Preferredpaymnt_CQ02_VTId { get; set; }
        public string Telematicsagrd { get; set; }
        public Nullable<int> Nightuse_CQ03_VTId { get; set; }
        public Nullable<int> Nightpassengers_CQN1_VTId { get; set; }
        public Nullable<int> Carsinhousehold_CQN2_VTId { get; set; }
        public string Peakuse { get; set; }
        public string Ownprevins { get; set; }
        public Nullable<int> Housetype_CQ04_VTId { get; set; }
        public Nullable<int> Daytimelocation_CQ05_VTId { get; set; }
        public string Endofrecord { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
