//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_QX1
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Topname { get; set; }
        public string Topcode { get; set; }
        public string Topstatus { get; set; }
        public Nullable<decimal> Topprem { get; set; }
        public Nullable<int> Toptotxs { get; set; }
        public Nullable<int> Toppolxs1 { get; set; }
        public Nullable<int> Toppolxs2 { get; set; }
        public Nullable<int> Toppolxs3 { get; set; }
        public Nullable<int> Toppolxs4 { get; set; }
        public string Toppolxs1type { get; set; }
        public string Toppolxs1code { get; set; }
        public string Toppolxs2type { get; set; }
        public string Toppolxs2code { get; set; }
        public string Toppolxs3type { get; set; }
        public string Toppolxs3code { get; set; }
        public string Toppolxs4type { get; set; }
        public string Toppolxs4code { get; set; }
        public Nullable<int> Topdrvxs1 { get; set; }
        public Nullable<int> Topdrvxs2 { get; set; }
        public Nullable<int> Topdrvxs3 { get; set; }
        public Nullable<int> Topdrvxs4 { get; set; }
        public Nullable<int> Topdrvxs5 { get; set; }
        public string Topdrvxs1type { get; set; }
        public string Topdrvxs1code { get; set; }
        public string Topdrvxs2type { get; set; }
        public string Topdrvxs2code { get; set; }
        public string Topdrvxs3type { get; set; }
        public string Topdrvxs3code { get; set; }
        public string Topdrvxs4type { get; set; }
        public string Topdrvxs4code { get; set; }
        public string Topdrvxs5type { get; set; }
        public string Topdrvxs5code { get; set; }
        public string Botname { get; set; }
        public string Botcode { get; set; }
        public string Botstatus { get; set; }
        public Nullable<decimal> Botprem { get; set; }
        public Nullable<int> Bottotxs { get; set; }
        public Nullable<int> Botpolxs1 { get; set; }
        public Nullable<int> Botpolxs2 { get; set; }
        public Nullable<int> Botpolxs3 { get; set; }
        public Nullable<int> Botpolxs4 { get; set; }
        public string Botpolxs1type { get; set; }
        public string Botpolxs1code { get; set; }
        public string Botpolxs2type { get; set; }
        public string Botpolxs2code { get; set; }
        public string Botpolxs3type { get; set; }
        public string Botpolxs3code { get; set; }
        public string Botpolxs4type { get; set; }
        public string Botpolxs4code { get; set; }
        public Nullable<int> Botdrvxs1 { get; set; }
        public Nullable<int> Botdrvxs2 { get; set; }
        public Nullable<int> Botdrvxs3 { get; set; }
        public Nullable<int> Botdrvxs4 { get; set; }
        public Nullable<int> Botdrvxs5 { get; set; }
        public string Botdrvxs1type { get; set; }
        public string Botdrvxs1code { get; set; }
        public string Botdrvxs2type { get; set; }
        public string Botdrvxs2code { get; set; }
        public string Botdrvxs3type { get; set; }
        public string Botdrvxs3code { get; set; }
        public string Botdrvxs4type { get; set; }
        public string Botdrvxs4code { get; set; }
        public string Botdrvxs5type { get; set; }
        public string Botdrvxs5code { get; set; }
        public string Ratesused { get; set; }
        public Nullable<System.DateTime> Quotedate { get; set; }
        public string Quotetime { get; set; }
        public Nullable<int> Topnum { get; set; }
        public Nullable<int> Botnum { get; set; }
        public Nullable<int> Totalframes { get; set; }
        public string Endofrecord { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
