//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_TV_History
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Pckge { get; set; }
        public Nullable<System.DateTime> Stdate { get; set; }
        public Nullable<System.DateTime> Endate { get; set; }
        public string Area1 { get; set; }
        public string Area2 { get; set; }
        public string Area3 { get; set; }
        public string Area4 { get; set; }
        public string Per1 { get; set; }
        public Nullable<int> Pa1 { get; set; }
        public Nullable<int> Med1 { get; set; }
        public Nullable<int> Canc1 { get; set; }
        public string Per2 { get; set; }
        public Nullable<int> Pa2 { get; set; }
        public Nullable<int> Med2 { get; set; }
        public Nullable<int> Canc2 { get; set; }
        public string Per3 { get; set; }
        public Nullable<int> Pa3 { get; set; }
        public Nullable<int> Med3 { get; set; }
        public Nullable<int> Canc3 { get; set; }
        public string Per4 { get; set; }
        public Nullable<int> Pa4 { get; set; }
        public Nullable<int> Med4 { get; set; }
        public Nullable<int> Canc4 { get; set; }
        public string Per5 { get; set; }
        public Nullable<int> Pa5 { get; set; }
        public Nullable<int> Med5 { get; set; }
        public Nullable<int> Canc5 { get; set; }
        public Nullable<decimal> Pr1 { get; set; }
        public Nullable<decimal> Pr2 { get; set; }
        public Nullable<decimal> Pr3 { get; set; }
        public Nullable<int> Bagval { get; set; }
        public Nullable<int> Mon { get; set; }
        public Nullable<int> Totsi { get; set; }
        public Nullable<decimal> Totpr { get; set; }
        public Nullable<int> Bag { get; set; }
        public string Annu { get; set; }
        public string F_37 { get; set; }
        public string Bagg1 { get; set; }
        public string Bagg2 { get; set; }
        public string Bagg3 { get; set; }
        public string Bagg4 { get; set; }
        public string Bagg5 { get; set; }
        public Nullable<System.DateTime> History_ { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
