//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_CX
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> Adddriv { get; set; }
        public string C_Name { get; set; }
        public Nullable<int> Occcd { get; set; }
        public string Physdef { get; set; }
        public string Lictype { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DatObtain { get; set; }
        public Nullable<System.DateTime> DatUKEnt { get; set; }
        public string BroScheme { get; set; }
        public Nullable<int> IncLim { get; set; }
        public string TRFrm { get; set; }
        public string Comm1 { get; set; }
        public string Comm2 { get; set; }
        public string Comm3 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
