//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_MC
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<int> Esize { get; set; }
        public string Reg { get; set; }
        public Nullable<System.DateTime> Regdate { get; set; }
        public Nullable<int> C_Value { get; set; }
        public string Body { get; set; }
        public string Eec { get; set; }
        public string Foregn { get; set; }
        public string Cover { get; set; }
        public string Drivers { get; set; }
        public string Ridspec { get; set; }
        public Nullable<System.DateTime> Ncbdate { get; set; }
        public Nullable<int> Excess { get; set; }
        public string Ratarea { get; set; }
        public string Ncbprej { get; set; }
        public string Othbike { get; set; }
        public string Accconv { get; set; }
        public Nullable<int> Compxs1 { get; set; }
        public string Compxs2 { get; set; }
        public Nullable<int> Ridlimit { get; set; }
        public string Ratdesc { get; set; }
        public Nullable<decimal> Ncbdisc { get; set; }
        public Nullable<int> Ncbyears { get; set; }
        public string Comm { get; set; }
        public string Occ { get; set; }
        public Nullable<int> Occcd { get; set; }
        public string Physdef { get; set; }
        public string Lictype { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<System.DateTime> Datob { get; set; }
        public Nullable<System.DateTime> Datukent { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
