//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_H9
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<System.DateTime> C_From { get; set; }
        public string Home_phoneno { get; set; }
        public string Reasoncommdiff { get; set; }
        public string Prevaddr1 { get; set; }
        public string Prevaddr2 { get; set; }
        public string Prevaddr3 { get; set; }
        public string Prevaddr4 { get; set; }
        public string Prevpcode { get; set; }
        public string Comm_daytime { get; set; }
        public Nullable<int> C_Sequence { get; set; }
        public string End_of_record { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
