//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_H7_History
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<System.DateTime> C_From { get; set; }
        public Nullable<int> End_excess { get; set; }
        public Nullable<int> C_Number { get; set; }
        public Nullable<int> Reason_H00C_VTId { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public string Endcode { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public Nullable<int> C_Sequence { get; set; }
        public string Adddesc1 { get; set; }
        public string Adddesc2 { get; set; }
        public string Adddesc3 { get; set; }
        public string Adddesc4 { get; set; }
        public string Adddesc5 { get; set; }
        public string Deletedatnb { get; set; }
        public Nullable<decimal> Amount1 { get; set; }
        public Nullable<decimal> Amount2 { get; set; }
        public Nullable<decimal> Amount3 { get; set; }
        public Nullable<int> Number1 { get; set; }
        public Nullable<int> Number2 { get; set; }
        public string Creationstat { get; set; }
        public string Hen_description { get; set; }
        public Nullable<System.DateTime> Effectivedate { get; set; }
        public Nullable<int> Endoexcess { get; set; }
        public Nullable<int> Sinumber { get; set; }
        public Nullable<int> Endreason_H00C_VTId { get; set; }
        public Nullable<System.DateTime> Enddate { get; set; }
        public string Code { get; set; }
        public string Text1 { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public string Text4 { get; set; }
        public string Text5 { get; set; }
        public Nullable<decimal> Decimal1 { get; set; }
        public Nullable<decimal> Decimal2 { get; set; }
        public Nullable<decimal> Decimal3 { get; set; }
        public Nullable<int> Value1 { get; set; }
        public Nullable<int> Value2 { get; set; }
        public string Endofrecord { get; set; }
        public string Endodescription { get; set; }
        public string Hipreference { get; set; }
        public string Dypvalue { get; set; }
        public string Dypvalue1 { get; set; }
        public Nullable<System.DateTime> History_ { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
