//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_ECOV
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Dts { get; set; }
        public string Thirdparty { get; set; }
        public string Accidentdental { get; set; }
        public string Trailer { get; set; }
        public string Saddle_required { get; set; }
        public Nullable<int> Saddle_value { get; set; }
        public string Plou { get; set; }
        public string Vet_required { get; set; }
        public string Vet_excess { get; set; }
        public string Vet_hospital { get; set; }
        public string Prev_ins { get; set; }
        public Nullable<System.DateTime> Prev_ind_date { get; set; }
        public Nullable<System.DateTime> Cover_date { get; set; }
        public string Coverlevel { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
