//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_QA
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> Quoteorigin_QREA_VTId { get; set; }
        public string Affiliate { get; set; }
        public Nullable<decimal> Origpremexclipt { get; set; }
        public Nullable<decimal> Origpreminclipt { get; set; }
        public Nullable<decimal> Newpremexclipt { get; set; }
        public Nullable<decimal> Newpreminclipt { get; set; }
        public Nullable<decimal> Newpremiptamt { get; set; }
        public Nullable<decimal> Diffpreminclipt { get; set; }
        public Nullable<decimal> Diffpctinclipt { get; set; }
        public Nullable<decimal> Diffpremexclipt { get; set; }
        public Nullable<decimal> Diffpctexclipt { get; set; }
        public Nullable<decimal> Brokerdiffprem { get; set; }
        public Nullable<decimal> Origcustprem { get; set; }
        public Nullable<decimal> Newcustprem { get; set; }
        public Nullable<decimal> Diffcustprem { get; set; }
        public Nullable<decimal> Origcheapprem { get; set; }
        public string Newcustpremenc { get; set; }
        public string Origcheapscheme { get; set; }
        public string Insurerauth { get; set; }
        public Nullable<decimal> Iptrate { get; set; }
        public Nullable<System.DateTime> Activequotedate { get; set; }
        public string Activequotetime { get; set; }
        public string Endofrecord { get; set; }
        public Nullable<decimal> Origcheappreminclipt { get; set; }
        public Nullable<decimal> Origcheappremexclipt { get; set; }
        public Nullable<int> Aqisfree_QR19_VTId { get; set; }
        public Nullable<int> Aq4ppresult_AQ01_VTId { get; set; }
        public Nullable<decimal> Aq4pporiginalpremiumexclipt { get; set; }
        public Nullable<decimal> Aq4pporiginalpremiuminclipt { get; set; }
        public Nullable<decimal> Aq4pporiginaliptamount { get; set; }
        public Nullable<decimal> Aq4ppnewpremiumexclipt { get; set; }
        public Nullable<decimal> Aq4ppnewpremiuminclipt { get; set; }
        public Nullable<decimal> Aq4ppnewiptamount { get; set; }
        public string Aq4ppruleversion { get; set; }
        public string Aq4ppnewquoteflag { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public Nullable<int> Referreason { get; set; }
        public Nullable<decimal> Commdiffamt { get; set; }
        public Nullable<decimal> Commdiffpct { get; set; }
        public Nullable<decimal> Commnewpremium { get; set; }
    }
}
