//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_MB2
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string C_Name { get; set; }
        public Nullable<int> Sex_QR25_VTId { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<System.DateTime> Date_of_entry { get; set; }
        public Nullable<int> Origin_country_QR43_VTId { get; set; }
        public Nullable<int> Riding_status_QR22_VTId { get; set; }
        public Nullable<int> Marital_status_QR17_VTId { get; set; }
        public Nullable<int> Licence_type_QR05_VTId { get; set; }
        public Nullable<System.DateTime> Date_obtained { get; set; }
        public Nullable<int> Licence_country_QR43_VTId { get; set; }
        public Nullable<int> Commuting_QR19_VTId { get; set; }
        public Nullable<int> Number_of_tests { get; set; }
        public Nullable<int> Years_ncb { get; set; }
        public Nullable<int> Ncb_type_QR44_VTId { get; set; }
        public Nullable<System.DateTime> Ncb_base_date { get; set; }
        public Nullable<int> Ncb_country_QR43_VTId { get; set; }
        public Nullable<int> Homeowner_QR19_VTId { get; set; }
        public Nullable<int> Drinker_QR19_VTId { get; set; }
        public Nullable<int> Smoker_QR19_VTId { get; set; }
        public Nullable<int> Claims_QR19_VTId { get; set; }
        public Nullable<int> Convictions_QR19_VTId { get; set; }
        public Nullable<int> Disabled_QR19_VTId { get; set; }
        public Nullable<int> Occupation_type1_QR35_VTId { get; set; }
        public Nullable<int> Business_type1_QR38_VTId { get; set; }
        public Nullable<int> Employment_status1_QR07_VTId { get; set; }
        public string Fullpart1 { get; set; }
        public Nullable<int> Occupation_type2_QR35_VTId { get; set; }
        public Nullable<int> Business_type2_QR38_VTId { get; set; }
        public Nullable<int> Employment_status2_QR07_VTId { get; set; }
        public string Fullpart2 { get; set; }
        public Nullable<int> Personal_business_QR19_VTId { get; set; }
        public Nullable<int> Related_business_QR19_VTId { get; set; }
        public Nullable<int> Anothers_business_QR19_VTId { get; set; }
        public Nullable<int> Soliciting_QR19_VTId { get; set; }
        public Nullable<int> Carriage_of_goods_QR19_VTId { get; set; }
        public Nullable<int> Private_hire_QR19_VTId { get; set; }
        public Nullable<int> Public_hire_QR19_VTId { get; set; }
        public Nullable<int> Delivery_service_QR19_VTId { get; set; }
        public Nullable<int> Despatch_rider_QR19_VTId { get; set; }
        public Nullable<int> Courier_service_QR19_VTId { get; set; }
        public Nullable<int> Fast_food_service_QR19_VTId { get; set; }
        public string Auto_renewal { get; set; }
        public string Add_rider { get; set; }
        public Nullable<int> Relation_to_main_QR13_VTId { get; set; }
        public Nullable<int> Access_other_vehicle_QR19_VTId { get; set; }
        public Nullable<int> Own_vehicle_QR19_VTId { get; set; }
        public Nullable<int> Own_vehicle_type_QR44_VTId { get; set; }
        public Nullable<System.DateTime> Own_ncb_date { get; set; }
        public string Own_inscode { get; set; }
        public Nullable<int> Own_insurer_QR54_VTId { get; set; }
        public Nullable<int> Company_vehicle_QR19_VTId { get; set; }
        public Nullable<System.DateTime> Company_years_date { get; set; }
        public Nullable<System.DateTime> Company_date_ended { get; set; }
        public Nullable<int> Company_sole_use_QR19_VTId { get; set; }
        public Nullable<int> Motoring_org_trigger_QR19_VTId { get; set; }
        public Nullable<int> Organisation1_QR89_VTId { get; set; }
        public Nullable<int> Organisation2_QR89_VTId { get; set; }
        public Nullable<int> Organisation3_QR89_VTId { get; set; }
        public Nullable<System.DateTime> Cbt_date_obtained { get; set; }
        public Nullable<int> Accothervehicle_QR19_VTId { get; set; }
        public Nullable<int> Ownvehicletype_QR44_VTId { get; set; }
        public Nullable<System.DateTime> Compyearsdate { get; set; }
        public Nullable<System.DateTime> Compdateended { get; set; }
        public Nullable<int> Companysoleuse_QR19_VTId { get; set; }
        public Nullable<int> Title_QRTL_VTId { get; set; }
        public string Surname { get; set; }
        public string Forename { get; set; }
        public Nullable<int> Dvlanotified_QR19_VTId { get; set; }
        public Nullable<int> Riderregdis_QR19_VTId { get; set; }
        public Nullable<int> Riderdisbadge_QR19_VTId { get; set; }
        public Nullable<int> Autoonly_QR19_VTId { get; set; }
        public Nullable<int> Riderxs { get; set; }
        public string Riderxstype { get; set; }
        public Nullable<int> Temprider_QR19_VTId { get; set; }
        public Nullable<System.DateTime> Tempriderexpirydate { get; set; }
        public string Tempriderexpirytime { get; set; }
        public string End_of_record { get; set; }
        public Nullable<System.DateTime> Cbt_pass_date { get; set; }
        public Nullable<int> Emp_status1_QR07_VTId { get; set; }
        public Nullable<int> Emp_status2_QR07_VTId { get; set; }
        public Nullable<int> Personalbusiness_QR19_VTId { get; set; }
        public Nullable<int> Anothersbusiness_QR19_VTId { get; set; }
        public Nullable<int> Carrying_goods_QR19_VTId { get; set; }
        public Nullable<int> Other_vehicles_QR19_VTId { get; set; }
        public Nullable<System.DateTime> Cmpny_years_date { get; set; }
        public Nullable<System.DateTime> Cmpny_date_ended { get; set; }
        public Nullable<decimal> Percentncb { get; set; }
        public Nullable<int> Aqquoteorigin_QREA_VTId { get; set; }
        public string Aqaffiliate { get; set; }
        public Nullable<int> Businesssourcecode_QREA_VTId { get; set; }
        public Nullable<int> Businesssrccode_QREA_VTId { get; set; }
        public Nullable<int> Ratesyear { get; set; }
        public Nullable<int> Ratesmonth { get; set; }
        public Nullable<int> Ratesversion { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
