//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_EV_BGE
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Suffix_ { get; set; }
        public string C_From { get; set; }
        public string C_To { get; set; }
        public Nullable<int> C_Number { get; set; }
        public Nullable<int> Product_CCM1_VTId { get; set; }
        public Nullable<int> C_Type_CCM2_VTId { get; set; }
        public Nullable<System.DateTime> Dt_raised { get; set; }
        public Nullable<System.DateTime> Dt_acknowl { get; set; }
        public Nullable<System.DateTime> Dt_resolved { get; set; }
        public Nullable<System.DateTime> Dt_referred { get; set; }
        public string Classification { get; set; }
        public string Staff { get; set; }
        public string Analysis { get; set; }
        public string Thirdparty { get; set; }
        public string Upheld { get; set; }
        public string Ref_fos { get; set; }
        public string C_Ref { get; set; }
        public Nullable<System.DateTime> Dt_upheld { get; set; }
        public Nullable<System.DateTime> Dt_ref_fos { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public string Summary { get; set; }
        public string Details_1 { get; set; }
        public string Details_2 { get; set; }
        public string Details_3 { get; set; }
        public string Details_4 { get; set; }
        public string Details_5 { get; set; }
        public string Details_6 { get; set; }
        public string Details_7 { get; set; }
        public string Details_8 { get; set; }
        public string Details_9 { get; set; }
        public string Handler { get; set; }
        public string C_Include { get; set; }
        public Nullable<int> Cause_CCM5_VTId { get; set; }
        public Nullable<int> Prodserv_CCM4_VTId { get; set; }
        public Nullable<int> Psgroup2016_CCM6_VTId { get; set; }
        public Nullable<int> Prodserv2016_CCM7_VTId { get; set; }
        public Nullable<int> Cause2016_CCM8_VTId { get; set; }
        public Nullable<int> Subcause2016_CCM9_VTId { get; set; }
        public string Psother2016 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
