//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_BP0
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Line01 { get; set; }
        public string Line02 { get; set; }
        public string Line03 { get; set; }
        public string Line04 { get; set; }
        public string Line05 { get; set; }
        public string Line06 { get; set; }
        public string Line07 { get; set; }
        public string Line08 { get; set; }
        public string Line09 { get; set; }
        public string Line10 { get; set; }
        public string Line11 { get; set; }
        public string Line12 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
