//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_bredetail
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string Code { get; set; }
        public string C_Name { get; set; }
        public string Init { get; set; }
        public string Department { get; set; }
        public string Email { get; set; }
        public string Notes1 { get; set; }
        public string Notes2 { get; set; }
        public string Jobtitle { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Status { get; set; }
        public string Ext_name { get; set; }
        public string Ext_jobtitle { get; set; }
        public string Ext_department { get; set; }
        public string Division { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
