//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_TW
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> Drivers_QR01_VTId { get; set; }
        public Nullable<int> Number_named { get; set; }
        public Nullable<int> Aged_over { get; set; }
        public Nullable<System.DateTime> Cover_date { get; set; }
        public string Business_pcode { get; set; }
        public string Ins_scheme { get; set; }
        public Nullable<int> Ever_held_ins_QR19_VTId { get; set; }
        public Nullable<int> Last_insurer_QR54_VTId { get; set; }
        public Nullable<int> Terms_imposed_QR19_VTId { get; set; }
        public Nullable<int> Holding_broker_QR19_VTId { get; set; }
        public Nullable<int> Comp_xs { get; set; }
        public Nullable<int> Policy_term { get; set; }
        public Nullable<int> Ever_refused_QR19_VTId { get; set; }
        public Nullable<int> Non_motor_convs_QR19_VTId { get; set; }
        public Nullable<int> Scheme_number { get; set; }
        public Nullable<int> Prem_load { get; set; }
        public string Cover_time { get; set; }
        public string Cover_time_hh { get; set; }
        public string F_19 { get; set; }
        public string Cover_time_mm { get; set; }
        public string Endofrecord { get; set; }
        public string Webauthenticationcode { get; set; }
        public string Webcovertime { get; set; }
        public Nullable<int> Webebuy_QR19_VTId { get; set; }
        public string Covertime { get; set; }
        public Nullable<int> Lapsedfor { get; set; }
        public Nullable<int> Lapsedtype_QR29_VTId { get; set; }
        public Nullable<int> Consentforsearches_QR19_VTId { get; set; }
        public Nullable<int> Cnsntforsearches_QR19_VTId { get; set; }
        public string Businesseircode { get; set; }
        public Nullable<System.DateTime> Quotedate { get; set; }
        public string Quotetime { get; set; }
        public Nullable<int> Ratesmonth { get; set; }
        public Nullable<int> Ratesversion { get; set; }
        public Nullable<int> Ratesyear { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public string Ratescountry { get; set; }
    }
}
