//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_TUWK_History
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Newpol { get; set; }
        public string MTA { get; set; }
        public string Cover { get; set; }
        public string Base { get; set; }
        public string Inexp_Driver { get; set; }
        public string vehicle_Type { get; set; }
        public string Driv_Age { get; set; }
        public string Drivers { get; set; }
        public string Anyother_Veh { get; set; }
        public string Volxs { get; set; }
        public string NCB_Years { get; set; }
        public string NCB_Disc { get; set; }
        public string Intro_Years { get; set; }
        public string Intro_Disc { get; set; }
        public string Accs_Conse { get; set; }
        public string Protncb { get; set; }
        public string IPT { get; set; }
        public string Broker_Fee { get; set; }
        public string Total_Prem { get; set; }
        public string Spec_restrict { get; set; }
        public string Quoteref { get; set; }
        public Nullable<System.DateTime> History_ { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
