//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_NSB
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public string C_Time { get; set; }
        public string Ratesversion { get; set; }
        public Nullable<int> Yearsncdatthisrenewal { get; set; }
        public Nullable<int> Yrsncdrnwl { get; set; }
        public Nullable<int> Yearsncd { get; set; }
        public Nullable<int> Yrsncd { get; set; }
        public Nullable<int> Ncdwithoutprotection { get; set; }
        public Nullable<int> Ncdwithoutprotection1 { get; set; }
        public Nullable<int> Ncdwithoutprotection2 { get; set; }
        public Nullable<int> Ncdwithoutprotection3 { get; set; }
        public Nullable<int> Ncdwithoutprotection4 { get; set; }
        public Nullable<int> Ncdwithoutprotection5 { get; set; }
        public Nullable<int> Ncdwithprotection { get; set; }
        public Nullable<int> Ncdwithprotectionperiod { get; set; }
        public Nullable<int> Ncdwithprotection1 { get; set; }
        public Nullable<int> Ncdwithprotection1period { get; set; }
        public Nullable<int> Ncdwithprotection2 { get; set; }
        public Nullable<int> Ncdwithprotection2period { get; set; }
        public Nullable<int> Ncdwithprotection3 { get; set; }
        public Nullable<int> Ncdwithprotection3period { get; set; }
        public Nullable<int> Ncdwithprotection4 { get; set; }
        public Nullable<int> Ncdwithprotection4period { get; set; }
        public Nullable<int> Ncdwithprotection5 { get; set; }
        public Nullable<int> Ncdwithprotection5period { get; set; }
        public Nullable<int> Ncdwithout1 { get; set; }
        public Nullable<int> Ncdwithout2 { get; set; }
        public Nullable<int> Ncdwithout3 { get; set; }
        public Nullable<int> Ncdwithout4 { get; set; }
        public Nullable<int> Ncdwithout5 { get; set; }
        public Nullable<int> Ncdwith1 { get; set; }
        public Nullable<int> Ncdwith1period { get; set; }
        public Nullable<int> Ncdwith2 { get; set; }
        public Nullable<int> Ncdwith2period { get; set; }
        public Nullable<int> Ncdwith3 { get; set; }
        public Nullable<int> Ncdwith3period { get; set; }
        public Nullable<int> Ncdwith4 { get; set; }
        public Nullable<int> Ncdwith4period { get; set; }
        public Nullable<int> Ncdwith5 { get; set; }
        public Nullable<int> Ncdwith5period { get; set; }
        public string Endofrecord { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
