//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_SE
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Cov1 { get; set; }
        public Nullable<int> SI1 { get; set; }
        public Nullable<decimal> Rat1 { get; set; }
        public string Cov2 { get; set; }
        public Nullable<int> SI2 { get; set; }
        public Nullable<decimal> Rat2 { get; set; }
        public string Cov3 { get; set; }
        public Nullable<int> SI3 { get; set; }
        public Nullable<decimal> Rat3 { get; set; }
        public string Cov4 { get; set; }
        public Nullable<int> SI4 { get; set; }
        public Nullable<decimal> Rat4 { get; set; }
        public string Cov5 { get; set; }
        public Nullable<int> SI5 { get; set; }
        public Nullable<decimal> Rat5 { get; set; }
        public string Cov6 { get; set; }
        public Nullable<int> SI6 { get; set; }
        public Nullable<decimal> Rat6 { get; set; }
        public string Cov7 { get; set; }
        public Nullable<int> SI7 { get; set; }
        public Nullable<decimal> Rat7 { get; set; }
        public string Cov8 { get; set; }
        public Nullable<decimal> Rat8 { get; set; }
        public string Cov9 { get; set; }
        public Nullable<int> SI9 { get; set; }
        public Nullable<decimal> Rat9 { get; set; }
        public string Cov10 { get; set; }
        public Nullable<decimal> Rat10 { get; set; }
        public string Cov11 { get; set; }
        public Nullable<int> SI11 { get; set; }
        public Nullable<decimal> Rat11 { get; set; }
        public string Cov12 { get; set; }
        public Nullable<int> SI12 { get; set; }
        public Nullable<decimal> Rat12 { get; set; }
        public string AlarmWarr { get; set; }
        public Nullable<System.DateTime> LTADate { get; set; }
        public string Comm1 { get; set; }
        public string Comm2 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
