//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_DPU
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> Ultins1_INSU_VTId { get; set; }
        public Nullable<int> Ultins2_INSU_VTId { get; set; }
        public Nullable<int> Ultins3_INSU_VTId { get; set; }
        public Nullable<int> Ultins4_INSU_VTId { get; set; }
        public Nullable<int> Ultins5_INSU_VTId { get; set; }
        public Nullable<int> Ultins6_INSU_VTId { get; set; }
        public Nullable<int> Ultins7_INSU_VTId { get; set; }
        public Nullable<int> Ultins8_INSU_VTId { get; set; }
        public Nullable<int> Ultins9_INSU_VTId { get; set; }
        public Nullable<int> Ultins10_INSU_VTId { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
