//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_PZ
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Subs { get; set; }
        public Nullable<int> Ded1 { get; set; }
        public string Thft { get; set; }
        public Nullable<int> Ded2 { get; set; }
        public string Trns1 { get; set; }
        public string Trns2 { get; set; }
        public Nullable<int> Ded3 { get; set; }
        public string Glss { get; set; }
        public Nullable<int> Ded4 { get; set; }
        public string Inf1 { get; set; }
        public string Inf2 { get; set; }
        public string Comm1 { get; set; }
        public string Comm2 { get; set; }
        public string Comm3 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
