//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_EL
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> EmpNo1 { get; set; }
        public Nullable<int> Wage1 { get; set; }
        public Nullable<decimal> Rate1 { get; set; }
        public Nullable<decimal> Prem1 { get; set; }
        public Nullable<int> EmpNo2 { get; set; }
        public Nullable<int> Wage2 { get; set; }
        public Nullable<decimal> Rate2 { get; set; }
        public Nullable<decimal> Prem2 { get; set; }
        public Nullable<int> EmpNo3 { get; set; }
        public Nullable<int> Wage3 { get; set; }
        public Nullable<decimal> Rate3 { get; set; }
        public Nullable<decimal> Prem3 { get; set; }
        public string Rem1 { get; set; }
        public string Rem2 { get; set; }
        public string Declr { get; set; }
        public string F_16 { get; set; }
        public Nullable<int> F_17 { get; set; }
        public string Ratng1 { get; set; }
        public Nullable<int> RatNo1 { get; set; }
        public Nullable<int> RatAm1 { get; set; }
        public Nullable<decimal> Rat1 { get; set; }
        public Nullable<decimal> Prm1 { get; set; }
        public string Ratng2 { get; set; }
        public Nullable<int> RatNo2 { get; set; }
        public Nullable<int> RatAm2 { get; set; }
        public Nullable<decimal> Rat2 { get; set; }
        public Nullable<decimal> Prm2 { get; set; }
        public string Ratng3 { get; set; }
        public Nullable<int> RatNo3 { get; set; }
        public Nullable<int> RatAm3 { get; set; }
        public Nullable<decimal> Rat3 { get; set; }
        public Nullable<decimal> Prm3 { get; set; }
        public string Ratng4 { get; set; }
        public Nullable<int> RatNo4 { get; set; }
        public Nullable<int> RatAm4 { get; set; }
        public Nullable<decimal> Rat4 { get; set; }
        public Nullable<decimal> Prm4 { get; set; }
        public string Ratng5 { get; set; }
        public Nullable<int> RatNo5 { get; set; }
        public Nullable<int> RatAm5 { get; set; }
        public Nullable<decimal> Rat5 { get; set; }
        public Nullable<decimal> Prm5 { get; set; }
        public string Ratng6 { get; set; }
        public Nullable<int> RatNo6 { get; set; }
        public Nullable<int> RatAm6 { get; set; }
        public Nullable<decimal> Rat6 { get; set; }
        public Nullable<decimal> Prm6 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
