//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_QXR
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Currname { get; set; }
        public string Currcode { get; set; }
        public string Currstatus { get; set; }
        public Nullable<decimal> Currprem { get; set; }
        public Nullable<int> Currtotxs { get; set; }
        public Nullable<int> Currpolxs1 { get; set; }
        public Nullable<int> Currpolxs2 { get; set; }
        public Nullable<int> Currpolxs3 { get; set; }
        public Nullable<int> Currpolxs4 { get; set; }
        public string Currpolxs1type { get; set; }
        public string Currpolxs1code { get; set; }
        public string Currpolxs2type { get; set; }
        public string Currpolxs2code { get; set; }
        public string Currpolxs3type { get; set; }
        public string Currpolxs3code { get; set; }
        public string Currpolxs4type { get; set; }
        public string Currpolxs4code { get; set; }
        public Nullable<int> Currdrvxs1 { get; set; }
        public Nullable<int> Currdrvxs2 { get; set; }
        public Nullable<int> Currdrvxs3 { get; set; }
        public Nullable<int> Currdrvxs4 { get; set; }
        public Nullable<int> Currdrvxs5 { get; set; }
        public string Currdrvxs1type { get; set; }
        public string Currdrvxs1code { get; set; }
        public string Currdrvxs2type { get; set; }
        public string Currdrvxs2code { get; set; }
        public string Currdrvxs3type { get; set; }
        public string Currdrvxs3code { get; set; }
        public string Currdrvxs4type { get; set; }
        public string Currdrvxs4code { get; set; }
        public string Currdrvxs5type { get; set; }
        public string Currdrvxs5code { get; set; }
        public string Altname { get; set; }
        public string Altcode { get; set; }
        public string Altstatus { get; set; }
        public Nullable<decimal> Altprem { get; set; }
        public Nullable<int> Alttotxs { get; set; }
        public Nullable<int> Altpolxs1 { get; set; }
        public Nullable<int> Altpolxs2 { get; set; }
        public Nullable<int> Altpolxs3 { get; set; }
        public Nullable<int> Altpolxs4 { get; set; }
        public string Altpolxs1type { get; set; }
        public string Altpolxs1code { get; set; }
        public string Altpolxs2type { get; set; }
        public string Altpolxs2code { get; set; }
        public string Altpolxs3type { get; set; }
        public string Altpolxs3code { get; set; }
        public string Altpolxs4type { get; set; }
        public string Altpolxs4code { get; set; }
        public Nullable<int> Altdrvxs1 { get; set; }
        public Nullable<int> Altdrvxs2 { get; set; }
        public Nullable<int> Altdrvxs3 { get; set; }
        public Nullable<int> Altdrvxs4 { get; set; }
        public Nullable<int> Altdrvxs5 { get; set; }
        public string Altdrvxs1type { get; set; }
        public string Altdrvxs1code { get; set; }
        public string Altdrvxs2type { get; set; }
        public string Altdrvxs2code { get; set; }
        public string Altdrvxs3type { get; set; }
        public string Altdrvxs3code { get; set; }
        public string Altdrvxs4type { get; set; }
        public string Altdrvxs4code { get; set; }
        public string Altdrvxs5type { get; set; }
        public string Altdrvxs5code { get; set; }
        public string Ratesused { get; set; }
        public Nullable<System.DateTime> Quotedate { get; set; }
        public string Quotetime { get; set; }
        public string Endofrecord { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
