//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_IR
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> Capac { get; set; }
        public Nullable<int> Trnov { get; set; }
        public Nullable<int> Wages { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Prem { get; set; }
        public string Cover { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string Addr3 { get; set; }
        public string Addr4 { get; set; }
        public string Op1 { get; set; }
        public Nullable<decimal> Rate1 { get; set; }
        public Nullable<decimal> Prem1 { get; set; }
        public string Op2 { get; set; }
        public Nullable<decimal> Rate2 { get; set; }
        public Nullable<decimal> Prem2 { get; set; }
        public string Op3 { get; set; }
        public Nullable<decimal> Rate3 { get; set; }
        public Nullable<decimal> Prem3 { get; set; }
        public string Op4 { get; set; }
        public Nullable<decimal> Rate4 { get; set; }
        public Nullable<decimal> Prem4 { get; set; }
        public string Op5 { get; set; }
        public Nullable<decimal> Rate5 { get; set; }
        public Nullable<decimal> Prem5 { get; set; }
        public string Op6 { get; set; }
        public Nullable<decimal> Rate6 { get; set; }
        public Nullable<decimal> Prem6 { get; set; }
        public string Op7 { get; set; }
        public Nullable<decimal> Rate7 { get; set; }
        public Nullable<decimal> Prem7 { get; set; }
        public string Op8 { get; set; }
        public Nullable<decimal> Rate8 { get; set; }
        public Nullable<decimal> Prem8 { get; set; }
        public string Op9 { get; set; }
        public Nullable<decimal> Rate9 { get; set; }
        public Nullable<decimal> Prem9 { get; set; }
        public string Op10 { get; set; }
        public Nullable<decimal> Rate10 { get; set; }
        public Nullable<decimal> Prem10 { get; set; }
        public string Op11 { get; set; }
        public Nullable<decimal> Rate11 { get; set; }
        public Nullable<decimal> Prem11 { get; set; }
        public string Op12 { get; set; }
        public Nullable<decimal> Rate12 { get; set; }
        public Nullable<decimal> Prem12 { get; set; }
        public string Op13 { get; set; }
        public Nullable<decimal> Rate13 { get; set; }
        public Nullable<decimal> Prem13 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
