//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_BGP
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<decimal> Premiumincipt { get; set; }
        public Nullable<decimal> Totalipt { get; set; }
        public Nullable<decimal> Iptrate { get; set; }
        public string Manoverused { get; set; }
        public Nullable<decimal> Manoveramount { get; set; }
        public Nullable<decimal> Manoverpercent { get; set; }
        public string Refoverused { get; set; }
        public Nullable<decimal> Refoveramount { get; set; }
        public Nullable<decimal> Refoverpercent { get; set; }
        public string Instused { get; set; }
        public Nullable<int> Instnumber { get; set; }
        public Nullable<decimal> Instfirst { get; set; }
        public Nullable<decimal> Insteach { get; set; }
        public Nullable<decimal> Instadmin { get; set; }
        public string Addonused { get; set; }
        public string Addondesc { get; set; }
        public Nullable<decimal> Addonpremium { get; set; }
        public Nullable<decimal> Addonipt { get; set; }
        public string Addonused1 { get; set; }
        public string Addondesc1 { get; set; }
        public Nullable<decimal> Addonpremium1 { get; set; }
        public Nullable<decimal> Addonipt1 { get; set; }
        public string F_23 { get; set; }
        public string Addonused2 { get; set; }
        public string Addondesc2 { get; set; }
        public Nullable<decimal> Addonpremium2 { get; set; }
        public Nullable<decimal> Addonipt2 { get; set; }
        public string F_28 { get; set; }
        public string Addonused3 { get; set; }
        public string Addondesc3 { get; set; }
        public Nullable<decimal> Addonpremium3 { get; set; }
        public Nullable<decimal> Addonipt3 { get; set; }
        public string F_33 { get; set; }
        public string Addonused4 { get; set; }
        public string Addondesc4 { get; set; }
        public Nullable<decimal> Addonpremium4 { get; set; }
        public Nullable<decimal> Addonipt4 { get; set; }
        public string F_38 { get; set; }
        public string Addonused5 { get; set; }
        public string Addondesc5 { get; set; }
        public Nullable<decimal> Addonpremium5 { get; set; }
        public Nullable<decimal> Addonipt5 { get; set; }
        public string F_43 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
