//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_H4
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<System.DateTime> C_From { get; set; }
        public Nullable<int> Areffects { get; set; }
        public Nullable<int> Areffectsitem { get; set; }
        public Nullable<int> Creditcards { get; set; }
        public Nullable<int> Arvaluables { get; set; }
        public Nullable<int> Arvaluablesitem { get; set; }
        public Nullable<int> C_Money { get; set; }
        public Nullable<int> Arphoto { get; set; }
        public Nullable<int> Arphotoitem { get; set; }
        public Nullable<int> Arsport { get; set; }
        public Nullable<int> Arsportitem { get; set; }
        public Nullable<int> Freezertotal { get; set; }
        public Nullable<int> Arbicycles { get; set; }
        public Nullable<int> Arbicyclesitem { get; set; }
        public Nullable<int> Allriskstotal { get; set; }
        public string Cyclemake1 { get; set; }
        public string Cyclemake2 { get; set; }
        public string Cyclemake3 { get; set; }
        public string Cyclemake4 { get; set; }
        public string Cyclemake5 { get; set; }
        public string Cyclemake6 { get; set; }
        public string Cycledesc1 { get; set; }
        public string Cycledesc2 { get; set; }
        public string Cycledesc3 { get; set; }
        public string Cycledesc4 { get; set; }
        public string Cycledesc5 { get; set; }
        public string Cycledesc6 { get; set; }
        public Nullable<int> Cycleval1 { get; set; }
        public Nullable<int> Cycleval2 { get; set; }
        public Nullable<int> Cycleval3 { get; set; }
        public Nullable<int> Cycleval4 { get; set; }
        public Nullable<int> Cycleval5 { get; set; }
        public Nullable<int> Cycleval6 { get; set; }
        public string Legexp { get; set; }
        public string Aranybicycles { get; set; }
        public Nullable<int> Freezerage { get; set; }
        public Nullable<int> C_Sequence { get; set; }
        public Nullable<decimal> Legalpremium { get; set; }
        public Nullable<int> Legalexpenses { get; set; }
        public Nullable<decimal> Cyclepremium { get; set; }
        public Nullable<decimal> Unspecpremium { get; set; }
        public Nullable<decimal> Cycle1premium { get; set; }
        public Nullable<decimal> Cycle2premium { get; set; }
        public Nullable<decimal> Cycle3premium { get; set; }
        public Nullable<decimal> Cycle4premium { get; set; }
        public Nullable<decimal> Cycle5premium { get; set; }
        public Nullable<decimal> Cycle6premium { get; set; }
        public string Cycle1territory { get; set; }
        public string Cycle2territory { get; set; }
        public string Cycle3territory { get; set; }
        public string Cycle4territory { get; set; }
        public string Cycle5territory { get; set; }
        public string Cycle6territory { get; set; }
        public string Unspeceffectsterritory { get; set; }
        public string Valuablesunspecterritory { get; set; }
        public string Photounspecterritory { get; set; }
        public string Sportsunspecterritory { get; set; }
        public string Moneyterritory { get; set; }
        public string Creditcardsterritory { get; set; }
        public string Areffectsterr { get; set; }
        public string Arvaluablesterr { get; set; }
        public string Arphototerr { get; set; }
        public string Arsportsterr { get; set; }
        public string Armoneyterr { get; set; }
        public string Creditcardsterr { get; set; }
        public Nullable<int> Riskcompxs { get; set; }
        public Nullable<int> Riskvolxs { get; set; }
        public Nullable<int> Risktotalxs { get; set; }
        public string Creationsource { get; set; }
        public string Updatedbyuser { get; set; }
        public string End_of_record { get; set; }
        public Nullable<int> Reqareffects { get; set; }
        public Nullable<int> Reqareffectsitem { get; set; }
        public Nullable<int> Reqcreditcards { get; set; }
        public Nullable<int> Reqarvaluables { get; set; }
        public Nullable<int> Reqarvaluablesitem { get; set; }
        public Nullable<int> Reqmoney { get; set; }
        public Nullable<int> Reqarphoto { get; set; }
        public Nullable<int> Reqarphotoitem { get; set; }
        public Nullable<int> Reqarsport { get; set; }
        public Nullable<int> Reqarsportitem { get; set; }
        public Nullable<int> Reqfreezertotal { get; set; }
        public Nullable<int> Reqcycleval1 { get; set; }
        public Nullable<int> Reqcycleval2 { get; set; }
        public Nullable<int> Reqcycleval3 { get; set; }
        public Nullable<int> Reqcycleval4 { get; set; }
        public Nullable<int> Reqcycleval5 { get; set; }
        public Nullable<int> Reqcycleval6 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
