//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_CA
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Model { get; set; }
        public Nullable<int> Make { get; set; }
        public string C_Use { get; set; }
        public Nullable<int> Vansi { get; set; }
        public Nullable<decimal> Vanprem { get; set; }
        public Nullable<int> Contsi { get; set; }
        public Nullable<decimal> Contprem { get; set; }
        public string Van { get; set; }
        public string Cont { get; set; }
        public string Othtow { get; set; }
        public string Continent { get; set; }
        public string Towext { get; set; }
        public string Lossuse { get; set; }
        public string Rem { get; set; }
        public Nullable<int> F_15 { get; set; }
        public string Val1 { get; set; }
        public string Val2 { get; set; }
        public string Val3 { get; set; }
        public string Val4 { get; set; }
        public string Val5 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
