//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_AX
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string F_1 { get; set; }
        public Nullable<System.DateTime> Acc_date1 { get; set; }
        public Nullable<int> Acc_type1_QR18_VTId { get; set; }
        public string Acc_ncb1 { get; set; }
        public Nullable<int> Acc_fault1_QR31_VTId { get; set; }
        public string Acc_injury1 { get; set; }
        public Nullable<int> Acc_amt1 { get; set; }
        public Nullable<int> Acc_tp_cost1 { get; set; }
        public Nullable<System.DateTime> Conv_date1 { get; set; }
        public Nullable<int> Conv_code1_QR15_VTId { get; set; }
        public Nullable<int> Conv_code_nn1 { get; set; }
        public Nullable<int> Conv_disqual1 { get; set; }
        public Nullable<int> Conv_points1 { get; set; }
        public Nullable<int> Conv_fine1 { get; set; }
        public Nullable<int> Conv_acc_no1 { get; set; }
        public string F_16 { get; set; }
        public string F_17 { get; set; }
        public string F_18 { get; set; }
        public Nullable<System.DateTime> Acc_date2 { get; set; }
        public Nullable<int> Acc_type2_QR18_VTId { get; set; }
        public string Acc_ncb2 { get; set; }
        public Nullable<int> Acc_fault2_QR31_VTId { get; set; }
        public string Acc_injury2 { get; set; }
        public Nullable<int> Acc_amt2 { get; set; }
        public Nullable<int> Acc_tp_cost2 { get; set; }
        public Nullable<System.DateTime> Conv_date2 { get; set; }
        public Nullable<int> Conv_code2_QR15_VTId { get; set; }
        public Nullable<int> Conv_code_nn2 { get; set; }
        public Nullable<int> Conv_disqual2 { get; set; }
        public Nullable<int> Conv_points2 { get; set; }
        public Nullable<int> Conv_fine2 { get; set; }
        public Nullable<int> Conv_acc_no2 { get; set; }
        public string F_33 { get; set; }
        public string F_34 { get; set; }
        public string F_35 { get; set; }
        public Nullable<System.DateTime> Acc_date3 { get; set; }
        public Nullable<int> Acc_type3_QR18_VTId { get; set; }
        public string Acc_ncb3 { get; set; }
        public Nullable<int> Acc_fault3_QR31_VTId { get; set; }
        public string Acc_injury3 { get; set; }
        public Nullable<int> Acc_amt3 { get; set; }
        public Nullable<int> Acc_tp_cost3 { get; set; }
        public Nullable<System.DateTime> Conv_date3 { get; set; }
        public Nullable<int> Conv_code3_QR15_VTId { get; set; }
        public Nullable<int> Conv_code_nn3 { get; set; }
        public Nullable<int> Conv_disqual3 { get; set; }
        public Nullable<int> Conv_points3 { get; set; }
        public Nullable<int> Conv_fine3 { get; set; }
        public Nullable<int> Conv_acc_no3 { get; set; }
        public string F_50 { get; set; }
        public string F_51 { get; set; }
        public string F_52 { get; set; }
        public Nullable<System.DateTime> Acc_date4 { get; set; }
        public Nullable<int> Acc_type4_QR18_VTId { get; set; }
        public string Acc_ncb4 { get; set; }
        public Nullable<int> Acc_fault4_QR31_VTId { get; set; }
        public string Acc_injury4 { get; set; }
        public Nullable<int> Acc_amt4 { get; set; }
        public Nullable<int> Acc_tp_cost4 { get; set; }
        public Nullable<System.DateTime> Conv_date4 { get; set; }
        public Nullable<int> Conv_code4_QR15_VTId { get; set; }
        public Nullable<int> Conv_code_nn4 { get; set; }
        public Nullable<int> Conv_disqual4 { get; set; }
        public Nullable<int> Conv_points4 { get; set; }
        public Nullable<int> Conv_fine4 { get; set; }
        public Nullable<int> Conv_acc_no4 { get; set; }
        public string F_67 { get; set; }
        public string F_68 { get; set; }
        public string F_69 { get; set; }
        public Nullable<System.DateTime> Acc_date5 { get; set; }
        public Nullable<int> Acc_type5_QR18_VTId { get; set; }
        public string Acc_ncb5 { get; set; }
        public Nullable<int> Acc_fault5_QR31_VTId { get; set; }
        public string Acc_injury5 { get; set; }
        public Nullable<int> Acc_amt5 { get; set; }
        public Nullable<int> Acc_tp_cost5 { get; set; }
        public Nullable<System.DateTime> Conv_date5 { get; set; }
        public Nullable<int> Conv_code5_QR15_VTId { get; set; }
        public Nullable<int> Conv_code_nn5 { get; set; }
        public Nullable<int> Conv_disqual5 { get; set; }
        public Nullable<int> Conv_points5 { get; set; }
        public Nullable<int> Conv_fine5 { get; set; }
        public Nullable<int> Conv_acc_no5 { get; set; }
        public string F_84 { get; set; }
        public string F_85 { get; set; }
        public string F_86 { get; set; }
        public string Acc_driver1 { get; set; }
        public string Acc_driver2 { get; set; }
        public string Acc_driver3 { get; set; }
        public string Acc_driver4 { get; set; }
        public string Acc_driver5 { get; set; }
        public string Conv_driver1 { get; set; }
        public string Conv_driver2 { get; set; }
        public string Conv_driver3 { get; set; }
        public string Conv_driver4 { get; set; }
        public string Conv_driver5 { get; set; }
        public Nullable<int> Acc_per_recov1 { get; set; }
        public Nullable<int> Acc_per_recov2 { get; set; }
        public Nullable<int> Acc_per_recov3 { get; set; }
        public Nullable<int> Acc_per_recov4 { get; set; }
        public Nullable<int> Acc_per_recov5 { get; set; }
        public Nullable<int> Conv_samp_type1_QR34_VTId { get; set; }
        public Nullable<int> Conv_samp_type2_QR34_VTId { get; set; }
        public Nullable<int> Conv_samp_type3_QR34_VTId { get; set; }
        public Nullable<int> Conv_samp_type4_QR34_VTId { get; set; }
        public Nullable<int> Conv_samp_type5_QR34_VTId { get; set; }
        public Nullable<int> Acc_ncb_prior1 { get; set; }
        public Nullable<int> Acc_ncb_prior2 { get; set; }
        public Nullable<int> Acc_ncb_prior3 { get; set; }
        public Nullable<int> Acc_ncb_prior4 { get; set; }
        public Nullable<int> Acc_ncb_prior5 { get; set; }
        public Nullable<System.DateTime> Conv_off_date1 { get; set; }
        public Nullable<System.DateTime> Conv_off_date2 { get; set; }
        public Nullable<System.DateTime> Conv_off_date3 { get; set; }
        public Nullable<System.DateTime> Conv_off_date4 { get; set; }
        public Nullable<System.DateTime> Conv_off_date5 { get; set; }
        public Nullable<int> Conv_ban_period1_QR02_VTId { get; set; }
        public Nullable<int> Conv_ban_period2_QR02_VTId { get; set; }
        public Nullable<int> Conv_ban_period3_QR02_VTId { get; set; }
        public Nullable<int> Conv_ban_period4_QR02_VTId { get; set; }
        public Nullable<int> Conv_samp_level1 { get; set; }
        public Nullable<int> Conv_samp_level2 { get; set; }
        public Nullable<int> Conv_samp_level3 { get; set; }
        public Nullable<int> Conv_samp_level4 { get; set; }
        public Nullable<int> Conv_samp_level5 { get; set; }
        public Nullable<int> Conv_ban_period5_QR02_VTId { get; set; }
        public Nullable<int> Acc_policy1_QR20_VTId { get; set; }
        public Nullable<int> Acc_policy2_QR20_VTId { get; set; }
        public Nullable<int> Acc_policy3_QR20_VTId { get; set; }
        public Nullable<int> Acc_policy4_QR20_VTId { get; set; }
        public Nullable<int> Acc_policy5_QR20_VTId { get; set; }
        public Nullable<int> Acc_desc1_QR28_VTId { get; set; }
        public Nullable<int> Acc_desc2_QR28_VTId { get; set; }
        public Nullable<int> Acc_desc3_QR28_VTId { get; set; }
        public Nullable<int> Acc_desc4_QR28_VTId { get; set; }
        public Nullable<int> Acc_desc5_QR28_VTId { get; set; }
        public Nullable<int> Conv_ban_per1_QR02_VTId { get; set; }
        public Nullable<int> Conv_ban_per2_QR02_VTId { get; set; }
        public Nullable<int> Conv_ban_per3_QR02_VTId { get; set; }
        public Nullable<int> Conv_ban_per4_QR02_VTId { get; set; }
        public Nullable<int> Conv_samp_lev1 { get; set; }
        public Nullable<int> Conv_samp_lev2 { get; set; }
        public Nullable<int> Conv_samp_lev3 { get; set; }
        public Nullable<int> Conv_samp_lev4 { get; set; }
        public Nullable<int> Conv_samp_lev5 { get; set; }
        public Nullable<int> Conv_ban_per5_QR02_VTId { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
