//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_brclaims
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public string Policy_ref { get; set; }
        public Nullable<int> Claim_number { get; set; }
        public string Client_ref { get; set; }
        public string Policy_type { get; set; }
        public string Pol_key { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> Date_of_loss { get; set; }
        public string Cause_of_loss { get; set; }
        public string Claim_status { get; set; }
        public Nullable<decimal> Claim_amount { get; set; }
        public Nullable<decimal> Claim_reserve { get; set; }
        public Nullable<decimal> Amount_settled { get; set; }
        public Nullable<System.DateTime> Date_settled { get; set; }
        public string C_Description { get; set; }
        public string Executive { get; set; }
        public Nullable<int> Insurer_INSC_VTId { get; set; }
        public string Owner { get; set; }
        public string Claim_type { get; set; }
        public Nullable<System.DateTime> Status_date { get; set; }
        public string C_Key { get; set; }
        public Nullable<int> Claim_amount2 { get; set; }
        public string Description2 { get; set; }
        public Nullable<decimal> Old_claim_amount { get; set; }
        public Nullable<decimal> Old_claim_reserve { get; set; }
        public Nullable<decimal> Old_amount_settled { get; set; }
        public string Reserved { get; set; }
        public Nullable<int> Ext_claimstatus_B033_VTId { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
