//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_MB3
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> Bike_code { get; set; }
        public Nullable<int> Make_vt_QR88_VTId { get; set; }
        public string Model { get; set; }
        public Nullable<int> Eng_size { get; set; }
        public Nullable<System.DateTime> Date_made { get; set; }
        public Nullable<int> Reg_QR48_VTId { get; set; }
        public string Reg_mark { get; set; }
        public string C_Type { get; set; }
        public Nullable<int> C_Value { get; set; }
        public Nullable<int> Purchase_price { get; set; }
        public Nullable<int> Mileage_private { get; set; }
        public Nullable<int> Mileage_business { get; set; }
        public Nullable<int> Owner_QR08_VTId { get; set; }
        public Nullable<int> Keeper_QR08_VTId { get; set; }
        public Nullable<int> Modified_QR19_VTId { get; set; }
        public Nullable<int> Grey_import_QR19_VTId { get; set; }
        public Nullable<int> Parking_QR33_VTId { get; set; }
        public string Garage_structure { get; set; }
        public Nullable<int> Transmission_QR42_VTId { get; set; }
        public string Turbo_supercharger { get; set; }
        public Nullable<int> Countryofmanufacture_QR43_VTId { get; set; }
        public Nullable<int> Sidecar_QR19_VTId { get; set; }
        public Nullable<int> Pillions_QR19_VTId { get; set; }
        public Nullable<int> Trailer_QR19_VTId { get; set; }
        public Nullable<int> Fuel_type_QR32_VTId { get; set; }
        public Nullable<int> Audio { get; set; }
        public Nullable<int> Telephone { get; set; }
        public string Unlisted_make { get; set; }
        public string Unlisted_model { get; set; }
        public string Unlisted_type { get; set; }
        public Nullable<int> Approx_group { get; set; }
        public Nullable<int> Modification1_QR81_VTId { get; set; }
        public Nullable<int> Modification2_QR81_VTId { get; set; }
        public Nullable<int> Modification3_QR81_VTId { get; set; }
        public Nullable<int> Modification4_QR81_VTId { get; set; }
        public Nullable<int> Modification5_QR81_VTId { get; set; }
        public string Unlistedmodification { get; set; }
        public Nullable<int> Immobiliser_type_QR82_VTId { get; set; }
        public Nullable<int> Alarm_type_QR86_VTId { get; set; }
        public Nullable<int> Other_devices_type_QR87_VTId { get; set; }
        public Nullable<int> Datatag_QR19_VTId { get; set; }
        public Nullable<int> Immob_fitted_by_QR37_VTId { get; set; }
        public Nullable<int> Alarm_fitted_by_QR37_VTId { get; set; }
        public Nullable<int> Other_fitted_by_QR37_VTId { get; set; }
        public Nullable<int> Datatag_fitted_by_QR37_VTId { get; set; }
        public Nullable<int> Abs_QR19_VTId { get; set; }
        public Nullable<System.DateTime> Purchase_date { get; set; }
        public Nullable<int> Panniers { get; set; }
        public Nullable<int> Year_made { get; set; }
        public Nullable<int> Comp_xs { get; set; }
        public Nullable<int> Vol_xs { get; set; }
        public string Cover { get; set; }
        public Nullable<int> Agreed_value_QR19_VTId { get; set; }
        public Nullable<int> C_Group { get; set; }
        public Nullable<int> Mod1_QR81_VTId { get; set; }
        public Nullable<int> Mod2_QR81_VTId { get; set; }
        public Nullable<int> Mod3_QR81_VTId { get; set; }
        public Nullable<int> Mod4_QR81_VTId { get; set; }
        public Nullable<int> Mod5_QR81_VTId { get; set; }
        public string Unlistmod { get; set; }
        public Nullable<int> Immob_type_QR82_VTId { get; set; }
        public Nullable<int> Otherdevtype_QR87_VTId { get; set; }
        public Nullable<int> Immobfitby_QR37_VTId { get; set; }
        public Nullable<int> Alarmfitby_QR37_VTId { get; set; }
        public Nullable<int> Otherfitby_QR37_VTId { get; set; }
        public Nullable<int> Datatagfitby_QR37_VTId { get; set; }
        public Nullable<System.DateTime> Purchdate { get; set; }
        public Nullable<int> Appsecurity { get; set; }
        public Nullable<int> Garage_disc_bike_QR19_VTId { get; set; }
        public string Vxstypebike { get; set; }
        public string Cxstypebike { get; set; }
        public Nullable<int> Polxsbike { get; set; }
        public Nullable<int> Origvolxsbike { get; set; }
        public Nullable<int> Origcomxsbike { get; set; }
        public string End_of_record { get; set; }
        public string Make_vt_vo { get; set; }
        public string Authorisation_vo { get; set; }
        public Nullable<int> Vehicleoverride_QR19_VTId { get; set; }
        public Nullable<int> Bikeprfn { get; set; }
        public Nullable<System.DateTime> Tempbikeexpirydate { get; set; }
        public string Tempbikeexpirytime { get; set; }
        public Nullable<int> Tempbike_QR19_VTId { get; set; }
        public string Turbo_superchg { get; set; }
        public Nullable<int> Dtag_fitted_by_QR37_VTId { get; set; }
        public Nullable<int> Other_dev_type_QR87_VTId { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
