//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DF_H5
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<System.DateTime> C_From { get; set; }
        public Nullable<int> C_Number { get; set; }
        public string C_Section { get; set; }
        public Nullable<int> C_Type_H00A_VTId { get; set; }
        public string Deleted { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public Nullable<int> C_Value { get; set; }
        public string Desc1 { get; set; }
        public Nullable<int> C_Sequence { get; set; }
        public string Desc2 { get; set; }
        public string Createdbyclaimswriter { get; set; }
        public string Creationsource { get; set; }
        public string Updatedbyuser { get; set; }
        public string End_of_record { get; set; }
        public string Claimsettled { get; set; }
        public string Ediclaimsettled { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
