//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_CV
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Reg { get; set; }
        public Nullable<int> Carrytons { get; set; }
        public Nullable<int> Carrycwts { get; set; }
        public Nullable<int> Grwtons { get; set; }
        public Nullable<int> Grwcwts { get; set; }
        public Nullable<System.DateTime> Regdate { get; set; }
        public Nullable<int> C_Value { get; set; }
        public string Body { get; set; }
        public string Lhd { get; set; }
        public string Eec { get; set; }
        public string C_Foreign { get; set; }
        public string Cover { get; set; }
        public string Drivers { get; set; }
        public string C_Use { get; set; }
        public Nullable<System.DateTime> Ncbdate { get; set; }
        public Nullable<int> Excess { get; set; }
        public string Ratarea { get; set; }
        public string Windscrn { get; set; }
        public string Ncbprej { get; set; }
        public Nullable<int> Radius { get; set; }
        public string Accconv { get; set; }
        public Nullable<int> Compexc1 { get; set; }
        public string Compexc2 { get; set; }
        public Nullable<decimal> Ncbdisc { get; set; }
        public Nullable<int> Ncbyears { get; set; }
        public string Opcert { get; set; }
        public Nullable<System.DateTime> Polsusp { get; set; }
        public string Comm { get; set; }
        public string Occup { get; set; }
        public Nullable<int> Occcd { get; set; }
        public string Physdef { get; set; }
        public string Lictype { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public Nullable<System.DateTime> Datobtain { get; set; }
        public Nullable<System.DateTime> Datukent { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
