//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_CF_History
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> Proposer_QR24_VTId { get; set; }
        public Nullable<int> Years_ncb { get; set; }
        public string Ins_scheme { get; set; }
        public Nullable<int> Car_code { get; set; }
        public Nullable<int> Make_QR26_VTId { get; set; }
        public Nullable<int> Compxs { get; set; }
        public Nullable<int> Premload { get; set; }
        public string Compxstype { get; set; }
        public string Windscrn { get; set; }
        public string Model { get; set; }
        public Nullable<int> Windscreen_QR49_VTId { get; set; }
        public Nullable<int> Motor_orgs_QR12_VTId { get; set; }
        public Nullable<int> Parking_QR33_VTId { get; set; }
        public string Lhd { get; set; }
        public Nullable<int> Engine_size { get; set; }
        public Nullable<int> C_Value { get; set; }
        public string Modified { get; set; }
        public string Cover { get; set; }
        public string Protected_bonus { get; set; }
        public string All_female { get; set; }
        public Nullable<int> Vol_xs { get; set; }
        public string C_Type { get; set; }
        public Nullable<int> Drivers_QR01_VTId { get; set; }
        public string Second_car { get; set; }
        public string Holding_broker { get; set; }
        public Nullable<int> Fuel_QR32_VTId { get; set; }
        public Nullable<int> No_named { get; set; }
        public Nullable<int> Aged_over { get; set; }
        public Nullable<int> Scheme { get; set; }
        public Nullable<System.DateTime> Cover_date { get; set; }
        public Nullable<System.DateTime> Date_made { get; set; }
        public string Rated_postcode { get; set; }
        public string Reg { get; set; }
        public string Fc_inscode { get; set; }
        public string Curr_inscode { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<int> Seats { get; set; }
        public Nullable<int> Gears_QR42_VTId { get; set; }
        public Nullable<int> Body_QR47_VTId { get; set; }
        public Nullable<int> Orig_alarm_type_QR11_VTId { get; set; }
        public Nullable<int> Alarm_fitted_QR37_VTId { get; set; }
        public Nullable<int> Doors { get; set; }
        public Nullable<int> Audio { get; set; }
        public Nullable<int> Telephone { get; set; }
        public Nullable<int> Orig_immobiliser_type_QR16_VTId { get; set; }
        public Nullable<int> Immobiliser_fitted_QR37_VTId { get; set; }
        public Nullable<int> Orig_tracker_type_QR03_VTId { get; set; }
        public Nullable<int> Tracker_fitted_QR37_VTId { get; set; }
        public string Abs { get; set; }
        public Nullable<int> Abs_fitted_QR37_VTId { get; set; }
        public Nullable<int> Owner_QR08_VTId { get; set; }
        public Nullable<int> Keeper_QR08_VTId { get; set; }
        public string Ever_insured { get; set; }
        public string Class_of_use { get; set; }
        public string Exclude_comm { get; set; }
        public Nullable<int> Current_insurer_QR54_VTId { get; set; }
        public Nullable<int> Immob_type_QR92_VTId { get; set; }
        public Nullable<int> Immob_fitted_QR37_VTId { get; set; }
        public string Step_back { get; set; }
        public string Previouspayment { get; set; }
        public Nullable<System.DateTime> Purchasedate { get; set; }
        public string Endofrecord { get; set; }
        public Nullable<int> Lapsed_for { get; set; }
        public Nullable<int> Lapsed_type_QR29_VTId { get; set; }
        public Nullable<int> Immobiliser_type_QR92_VTId { get; set; }
        public Nullable<int> Alarm_type_QR94_VTId { get; set; }
        public Nullable<int> Tracker_type_QR96_VTId { get; set; }
        public Nullable<int> Modlist1_QR99_VTId { get; set; }
        public Nullable<int> Modlist2_QR99_VTId { get; set; }
        public Nullable<int> Modlist3_QR99_VTId { get; set; }
        public Nullable<int> Modlist4_QR99_VTId { get; set; }
        public Nullable<int> Modlist5_QR99_VTId { get; set; }
        public string Unlistedmod { get; set; }
        public string Quotationlogicused { get; set; }
        public string Webauthenticationcode { get; set; }
        public string Webcovertime { get; set; }
        public string Webebuy { get; set; }
        public string Covertime { get; set; }
        public string Aqaffiliate { get; set; }
        public Nullable<int> Aqquoteorigin_QREA_VTId { get; set; }
        public Nullable<int> Ratesmonth { get; set; }
        public Nullable<int> Ratesversion { get; set; }
        public Nullable<int> Ratesyear { get; set; }
        public string Cnsntforsearches { get; set; }
        public Nullable<int> Businesssourcecode_QREA_VTId { get; set; }
        public Nullable<int> Businesssrccode_QREA_VTId { get; set; }
        public string Eircode { get; set; }
        public string Proposereircode { get; set; }
        public Nullable<System.DateTime> Quotedate { get; set; }
        public string Quotetime { get; set; }
        public Nullable<System.DateTime> History_ { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
