//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_yymemoshist
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public Nullable<int> Ins_co_INSC_VTId { get; set; }
        public Nullable<int> Office_IOFF_VTId { get; set; }
        public Nullable<int> Doc_type_DOCT_VTId { get; set; }
        public string Polref { get; set; }
        public string Source { get; set; }
        public string Spare1 { get; set; }
        public Nullable<int> Key_suffix { get; set; }
        public string C_Key { get; set; }
        public string Print_status { get; set; }
        public Nullable<System.DateTime> Effective_date { get; set; }
        public string Remarks1 { get; set; }
        public string Remarks2 { get; set; }
        public string Remarks3 { get; set; }
        public string Remarks4 { get; set; }
        public string Remarks5 { get; set; }
        public string Remarks6 { get; set; }
        public string Remarks7 { get; set; }
        public string Remarks8 { get; set; }
        public string Insurer_ref { get; set; }
        public string Our_ref { get; set; }
        public string Policyholder { get; set; }
        public Nullable<int> No_of_copies { get; set; }
        public string Spare2 { get; set; }
        public string C_Exec { get; set; }
        public string Operator { get; set; }
        public string Poltype { get; set; }
        public Nullable<System.DateTime> Date_to_be_sent { get; set; }
        public Nullable<System.DateTime> Short_date_tbs { get; set; }
        public string Nickname { get; set; }
        public Nullable<int> Claim_ref { get; set; }
        public string Claim_type { get; set; }
        public string Claim_loss { get; set; }
        public string Claim_stat { get; set; }
        public string Insurer_ref_old { get; set; }
        public string Our_ref_old { get; set; }
        public string Remarks9 { get; set; }
        public string Remarks10 { get; set; }
        public string Remarks11 { get; set; }
        public string Remarks12 { get; set; }
        public string Remarks13 { get; set; }
        public string Remarks14 { get; set; }
        public string Remarks15 { get; set; }
        public string Remarks16 { get; set; }
        public string Remarks17 { get; set; }
        public string Remarks18 { get; set; }
        public string Remarks19 { get; set; }
        public string Remarks20 { get; set; }
        public string Remarks21 { get; set; }
        public string Remarks22 { get; set; }
        public string Remarks23 { get; set; }
        public string Remarks24 { get; set; }
        public string Remarks25 { get; set; }
        public string Remarks26 { get; set; }
        public string Remarks27 { get; set; }
        public string Remarks28 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
