//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_BGA
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string F_1 { get; set; }
        public string Salemeth { get; set; }
        public Nullable<int> Saletype_CC01_VTId { get; set; }
        public string Trantype { get; set; }
        public string Demand_1 { get; set; }
        public string Demand_2 { get; set; }
        public string Demand_3 { get; set; }
        public string Demand_4 { get; set; }
        public string Demand_5 { get; set; }
        public string Demand_6 { get; set; }
        public string Demand_7 { get; set; }
        public string Demand_8 { get; set; }
        public string Demand_9 { get; set; }
        public string Demand_10 { get; set; }
        public string Demand_11 { get; set; }
        public Nullable<System.DateTime> Quote_date { get; set; }
        public string Quote_time { get; set; }
        public Nullable<System.DateTime> Amend_date { get; set; }
        public string Amend_op { get; set; }
        public string Copy_to_pol { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
