//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_Dapolicy
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public string Polref { get; set; }
        public string Prospect_ref { get; set; }
        public string Short_polref { get; set; }
        public string Ptype { get; set; }
        public Nullable<int> Status { get; set; }
        public string Frame { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public string Create_time { get; set; }
        public string Create_op { get; set; }
        public Nullable<System.DateTime> Quote_date { get; set; }
        public string Quote_op { get; set; }
        public Nullable<int> Insurer_INSC_VTId { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public string C_Exec { get; set; }
        public Nullable<int> Branch { get; set; }
        public Nullable<System.DateTime> Trans_date { get; set; }
        public string Trans_op { get; set; }
        public string Trans_time { get; set; }
        public string Brooms_ref { get; set; }
        public Nullable<int> Mailshot_YENO_VTId { get; set; }
        public string Polno { get; set; }
        public Nullable<int> Leunits { get; set; }
        public Nullable<int> Excess1 { get; set; }
        public Nullable<int> Excess2 { get; set; }
        public Nullable<int> Excess3 { get; set; }
        public Nullable<int> Excess4 { get; set; }
        public string Excess_name1 { get; set; }
        public string Excess_name2 { get; set; }
        public string Excess_name3 { get; set; }
        public string Excess_name4 { get; set; }
        public Nullable<int> Voluntary_excess { get; set; }
        public Nullable<int> Lic_held { get; set; }
        public Nullable<int> Lic_period_QR29_VTId { get; set; }
        public Nullable<int> Residency { get; set; }
        public Nullable<int> Residency_period_QR29_VTId { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public string Agent { get; set; }
        public Nullable<int> Abi_car_code { get; set; }
        public string C_Key { get; set; }
        public string Cc_saaudit_ref { get; set; }
        public string Cc_saaudit_polref { get; set; }
        public Nullable<int> Cc_saaudit_suffix { get; set; }
        public Nullable<decimal> Cc_pay_amount { get; set; }
        public Nullable<System.DateTime> Cc_auth_date { get; set; }
        public Nullable<System.DateTime> Cc_auth_expiry { get; set; }
        public Nullable<int> Cc_creditplan_YENO_VTId { get; set; }
        public string Cc_pay_type { get; set; }
        public Nullable<System.DateTime> Cover_date { get; set; }
        public string Operator { get; set; }
        public Nullable<int> Accept_policy_YENO_VTId { get; set; }
        public string Accept_op { get; set; }
        public Nullable<System.DateTime> Accept_date { get; set; }
        public string Reg { get; set; }
        public string Remote_server { get; set; }
        public Nullable<int> Current_scheme { get; set; }
        public Nullable<int> Override_prem_YENO_VTId { get; set; }
        public string Broms_ref_pt { get; set; }
        public Nullable<int> Term { get; set; }
        public string Cc_auth_op { get; set; }
        public Nullable<int> Proc_flag { get; set; }
        public Nullable<decimal> Ipt_rate { get; set; }
        public Nullable<decimal> Comm_rate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Edi_policy_YENO_VTId { get; set; }
        public Nullable<int> Internet_flag_YENO_VTId { get; set; }
        public string Comtype { get; set; }
        public Nullable<int> Broker_ref { get; set; }
        public Nullable<int> Purge_YENO_VTId { get; set; }
        public string Payment_method { get; set; }
        public string Frequency { get; set; }
        public string Frequency_basic { get; set; }
        public string Tran_type { get; set; }
        public Nullable<int> Instalments { get; set; }
        public Nullable<decimal> Interest_amount { get; set; }
        public Nullable<decimal> Charge_amt { get; set; }
        public Nullable<int> Le_YENO_VTId { get; set; }
        public Nullable<int> Orig_volxs { get; set; }
        public Nullable<decimal> Le_value { get; set; }
        public Nullable<System.DateTime> Epa_import_date { get; set; }
        public Nullable<System.DateTime> Epa_conv_date { get; set; }
        public string Ownercode { get; set; }
        public string Spare1 { get; set; }
        public string Spare2 { get; set; }
        public string Brooms_policy { get; set; }
        public string Cust_class { get; set; }
        public string Cust_class_mfs { get; set; }
        public string Sale_doc1 { get; set; }
        public string Sale_doc2 { get; set; }
        public string Sale_doc3 { get; set; }
        public string Sale_doc4 { get; set; }
        public string Sale_doc5 { get; set; }
        public string Sale_doc6 { get; set; }
        public Nullable<System.DateTime> Sale_doc1_date { get; set; }
        public Nullable<System.DateTime> Sale_doc2_date { get; set; }
        public Nullable<System.DateTime> Sale_doc3_date { get; set; }
        public Nullable<System.DateTime> Sale_doc4_date { get; set; }
        public Nullable<System.DateTime> Sale_doc5_date { get; set; }
        public Nullable<System.DateTime> Sale_doc6_date { get; set; }
        public Nullable<int> Mta_policy_YENO_VTId { get; set; }
        public string Mta_old_scheme { get; set; }
        public string Mta_new_scheme { get; set; }
        public Nullable<decimal> Mta_ret_premium { get; set; }
        public Nullable<int> Edi_scheme_YENO_VTId { get; set; }
        public string Partial_case { get; set; }
        public Nullable<int> Partial_branch { get; set; }
        public string Partial_ref { get; set; }
        public string Finance_ref { get; set; }
        public Nullable<int> Finance_branch { get; set; }
        public Nullable<System.DateTime> Rdat { get; set; }
        public Nullable<int> Requote_YENO_VTId { get; set; }
        public string Pay_method { get; set; }
        public Nullable<int> Cover_requested { get; set; }
        public string Purpose_notes1 { get; set; }
        public string Purpose_notes2 { get; set; }
        public string Trader_ref { get; set; }
        public Nullable<System.DateTime> Conversion_date { get; set; }
        public string Trader_status { get; set; }
        public Nullable<decimal> Pay_value { get; set; }
        public string Import_type { get; set; }
        public Nullable<decimal> Trader_comm_amt { get; set; }
        public Nullable<decimal> Trader_comm_pc { get; set; }
        public string Agg_short_code { get; set; }
        public string Agg_quote_ref { get; set; }
        public string Brandch { get; set; }
        public Nullable<int> Zero_commission_YENO_VTId { get; set; }
        public string Trader_qstatus { get; set; }
        public Nullable<int> Brand_QCBR_VTId { get; set; }
        public Nullable<int> Stream_QCST_VTId { get; set; }
        public Nullable<int> Postquote_supported_YENO_VTId { get; set; }
        public Nullable<int> Edi_supported_YENO_VTId { get; set; }
        public Nullable<int> No_quote_engine_YENO_VTId { get; set; }
        public Nullable<int> Agg_conv_units { get; set; }
        public Nullable<int> Stp_YENO_VTId { get; set; }
        public Nullable<decimal> Trader_insfee { get; set; }
        public Nullable<int> Trader_insfee_ipt_YENO_VTId { get; set; }
        public Nullable<int> Trader_insfee_comm_YENO_VTId { get; set; }
        public Nullable<int> Owm_YENO_VTId { get; set; }
        public Nullable<int> Unit_type_B014_VTId { get; set; }
        public Nullable<int> Units_per_convert { get; set; }
        public Nullable<int> Trader_proc_YENO_VTId { get; set; }
        public Nullable<decimal> Trader_fee { get; set; }
        public Nullable<int> Trader_fee_zero_YENO_VTId { get; set; }
        public Nullable<decimal> Cpc_charge_amt { get; set; }
        public Nullable<int> Trader_market_BRTM_VTId { get; set; }
        public Nullable<int> Mp_offer_finance_YENO_VTId { get; set; }
        public string Mp_finance_plan { get; set; }
        public Nullable<int> Mp_finance_planid { get; set; }
        public Nullable<int> Mp_finance_plan_lock_YENO_VTId { get; set; }
        public string Mp_l2_type { get; set; }
        public Nullable<int> Leadtype_unit_B014_VTId { get; set; }
        public Nullable<int> Source_CR01_VTId { get; set; }
        public Nullable<int> Querydisc { get; set; }
        public string Live_ref { get; set; }
        public string Live_policy { get; set; }
        public Nullable<int> Quoteandbuy_YENO_VTId { get; set; }
        public Nullable<decimal> Last_year_prem { get; set; }
        public Nullable<int> Consec_years { get; set; }
        public Nullable<decimal> Annualised { get; set; }
        public Nullable<System.DateTime> Base_consec_years { get; set; }
        public Nullable<System.DateTime> Base_consec_yea { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
