//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_EQQA
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Quoteorigin { get; set; }
        public string Affiliate { get; set; }
        public Nullable<decimal> Origcheapprem { get; set; }
        public string Origcheapscheme { get; set; }
        public Nullable<System.DateTime> Activequotedate { get; set; }
        public string Activequotetime { get; set; }
        public Nullable<decimal> Origpremexclipt { get; set; }
        public Nullable<decimal> Origpreminclipt { get; set; }
        public Nullable<decimal> Diffpreminclipt { get; set; }
        public Nullable<decimal> Diffpctinclipt { get; set; }
        public Nullable<decimal> NewInsurerPrem { get; set; }
        public Nullable<decimal> Brokerdiffprem { get; set; }
        public Nullable<decimal> Newcustprem { get; set; }
        public Nullable<decimal> Diffcustprem { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
