//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_MV
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Heading { get; set; }
        public Nullable<int> F_2 { get; set; }
        public Nullable<System.DateTime> Ondt1 { get; set; }
        public string Make1 { get; set; }
        public string Model1 { get; set; }
        public string Reg1 { get; set; }
        public string Cover1 { get; set; }
        public string Use1 { get; set; }
        public Nullable<System.DateTime> Offdt1 { get; set; }
        public Nullable<int> No1 { get; set; }
        public Nullable<System.DateTime> Ondt2 { get; set; }
        public string Make2 { get; set; }
        public string Model2 { get; set; }
        public string Reg2 { get; set; }
        public string Cover2 { get; set; }
        public string Use2 { get; set; }
        public Nullable<System.DateTime> Offdt2 { get; set; }
        public Nullable<int> No2 { get; set; }
        public Nullable<System.DateTime> Ondt3 { get; set; }
        public string Make3 { get; set; }
        public string Model3 { get; set; }
        public string Reg3 { get; set; }
        public string Cover3 { get; set; }
        public string Use3 { get; set; }
        public Nullable<System.DateTime> Offdt3 { get; set; }
        public Nullable<int> No3 { get; set; }
        public Nullable<System.DateTime> Ondt4 { get; set; }
        public string Make4 { get; set; }
        public string Model4 { get; set; }
        public string Reg4 { get; set; }
        public string Cover4 { get; set; }
        public string Use4 { get; set; }
        public Nullable<System.DateTime> Offdt4 { get; set; }
        public Nullable<int> No4 { get; set; }
        public Nullable<System.DateTime> Ondt5 { get; set; }
        public string Make5 { get; set; }
        public string Model5 { get; set; }
        public string Reg5 { get; set; }
        public string Cover5 { get; set; }
        public string Use5 { get; set; }
        public Nullable<System.DateTime> Offdt5 { get; set; }
        public Nullable<int> No5 { get; set; }
        public Nullable<System.DateTime> Ondt6 { get; set; }
        public string Make6 { get; set; }
        public string Model6 { get; set; }
        public string Reg6 { get; set; }
        public string Cover6 { get; set; }
        public string Use6 { get; set; }
        public Nullable<System.DateTime> Offdt6 { get; set; }
        public Nullable<int> No6 { get; set; }
        public Nullable<System.DateTime> Ondt7 { get; set; }
        public string Make7 { get; set; }
        public string Model7 { get; set; }
        public string Reg7 { get; set; }
        public string Cover7 { get; set; }
        public string Use7 { get; set; }
        public Nullable<System.DateTime> Offdt7 { get; set; }
        public Nullable<int> No7 { get; set; }
        public Nullable<System.DateTime> Ondt8 { get; set; }
        public string Make8 { get; set; }
        public string Model8 { get; set; }
        public string Reg8 { get; set; }
        public string Cover8 { get; set; }
        public string Use8 { get; set; }
        public Nullable<System.DateTime> Offdt8 { get; set; }
        public Nullable<int> No8 { get; set; }
        public Nullable<System.DateTime> Ondt9 { get; set; }
        public string Make9 { get; set; }
        public string Model9 { get; set; }
        public string Reg9 { get; set; }
        public string Cover9 { get; set; }
        public string Use9 { get; set; }
        public Nullable<System.DateTime> Offdt9 { get; set; }
        public Nullable<int> No9 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
