//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_PC
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Accconv { get; set; }
        public string Ncbprej { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Licence_QR05_VTId { get; set; }
        public Nullable<int> Old_premload { get; set; }
        public Nullable<System.DateTime> Ncbdate { get; set; }
        public Nullable<int> Old_compxs { get; set; }
        public string Old_compxstype { get; set; }
        public string C_Name { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<System.DateTime> Dateobt { get; set; }
        public Nullable<System.DateTime> Ukdate { get; set; }
        public string Postcode { get; set; }
        public string Disabled { get; set; }
        public Nullable<int> Status_QR07_VTId { get; set; }
        public Nullable<int> Origin_QR43_VTId { get; set; }
        public Nullable<int> Licence_country_QR43_VTId { get; set; }
        public Nullable<int> Number_of_tests { get; set; }
        public Nullable<int> Marital_status_QR17_VTId { get; set; }
        public string Commuting { get; set; }
        public string Other_vehicles { get; set; }
        public Nullable<int> Pt_emp_status_QR07_VTId { get; set; }
        public Nullable<int> Private_mileage { get; set; }
        public Nullable<int> Business_mileage { get; set; }
        public Nullable<int> Ft_bus_cat_QR38_VTId { get; set; }
        public Nullable<int> Pt_occup_QR35_VTId { get; set; }
        public Nullable<int> Pt_bus_cat_QR38_VTId { get; set; }
        public Nullable<int> Ft_occup_QR35_VTId { get; set; }
        public Nullable<int> Ncb_type_QR44_VTId { get; set; }
        public Nullable<int> Ncb_country_QR43_VTId { get; set; }
        public string Smoker { get; set; }
        public string Homeowner { get; set; }
        public string Drinker { get; set; }
        public Nullable<int> Driver_status_QR22_VTId { get; set; }
        public string Personal_business { get; set; }
        public string Anothers_business { get; set; }
        public string Carriage_of_goods { get; set; }
        public string Soliciting { get; set; }
        public string Hire { get; set; }
        public string Emp_business { get; set; }
        public string Own_vehicle { get; set; }
        public Nullable<int> Own_vehicle_type_QR44_VTId { get; set; }
        public string Company_vehicle { get; set; }
        public string Company_private { get; set; }
        public string Own_insurer { get; set; }
        public Nullable<int> Own_ncb { get; set; }
        public Nullable<int> Company_ncb { get; set; }
        public Nullable<System.DateTime> Company_date_end { get; set; }
        public Nullable<System.DateTime> Own_veh_ncb_date { get; set; }
        public Nullable<System.DateTime> Company_veh_ncb_date { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> Business_miles { get; set; }
        public string Personal_bsness { get; set; }
        public string Anothers_bsness { get; set; }
        public string Carriageofgoods { get; set; }
        public Nullable<int> Ownvehicletype_QR44_VTId { get; set; }
        public Nullable<System.DateTime> Companydateend { get; set; }
        public Nullable<System.DateTime> Ownvehncbdate { get; set; }
        public Nullable<System.DateTime> Compvehncbdate { get; set; }
        public Nullable<int> History_whose_QR13_VTId { get; set; }
        public Nullable<int> History_pol_QR44_VTId { get; set; }
        public Nullable<int> History_yrsdriving { get; set; }
        public string History_flag { get; set; }
        public string History_insurer { get; set; }
        public Nullable<System.DateTime> History_date_ended { get; set; }
        public string Private_hire { get; set; }
        public string Endofrecord { get; set; }
        public Nullable<System.DateTime> Passplus { get; set; }
        public Nullable<int> Locallicensingauthority_QRCA_VTId { get; set; }
        public string Baseofficepostcode { get; set; }
        public Nullable<int> Llauthority_QRCA_VTId { get; set; }
        public string Bopostcode { get; set; }
        public string Bldocind { get; set; }
        public Nullable<int> Drivertitle_QRTL_VTId { get; set; }
        public string Forenames { get; set; }
        public string Surname { get; set; }
        public string Nonmotorconvictions { get; set; }
        public string Insurancecancelled { get; set; }
        public string Refusedinsurance { get; set; }
        public string Termsapplied { get; set; }
        public string Increasedpremium { get; set; }
        public string Nonmotorconvs { get; set; }
        public string Inscancelled { get; set; }
        public string Penalties { get; set; }
        public string Drivinglicencenumber { get; set; }
        public string Drivingqualificationtrigger { get; set; }
        public Nullable<int> Drivingqualificationvt_QRI1_VTId { get; set; }
        public Nullable<System.DateTime> Drivingqualificationdateobtained { get; set; }
        public string Drivlicno { get; set; }
        public string Drivqualtrigger { get; set; }
        public Nullable<int> Drivqualvt_QRI1_VTId { get; set; }
        public Nullable<System.DateTime> Drivqualdateobt { get; set; }
        public string Mylicencedriverconsent { get; set; }
        public string Mylicdvrcnsnt { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
