//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_AC
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<System.DateTime> Accdate { get; set; }
        public Nullable<int> ODCost { get; set; }
        public Nullable<int> TPCost { get; set; }
        public string PerInjury { get; set; }
        public string Fault { get; set; }
        public Nullable<System.DateTime> Condate1 { get; set; }
        public Nullable<int> Noofcon { get; set; }
        public string Concode1 { get; set; }
        public string Concode2 { get; set; }
        public string Concode3 { get; set; }
        public string Concode4 { get; set; }
        public string Concode5 { get; set; }
        public string Concode6 { get; set; }
        public string Accrem1 { get; set; }
        public string Accrem2 { get; set; }
        public string Accrem3 { get; set; }
        public string Accrem4 { get; set; }
        public string Clmrem1 { get; set; }
        public string Clmrem2 { get; set; }
        public string Clmrem3 { get; set; }
        public string Clmrem4 { get; set; }
        public string Clmrem5 { get; set; }
        public string Clmrem6 { get; set; }
        public Nullable<System.DateTime> Condate2 { get; set; }
        public string Driver { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
