//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_PD_History
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string C_Desc { get; set; }
        public Nullable<int> Lim1 { get; set; }
        public Nullable<int> Lim2 { get; set; }
        public Nullable<int> Turn1 { get; set; }
        public Nullable<int> Turn2 { get; set; }
        public Nullable<int> Turn3 { get; set; }
        public string UKOly { get; set; }
        public string Wld { get; set; }
        public string ExcNAmer { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Rem1 { get; set; }
        public string Rem2 { get; set; }
        public string Rem3 { get; set; }
        public Nullable<System.DateTime> History_ { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
