//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_yyletters
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public Nullable<int> Doc_type_DOCT_VTId { get; set; }
        public string Polref { get; set; }
        public string Source { get; set; }
        public string Spare1 { get; set; }
        public Nullable<int> Key_suffix { get; set; }
        public string C_Key { get; set; }
        public string Print_status { get; set; }
        public string C_Exec { get; set; }
        public string Operator { get; set; }
        public Nullable<int> No_of_copies { get; set; }
        public string Credit { get; set; }
        public string Tran_type { get; set; }
        public string Pay_method { get; set; }
        public string Act_agent { get; set; }
        public Nullable<System.DateTime> Date_raised { get; set; }
        public Nullable<System.DateTime> Date_settled { get; set; }
        public Nullable<decimal> Original_debt { get; set; }
        public Nullable<decimal> Paid_on_acc { get; set; }
        public Nullable<int> Trans_status { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public Nullable<decimal> Chg_only { get; set; }
        public Nullable<System.DateTime> Ledger_date { get; set; }
        public string Reference { get; set; }
        public Nullable<int> No_of_equal_inst { get; set; }
        public Nullable<decimal> Inst_amount { get; set; }
        public Nullable<System.DateTime> Inst_date { get; set; }
        public string Inst_freq { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Last_inst_amount { get; set; }
        public Nullable<decimal> Bal_owing { get; set; }
        public Nullable<decimal> Comm_rate { get; set; }
        public Nullable<decimal> Comm_amount { get; set; }
        public string Comm_flag { get; set; }
        public Nullable<int> No_of_inst { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> Req_total { get; set; }
        public Nullable<decimal> Req_inst { get; set; }
        public Nullable<decimal> Req_deposit { get; set; }
        public string Poltype { get; set; }
        public Nullable<System.DateTime> Date_to_be_sent { get; set; }
        public Nullable<System.DateTime> Print_date { get; set; }
        public Nullable<System.DateTime> Short_date_tbs { get; set; }
        public Nullable<int> Ccode { get; set; }
        public Nullable<decimal> Le_prem { get; set; }
        public Nullable<decimal> Od_only { get; set; }
        public Nullable<decimal> Bo_only { get; set; }
        public Nullable<int> No_of_units { get; set; }
        public string Remarks_2 { get; set; }
        public Nullable<decimal> Od_nocharge { get; set; }
        public Nullable<decimal> Bal_nocharge { get; set; }
        public Nullable<decimal> Poac_nocharge { get; set; }
        public Nullable<decimal> Ipt_amount { get; set; }
        public Nullable<decimal> Ipt_rate { get; set; }
        public Nullable<decimal> Gross_exempt { get; set; }
        public Nullable<decimal> Gross_tax { get; set; }
        public Nullable<decimal> Ipt_rate_le { get; set; }
        public Nullable<decimal> Gross_exempt_only { get; set; }
        public Nullable<decimal> Gross_tax_only { get; set; }
        public Nullable<decimal> Ipt_amount_only { get; set; }
        public Nullable<int> Claim_ref { get; set; }
        public string Claim_type { get; set; }
        public string Claim_loss { get; set; }
        public string Claim_stat { get; set; }
        public string L_pay_method { get; set; }
        public string Free_text { get; set; }
        public string Remarks_3 { get; set; }
        public string Remarks_4 { get; set; }
        public Nullable<decimal> Le_o_prem { get; set; }
        public Nullable<int> Trans_suffix { get; set; }
        public string Calc_done { get; set; }
        public string Oneoff { get; set; }
        public string Print_yesno { get; set; }
        public string C_Module { get; set; }
        public string Alien_desc { get; set; }
        public Nullable<int> Cq_idnum { get; set; }
        public Nullable<decimal> Card_charge { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
