//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_BFB
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Bank_name { get; set; }
        public string Bank_addr1 { get; set; }
        public string Bank_addr2 { get; set; }
        public string Bank_addr3 { get; set; }
        public string Bank_addr4 { get; set; }
        public string Bank_pcode { get; set; }
        public string F_7 { get; set; }
        public string Ac_number { get; set; }
        public string Ac_type { get; set; }
        public string Sort_code { get; set; }
        public string Roll_number { get; set; }
        public string C_Dummy { get; set; }
        public string Ac_addr1 { get; set; }
        public string Ac_addr2 { get; set; }
        public string Ac_addr3 { get; set; }
        public string Ac_addr4 { get; set; }
        public string Ac_pcode { get; set; }
        public string Ac_title { get; set; }
        public string Ac_surname { get; set; }
        public string Ac_forenames { get; set; }
        public Nullable<int> Pref_pay_day { get; set; }
        public string Ac_holder { get; set; }
        public string Agreement { get; set; }
        public string Ac_busname { get; set; }
        public string Ac_covercode { get; set; }
        public string Ac_changeofprovider { get; set; }
        public Nullable<System.DateTime> Ac_holder_dob { get; set; }
        public string Card_holder { get; set; }
        public string Card_number { get; set; }
        public string Card_exp_date { get; set; }
        public string Card_issue_no { get; set; }
        public string Card_valid_from { get; set; }
        public string Ac_hm_tel { get; set; }
        public string Ac_ctype { get; set; }
        public string Ac_client { get; set; }
        public string Comptype { get; set; }
        public string An_encrypted { get; set; }
        public string Sc_encrypted { get; set; }
        public string Pan_encrypted { get; set; }
        public string Ac_email { get; set; }
        public string Ac_mobile { get; set; }
        public string Bic { get; set; }
        public string Bic_bank { get; set; }
        public string Bic_country { get; set; }
        public string Bic_location { get; set; }
        public string Bic_branch { get; set; }
        public string Iban { get; set; }
        public string Iban_country { get; set; }
        public string Iban_checkdigits { get; set; }
        public string Iban_bban { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
