//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_SCOM_History
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Oscheme { get; set; }
        public string Nscheme { get; set; }
        public Nullable<int> Ocxs { get; set; }
        public Nullable<int> Ncxs { get; set; }
        public Nullable<int> Oaxs { get; set; }
        public Nullable<int> Naxs { get; set; }
        public Nullable<int> Ovxs { get; set; }
        public Nullable<int> Nvxs { get; set; }
        public Nullable<int> Osxs { get; set; }
        public Nullable<int> Nsxs { get; set; }
        public Nullable<int> Osilimit { get; set; }
        public Nullable<int> Nsilimit { get; set; }
        public string Omobiles { get; set; }
        public string Nmobiles { get; set; }
        public string Olaptops { get; set; }
        public string Nlaptops { get; set; }
        public string Oaccom { get; set; }
        public string Naccom { get; set; }
        public string Olocks { get; set; }
        public string Nlocks { get; set; }
        public string Ovaluables { get; set; }
        public string Nvaluables { get; set; }
        public string Ofood { get; set; }
        public string Nfood { get; set; }
        public string Ocash { get; set; }
        public string Ncash { get; set; }
        public string Ocredit { get; set; }
        public string Ncredit { get; set; }
        public string Oholiday { get; set; }
        public string Nholiday { get; set; }
        public string Ocoutb { get; set; }
        public string Ncoutb { get; set; }
        public string Ocopen { get; set; }
        public string Ncopen { get; set; }
        public string Ofuel { get; set; }
        public string Nfuel { get; set; }
        public string Ostudent { get; set; }
        public string Nstudent { get; set; }
        public string Opedal { get; set; }
        public string Npedal { get; set; }
        public string Otrace { get; set; }
        public string Ntrace { get; set; }
        public string Opipes { get; set; }
        public string Npipes { get; set; }
        public string Opets { get; set; }
        public string Npets { get; set; }
        public string Otheft { get; set; }
        public string Ntheft { get; set; }
        public Nullable<int> Osinglimit { get; set; }
        public Nullable<int> Nsinglimit { get; set; }
        public Nullable<System.DateTime> History_ { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
