//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_MB_History
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> Bike_code { get; set; }
        public Nullable<int> Make_vt_QR88_VTId { get; set; }
        public string Model { get; set; }
        public Nullable<int> Eng_size { get; set; }
        public Nullable<System.DateTime> Date_made { get; set; }
        public Nullable<int> Reg_QR48_VTId { get; set; }
        public string Reg_mark { get; set; }
        public string C_Type { get; set; }
        public Nullable<int> C_Value { get; set; }
        public Nullable<int> Purchase_price { get; set; }
        public Nullable<int> Mileage_private { get; set; }
        public Nullable<int> Mileage_business { get; set; }
        public Nullable<int> Owner_QR08_VTId { get; set; }
        public Nullable<int> Keeper_QR08_VTId { get; set; }
        public Nullable<int> Modified_QR19_VTId { get; set; }
        public Nullable<int> Grey_import_QR19_VTId { get; set; }
        public Nullable<int> Parking_QR33_VTId { get; set; }
        public string Garage_structure { get; set; }
        public Nullable<int> Transmission_QR42_VTId { get; set; }
        public string Turbo_supercharger { get; set; }
        public Nullable<int> Countryofmanufacture_QR43_VTId { get; set; }
        public Nullable<int> Sidecar_QR19_VTId { get; set; }
        public Nullable<int> Pillions_QR19_VTId { get; set; }
        public Nullable<int> Trailer_QR19_VTId { get; set; }
        public Nullable<int> Fuel_type_QR32_VTId { get; set; }
        public Nullable<int> Audio { get; set; }
        public Nullable<int> Telephone { get; set; }
        public string Unlisted_make { get; set; }
        public string Unlisted_model { get; set; }
        public string Unlisted_type { get; set; }
        public Nullable<int> Approx_group { get; set; }
        public Nullable<int> Modification1_QR81_VTId { get; set; }
        public Nullable<int> Modification2_QR81_VTId { get; set; }
        public Nullable<int> Modification3_QR81_VTId { get; set; }
        public Nullable<int> Modification4_QR81_VTId { get; set; }
        public Nullable<int> Modification5_QR81_VTId { get; set; }
        public string Unlistedmodification { get; set; }
        public string Cover { get; set; }
        public string Rated_post_code { get; set; }
        public Nullable<System.DateTime> Cover_date { get; set; }
        public string Ins_scheme { get; set; }
        public string Class_of_use { get; set; }
        public Nullable<int> Ever_insured_QR19_VTId { get; set; }
        public string Curr_inscode { get; set; }
        public Nullable<int> Current_ins_QR54_VTId { get; set; }
        public Nullable<int> Riders_QR91_VTId { get; set; }
        public Nullable<int> Number_named { get; set; }
        public Nullable<int> Aged_over { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<int> Vol_xs { get; set; }
        public Nullable<int> Ever_refused_QR19_VTId { get; set; }
        public Nullable<int> Other_claims_QR19_VTId { get; set; }
        public Nullable<int> Non_motoring_convs_QR19_VTId { get; set; }
        public Nullable<int> Holding_broker_QR19_VTId { get; set; }
        public Nullable<int> Scheme { get; set; }
        public Nullable<int> Protected_bonus_QR19_VTId { get; set; }
        public Nullable<int> Immobiliser_type_QR82_VTId { get; set; }
        public Nullable<int> Alarm_type_QR86_VTId { get; set; }
        public Nullable<int> Other_devices_type_QR87_VTId { get; set; }
        public Nullable<int> Datatag_QR19_VTId { get; set; }
        public Nullable<int> Immob_fitted_by_QR37_VTId { get; set; }
        public Nullable<int> Alarm_fitted_by_QR37_VTId { get; set; }
        public Nullable<int> Other_fitted_by_QR37_VTId { get; set; }
        public Nullable<int> Datatag_fitted_by_QR37_VTId { get; set; }
        public Nullable<int> Abs_QR19_VTId { get; set; }
        public Nullable<int> Comp_xs { get; set; }
        public string Comp_xs_type { get; set; }
        public Nullable<int> Prem_load { get; set; }
        public Nullable<System.DateTime> Purchase_date { get; set; }
        public Nullable<int> Panniers { get; set; }
        public Nullable<int> Abi_bike_code { get; set; }
        public Nullable<int> Year_made { get; set; }
        public Nullable<int> Doc_QR19_VTId { get; set; }
        public Nullable<int> C_Group { get; set; }
        public Nullable<int> Agreed_value_QR19_VTId { get; set; }
        public string Unlistmake { get; set; }
        public string Unlistmodel { get; set; }
        public string Unlisttype { get; set; }
        public Nullable<int> Mod1_QR81_VTId { get; set; }
        public Nullable<int> Mod3_QR81_VTId { get; set; }
        public Nullable<int> Mod4_QR81_VTId { get; set; }
        public Nullable<int> Mod5_QR81_VTId { get; set; }
        public string Unlistmod { get; set; }
        public string Ratedpcode { get; set; }
        public Nullable<int> Nonmotorconv_QR19_VTId { get; set; }
        public Nullable<int> Protbonus_QR19_VTId { get; set; }
        public Nullable<int> Immobtype_QR82_VTId { get; set; }
        public Nullable<int> Otherdevtype_QR87_VTId { get; set; }
        public Nullable<int> Immobfitby_QR37_VTId { get; set; }
        public Nullable<int> Alarmfitby_QR37_VTId { get; set; }
        public Nullable<int> Otherfitby_QR37_VTId { get; set; }
        public Nullable<int> Datatagfitby_QR37_VTId { get; set; }
        public Nullable<int> Appsecurity { get; set; }
        public Nullable<int> Garage_disc_bike_QR19_VTId { get; set; }
        public string Vxstypebike { get; set; }
        public string Cxstypebike { get; set; }
        public Nullable<int> Polxsbike { get; set; }
        public Nullable<int> Origvolxsbike { get; set; }
        public Nullable<int> Origcomxsbike { get; set; }
        public string End_of_record { get; set; }
        public Nullable<int> Ins_cancelled_special_terms_QR19_VTId { get; set; }
        public string Make_vt_vo { get; set; }
        public string Authorisation_vo { get; set; }
        public Nullable<int> Vehicleoverride_QR19_VTId { get; set; }
        public Nullable<int> Bikeprfn { get; set; }
        public string Turbo_superchg { get; set; }
        public Nullable<int> Dtag_fitted_by_QR37_VTId { get; set; }
        public Nullable<int> Other_dev_type_QR87_VTId { get; set; }
        public Nullable<int> Criminal_convs_QR19_VTId { get; set; }
        public Nullable<System.DateTime> Tempbikeexpirydate { get; set; }
        public string Tempbikeexpirytime { get; set; }
        public Nullable<int> Tempbike_QR19_VTId { get; set; }
        public string Webauthenticationcode { get; set; }
        public string Webcovertime { get; set; }
        public Nullable<int> Webebuy_QR19_VTId { get; set; }
        public string Covertime { get; set; }
        public Nullable<int> Countryofmanuf_QR43_VTId { get; set; }
        public Nullable<int> Lapsedfor { get; set; }
        public Nullable<int> Lapsedtype_QR29_VTId { get; set; }
        public Nullable<System.DateTime> Quotedate { get; set; }
        public string Quotetime { get; set; }
        public Nullable<int> Ratesmonth { get; set; }
        public Nullable<int> Ratesversion { get; set; }
        public Nullable<int> Ratesyear { get; set; }
        public Nullable<int> Consentforsearches_QR19_VTId { get; set; }
        public Nullable<int> Cnsntforsearches_QR19_VTId { get; set; }
        public Nullable<System.DateTime> History_ { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
