//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_L1
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Descrip { get; set; }
        public Nullable<int> No1 { get; set; }
        public Nullable<int> Sal1 { get; set; }
        public Nullable<int> No2 { get; set; }
        public Nullable<int> Sal2 { get; set; }
        public Nullable<int> No3 { get; set; }
        public Nullable<int> Sal3 { get; set; }
        public Nullable<int> Saltot { get; set; }
        public Nullable<int> Trnact { get; set; }
        public Nullable<int> Compclmact { get; set; }
        public Nullable<int> Compyract { get; set; }
        public Nullable<int> Trnest { get; set; }
        public Nullable<int> Compclmest { get; set; }
        public Nullable<int> Compyrest { get; set; }
        public Nullable<int> Credit { get; set; }
        public Nullable<int> Maxper { get; set; }
        public Nullable<int> Maxlim { get; set; }
        public string Comm { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
