//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_THAP
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string op { get; set; }
        public Nullable<decimal> anprem { get; set; }
        public string C_tran { get; set; }
        public Nullable<System.DateTime> effdt { get; set; }
        public Nullable<System.DateTime> todt { get; set; }
        public Nullable<int> days { get; set; }
        public Nullable<decimal> curr_prem { get; set; }
        public Nullable<decimal> adj_prem { get; set; }
        public Nullable<decimal> fee { get; set; }
        public Nullable<int> polno_YENO_VTId { get; set; }
        public Nullable<int> papers_YENO_VTId { get; set; }
        public string notes1 { get; set; }
        public string notes2 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
