//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_HTPR
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string HIns { get; set; }
        public Nullable<System.DateTime> RDat { get; set; }
        public string Contact { get; set; }
        public string Telephone { get; set; }
        public Nullable<decimal> STime1 { get; set; }
        public string STime2 { get; set; }
        public Nullable<decimal> ETime1 { get; set; }
        public string ETime2 { get; set; }
        public string PreHINS { get; set; }
        public string PreReference { get; set; }
        public string Notes1 { get; set; }
        public string Notes2 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
