//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BF_ADDN
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> Insurer1_INSC_VTId { get; set; }
        public string Product1 { get; set; }
        public Nullable<int> Units1 { get; set; }
        public Nullable<int> Create1_YENO_VTId { get; set; }
        public string Policyno1 { get; set; }
        public Nullable<decimal> Premium1 { get; set; }
        public Nullable<decimal> Net1 { get; set; }
        public Nullable<int> Insurer2_INSC_VTId { get; set; }
        public string Product2 { get; set; }
        public Nullable<int> Units2 { get; set; }
        public Nullable<int> Create2_YENO_VTId { get; set; }
        public string Policyno2 { get; set; }
        public Nullable<decimal> Premium2 { get; set; }
        public Nullable<decimal> Net2 { get; set; }
        public Nullable<int> Insurer3_INSC_VTId { get; set; }
        public string Product3 { get; set; }
        public Nullable<int> Units3 { get; set; }
        public Nullable<int> Create3_YENO_VTId { get; set; }
        public string Policyno3 { get; set; }
        public Nullable<decimal> Premium3 { get; set; }
        public Nullable<decimal> Net3 { get; set; }
        public Nullable<int> Insurer4_INSC_VTId { get; set; }
        public string Product4 { get; set; }
        public Nullable<int> Units4 { get; set; }
        public Nullable<int> Create4_YENO_VTId { get; set; }
        public string Policyno4 { get; set; }
        public Nullable<decimal> Premium4 { get; set; }
        public Nullable<decimal> Net4 { get; set; }
        public Nullable<int> Insurer5_INSC_VTId { get; set; }
        public string Product5 { get; set; }
        public Nullable<int> Units5 { get; set; }
        public Nullable<int> Create5_YENO_VTId { get; set; }
        public string Policyno5 { get; set; }
        public Nullable<decimal> Premium5 { get; set; }
        public Nullable<decimal> Net5 { get; set; }
        public Nullable<int> Insurer6_INSC_VTId { get; set; }
        public string Product6 { get; set; }
        public Nullable<int> Units6 { get; set; }
        public Nullable<int> Create6_YENO_VTId { get; set; }
        public string Policyno6 { get; set; }
        public Nullable<decimal> Premium6 { get; set; }
        public Nullable<decimal> Net6 { get; set; }
        public Nullable<int> Insurer7_INSC_VTId { get; set; }
        public string Product7 { get; set; }
        public Nullable<int> Units7 { get; set; }
        public Nullable<int> Create7_YENO_VTId { get; set; }
        public string Policyno7 { get; set; }
        public Nullable<decimal> Premium7 { get; set; }
        public Nullable<decimal> Net7 { get; set; }
        public Nullable<int> Insurer8_INSC_VTId { get; set; }
        public string Product8 { get; set; }
        public Nullable<int> Units8 { get; set; }
        public Nullable<int> Create8_YENO_VTId { get; set; }
        public string Policyno8 { get; set; }
        public Nullable<decimal> Premium8 { get; set; }
        public Nullable<decimal> Net8 { get; set; }
        public Nullable<int> Insurer9_INSC_VTId { get; set; }
        public string Product9 { get; set; }
        public Nullable<int> Units9 { get; set; }
        public Nullable<int> Create9_YENO_VTId { get; set; }
        public string Policyno9 { get; set; }
        public Nullable<decimal> Premium9 { get; set; }
        public Nullable<decimal> Net9 { get; set; }
        public Nullable<int> Insurer10_INSC_VTId { get; set; }
        public string Product10 { get; set; }
        public Nullable<int> Units10 { get; set; }
        public Nullable<int> Create10_YENO_VTId { get; set; }
        public string Policyno10 { get; set; }
        public Nullable<decimal> Premium10 { get; set; }
        public Nullable<decimal> Net10 { get; set; }
        public Nullable<int> Total_units { get; set; }
        public string F_72 { get; set; }
        public Nullable<decimal> Comm1 { get; set; }
        public Nullable<decimal> Comm2 { get; set; }
        public Nullable<decimal> Comm3 { get; set; }
        public Nullable<decimal> Comm4 { get; set; }
        public Nullable<decimal> Comm5 { get; set; }
        public Nullable<decimal> Comm6 { get; set; }
        public Nullable<decimal> Comm7 { get; set; }
        public Nullable<decimal> Comm8 { get; set; }
        public Nullable<decimal> Comm9 { get; set; }
        public Nullable<decimal> Comm10 { get; set; }
        public string F_83 { get; set; }
        public string F_84 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
