//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_12
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string C_Name { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Sex { get; set; }
        public string Lictype { get; set; }
        public Nullable<System.DateTime> Dateobt { get; set; }
        public string Occ { get; set; }
        public Nullable<int> Occode_JOBS_VTId { get; set; }
        public string Disabl { get; set; }
        public Nullable<System.DateTime> Dateinuk { get; set; }
        public string Married { get; set; }
        public string Status { get; set; }
        public string C_Relation { get; set; }
        public string Add_driver { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
