//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_H6
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<System.DateTime> C_From { get; set; }
        public Nullable<int> C_Number { get; set; }
        public Nullable<int> Category_H00B_VTId { get; set; }
        public string Proof { get; set; }
        public string Deleted { get; set; }
        public Nullable<int> Stated_value { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public string Transferred { get; set; }
        public string Valuationseen { get; set; }
        public string Territory { get; set; }
        public string Covertype { get; set; }
        public Nullable<decimal> Specifieditempremium { get; set; }
        public Nullable<int> Sequenceno { get; set; }
        public string End_of_record { get; set; }
        public Nullable<decimal> Specpremium { get; set; }
        public Nullable<decimal> Suminsilp { get; set; }
        public string Creationsource { get; set; }
        public string Updatedbyuser { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
