//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_PREQ_History
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> F_1_YENO_VTId { get; set; }
        public Nullable<System.DateTime> F_2 { get; set; }
        public string F_3 { get; set; }
        public string F_4 { get; set; }
        public Nullable<decimal> F_5 { get; set; }
        public string F_6 { get; set; }
        public Nullable<decimal> F_7 { get; set; }
        public string F_8 { get; set; }
        public string F_9 { get; set; }
        public string F_10 { get; set; }
        public Nullable<int> F_11_YENO_VTId { get; set; }
        public Nullable<System.DateTime> F_12 { get; set; }
        public Nullable<System.DateTime> F_13 { get; set; }
        public Nullable<System.DateTime> F_14 { get; set; }
        public Nullable<System.DateTime> F_15 { get; set; }
        public Nullable<System.DateTime> History_ { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
