//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_ERT
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string C_Result { get; set; }
        public string Quotesource { get; set; }
        public Nullable<int> Proposerareacoverused_QR30_VTId { get; set; }
        public Nullable<int> Businessareacoverused_QR30_VTId { get; set; }
        public Nullable<int> Parkingareat1coverused_QR30_VTId { get; set; }
        public Nullable<int> Parkingareat2coverused_QR30_VTId { get; set; }
        public Nullable<int> Parkingareat3coverused_QR30_VTId { get; set; }
        public Nullable<int> Parkingareat4coverused_QR30_VTId { get; set; }
        public Nullable<int> Parkingareat5coverused_QR30_VTId { get; set; }
        public string Insurererrormsg1 { get; set; }
        public string Insurererrormsg2 { get; set; }
        public string Ogierrorcode { get; set; }
        public string Ogierrormsg1 { get; set; }
        public string Ogierrormsg2 { get; set; }
        public string Insurerscheme { get; set; }
        public string Proposerareatermstr { get; set; }
        public string Proposerareagrpstr { get; set; }
        public string Businessareatermstr { get; set; }
        public string Businessareagrpstr { get; set; }
        public string Parkingareatermstrt1 { get; set; }
        public string Parkingareagrpstrt1 { get; set; }
        public string Parkingareatermstrt2 { get; set; }
        public string Parkingareagrpstrt2 { get; set; }
        public string Parkingareatermstrt3 { get; set; }
        public string Parkingareagrpstrt3 { get; set; }
        public string Parkingareatermstrt4 { get; set; }
        public string Parkingareagrpstrt4 { get; set; }
        public string Parkingareatermstrt5 { get; set; }
        public string Parkingareagrpstrt5 { get; set; }
        public string Enrichmentrequestid { get; set; }
        public string Quotereference { get; set; }
        public Nullable<System.DateTime> Enrichmentdate { get; set; }
        public string Enrichmenttime { get; set; }
        public string Ogixmllogid { get; set; }
        public Nullable<int> Enrichmenttimeinsecs { get; set; }
        public string Fprversion { get; set; }
        public string Service_QESV_VTId { get; set; }
        public string Enrichmentstring { get; set; }
        public string Endofrecord { get; set; }
        public string Bericprovider { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public string Ihpquotestatus { get; set; }
        public Nullable<decimal> Ihppremiuminclipt { get; set; }
        public Nullable<decimal> Ihppremiumexclipt { get; set; }
        public Nullable<decimal> Ihpiptvalue { get; set; }
        public Nullable<decimal> Ihpiptrate { get; set; }
        public Nullable<int> Ihptotalexcess { get; set; }
        public Nullable<int> Ihpexcess1 { get; set; }
        public Nullable<int> Ihpexcess2 { get; set; }
        public Nullable<int> Ihpexcess3 { get; set; }
        public Nullable<int> Ihpexcess4 { get; set; }
        public Nullable<int> Ihpvoluntaryexcess { get; set; }
        public string Ihpquotereference { get; set; }
        public string Ihpextendedquoteref { get; set; }
        public Nullable<int> Ihpquoteflags { get; set; }
        public Nullable<int> Ihpquoteflag1 { get; set; }
        public Nullable<int> Ihpquoteflag2 { get; set; }
        public Nullable<int> Ihpquoteflag3 { get; set; }
        public Nullable<int> Ihpquoteflag4 { get; set; }
        public Nullable<int> Ihpquoteflag5 { get; set; }
        public Nullable<int> Ihpquoteflag6 { get; set; }
        public Nullable<int> Ihpquoteflag7 { get; set; }
        public Nullable<int> Ihpquoteflag8 { get; set; }
        public Nullable<int> Ihpquoteflag9 { get; set; }
        public Nullable<int> Ihpquoteflag10 { get; set; }
        public Nullable<int> Ihpquoteflag11 { get; set; }
        public Nullable<int> Ihpquoteflag12 { get; set; }
        public Nullable<int> Ihpquoteflag13 { get; set; }
        public Nullable<int> Ihpquoteflag14 { get; set; }
        public string Ticreference { get; set; }
    }
}
