//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_yyclient
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string Refno { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Frame { get; set; }
        public string C_Name { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string Addr3 { get; set; }
        public string Addr4 { get; set; }
        public string Pcode { get; set; }
        public string Tel { get; set; }
        public string Title { get; set; }
        public string Forenames { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Sex { get; set; }
        public string Mar { get; set; }
        public Nullable<int> Child { get; set; }
        public string St_cl { get; set; }
        public string Odesc { get; set; }
        public Nullable<int> Ocode { get; set; }
        public Nullable<int> Credrate { get; set; }
        public Nullable<int> Proscode { get; set; }
        public string Inv_cl { get; set; }
        public Nullable<decimal> Sbal { get; set; }
        public string Notes { get; set; }
        public string Mshot { get; set; }
        public Nullable<int> C_Pages { get; set; }
        public Nullable<System.DateTime> Sdate { get; set; }
        public string Ctype { get; set; }
        public string Sfreq { get; set; }
        public string Contact { get; set; }
        public Nullable<int> Bpages { get; set; }
        public string C_Exec { get; set; }
        public string Agent { get; set; }
        public string Mshot1 { get; set; }
        public string Mshot2 { get; set; }
        public string Mshot3 { get; set; }
        public string Mshot4 { get; set; }
        public string Mshot5 { get; set; }
        public string Mshot6 { get; set; }
        public string Advisa { get; set; }
        public string Lmodule { get; set; }
        public string Bmodule { get; set; }
        public string Lexec { get; set; }
        public string Lagent { get; set; }
        public string Lagent1 { get; set; }
        public string Lagent2 { get; set; }
        public string Lagent3 { get; set; }
        public string Lagent4 { get; set; }
        public string Lagent5 { get; set; }
        public Nullable<System.DateTime> Rev_date { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Tel4 { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public Nullable<System.DateTime> Bg_issued { get; set; }
        public Nullable<System.DateTime> Tob_issued { get; set; }
        public Nullable<System.DateTime> B_last_stat { get; set; }
        public Nullable<System.DateTime> Estab { get; set; }
        public string Yr_end { get; set; }
        public Nullable<int> Employees { get; set; }
        public Nullable<int> Turnover { get; set; }
        public Nullable<int> Payroll { get; set; }
        public string Contact2 { get; set; }
        public string Contact3 { get; set; }
        public string Contact4 { get; set; }
        public string Job1 { get; set; }
        public string Job2 { get; set; }
        public string Job3 { get; set; }
        public string Job4 { get; set; }
        public string Ni_no { get; set; }
        public string Taxref { get; set; }
        public string Char1 { get; set; }
        public string Char2 { get; set; }
        public string Char3 { get; set; }
        public string Char4 { get; set; }
        public string Nickname { get; set; }
        public string Char5 { get; set; }
        public string Char6 { get; set; }
        public Nullable<int> Num1 { get; set; }
        public Nullable<decimal> Num2 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public string Code1_yn { get; set; }
        public string Code2_yn { get; set; }
        public string Code3_yn { get; set; }
        public string Code4_yn { get; set; }
        public Nullable<int> Comp_ref { get; set; }
        public string Partner_ref { get; set; }
        public string Ext_client_name { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public Nullable<System.DateTime> Date4 { get; set; }
        public Nullable<System.DateTime> Date5 { get; set; }
        public string Code5_yn { get; set; }
        public string Code6_yn { get; set; }
        public string Code7_yn { get; set; }
        public string Code8_yn { get; set; }
        public string Code9_yn { get; set; }
        public string Code10_yn { get; set; }
        public string Code11_yn { get; set; }
        public string Code12_yn { get; set; }
        public string Mailshot { get; set; }
        public string Telesales { get; set; }
        public string Email { get; set; }
        public string Tpda { get; set; }
        public string Tpdua { get; set; }
        public string Cust_class { get; set; }
        public string Cust_class_mfs { get; set; }
        public string Partial_save { get; set; }
        public string Apm_ref { get; set; }
        public Nullable<int> Apm_branch { get; set; }
        public string Client_stop { get; set; }
        public string Division { get; set; }
        public string Contactpref { get; set; }
        public Nullable<System.DateTime> Dt_factfind { get; set; }
        public string Stop_policy { get; set; }
        public string Nosms { get; set; }
        public string Docportal_url { get; set; }
        public string Docportal_pass { get; set; }
        public Nullable<int> Mp_fp_nextplan { get; set; }
        public string Bad_debt { get; set; }
        public Nullable<decimal> Bad_debt_amt { get; set; }
        public string Driver_lic { get; set; }
        public Nullable<int> Brand_QCBR_VTId { get; set; }
        public string C_Group { get; set; }
        public string Eircode { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
