//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_EC_History
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Webref { get; set; }
        public string Referrer { get; set; }
        public string Affiliate { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public string Notes1 { get; set; }
        public string Notes2 { get; set; }
        public string F_7 { get; set; }
        public string Brand { get; set; }
        public string Aggregator { get; set; }
        public string F_10 { get; set; }
        public string F_11 { get; set; }
        public string Deviceclass { get; set; }
        public Nullable<int> Ocpregistered_YENO_VTId { get; set; }
        public Nullable<System.DateTime> History_ { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
