//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_NPI
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public string C_Time { get; set; }
        public string Ratesversion { get; set; }
        public Nullable<decimal> Ncdimpliedpricewithipt { get; set; }
        public Nullable<decimal> Ncdprice { get; set; }
        public Nullable<int> Yearsncd { get; set; }
        public Nullable<decimal> Averagencddiscount { get; set; }
        public Nullable<int> Yearsncd1 { get; set; }
        public Nullable<decimal> Averagencddiscount1 { get; set; }
        public Nullable<decimal> Avrgencddisc1 { get; set; }
        public Nullable<int> Yearsncd2 { get; set; }
        public Nullable<decimal> Averagencddiscount2 { get; set; }
        public Nullable<decimal> Avrgencddisc2 { get; set; }
        public Nullable<int> Yearsncd3 { get; set; }
        public Nullable<decimal> Averagencddiscount3 { get; set; }
        public Nullable<decimal> Avrgencddisc3 { get; set; }
        public Nullable<int> Yearsncd4 { get; set; }
        public Nullable<decimal> Averagencddiscount4 { get; set; }
        public Nullable<decimal> Avrgencddisc4 { get; set; }
        public Nullable<int> Yearsncd5 { get; set; }
        public Nullable<decimal> Averagencddiscount5 { get; set; }
        public Nullable<decimal> Avrgencddisc5 { get; set; }
        public Nullable<int> Yearsncd6 { get; set; }
        public Nullable<decimal> Averagencddiscount6 { get; set; }
        public Nullable<decimal> Avrgencddisc6 { get; set; }
        public Nullable<int> Yearsncd7 { get; set; }
        public Nullable<decimal> Averagencddiscount7 { get; set; }
        public Nullable<decimal> Avrgencddisc7 { get; set; }
        public Nullable<int> Yearsncd8 { get; set; }
        public Nullable<decimal> Averagencddiscount8 { get; set; }
        public Nullable<decimal> Avrgencddisc8 { get; set; }
        public Nullable<int> Yearsncd9 { get; set; }
        public Nullable<decimal> Averagencddiscount9 { get; set; }
        public Nullable<decimal> Avrgencddisc9 { get; set; }
        public Nullable<int> Yearsncd10 { get; set; }
        public Nullable<decimal> Averagencddiscount10 { get; set; }
        public Nullable<decimal> Avrgencddisc10 { get; set; }
        public Nullable<int> Yearsncd11 { get; set; }
        public Nullable<decimal> Averagencddiscount11 { get; set; }
        public Nullable<decimal> Avrgencddisc11 { get; set; }
        public Nullable<int> Yearsncd12 { get; set; }
        public Nullable<decimal> Averagencddiscount12 { get; set; }
        public Nullable<decimal> Avrgencddisc12 { get; set; }
        public Nullable<int> Yearsncd13 { get; set; }
        public Nullable<decimal> Averagencddiscount13 { get; set; }
        public Nullable<decimal> Avrgencddisc13 { get; set; }
        public Nullable<int> Yearsncd14 { get; set; }
        public Nullable<decimal> Averagencddiscount14 { get; set; }
        public Nullable<decimal> Avrgencddisc14 { get; set; }
        public Nullable<int> Yearsncd15 { get; set; }
        public Nullable<decimal> Averagencddiscount15 { get; set; }
        public Nullable<decimal> Avrgencddisc15 { get; set; }
        public Nullable<int> Yearsncd16 { get; set; }
        public Nullable<decimal> Averagencddiscount16 { get; set; }
        public Nullable<decimal> Avrgencddisc16 { get; set; }
        public Nullable<int> Yearsncd17 { get; set; }
        public Nullable<decimal> Averagencddiscount17 { get; set; }
        public Nullable<decimal> Avrgencddisc17 { get; set; }
        public Nullable<int> Yearsncd18 { get; set; }
        public Nullable<decimal> Averagencddiscount18 { get; set; }
        public Nullable<decimal> Avrgencddisc18 { get; set; }
        public Nullable<int> Yearsncd19 { get; set; }
        public Nullable<decimal> Averagencddiscount19 { get; set; }
        public Nullable<decimal> Avrgencddisc19 { get; set; }
        public Nullable<int> Yearsncd20 { get; set; }
        public Nullable<decimal> Averagencddiscount20 { get; set; }
        public Nullable<decimal> Avrgencddisc20 { get; set; }
        public Nullable<int> Yearsncd21 { get; set; }
        public Nullable<decimal> Averagencddiscount21 { get; set; }
        public Nullable<decimal> Avrgencddisc21 { get; set; }
        public Nullable<int> Yearsncd22 { get; set; }
        public Nullable<decimal> Averagencddiscount22 { get; set; }
        public Nullable<decimal> Avrgencddisc22 { get; set; }
        public Nullable<int> Yearsncd23 { get; set; }
        public Nullable<decimal> Averagencddiscount23 { get; set; }
        public Nullable<decimal> Avrgencddisc23 { get; set; }
        public Nullable<int> Yearsncd24 { get; set; }
        public Nullable<decimal> Averagencddiscount24 { get; set; }
        public Nullable<decimal> Avrgencddisc24 { get; set; }
        public Nullable<int> Yearsncd25 { get; set; }
        public Nullable<decimal> Averagencddiscount25 { get; set; }
        public Nullable<decimal> Avrgencddisc25 { get; set; }
        public Nullable<int> Yearsncd26 { get; set; }
        public Nullable<decimal> Averagencddiscount26 { get; set; }
        public Nullable<decimal> Avrgencddisc26 { get; set; }
        public Nullable<int> Yearsncd27 { get; set; }
        public Nullable<decimal> Averagencddiscount27 { get; set; }
        public Nullable<decimal> Avrgencddisc27 { get; set; }
        public Nullable<int> Yearsncd28 { get; set; }
        public Nullable<decimal> Averagencddiscount28 { get; set; }
        public Nullable<decimal> Avrgencddisc28 { get; set; }
        public Nullable<int> Yearsncd29 { get; set; }
        public Nullable<decimal> Averagencddiscount29 { get; set; }
        public Nullable<decimal> Avrgencddisc29 { get; set; }
        public Nullable<int> Yearsncd30 { get; set; }
        public Nullable<decimal> Averagencddiscount30 { get; set; }
        public Nullable<decimal> Avrgencddisc30 { get; set; }
        public Nullable<int> Averagencdyear { get; set; }
        public string Insurername { get; set; }
        public string Insurerscid { get; set; }
        public string Endofrecord { get; set; }
        public Nullable<decimal> Originalncdimpliedpricewithipt { get; set; }
        public Nullable<decimal> Origncdprice { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public Nullable<int> Ncddataset { get; set; }
    }
}
