//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_SC
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string Adrr3 { get; set; }
        public string Adrr4 { get; set; }
        public string Cover { get; set; }
        public string Reinst { get; set; }
        public string Settbas { get; set; }
        public string Cov1 { get; set; }
        public Nullable<int> Si1 { get; set; }
        public Nullable<decimal> Rat1 { get; set; }
        public string Cov2 { get; set; }
        public Nullable<int> Si2 { get; set; }
        public Nullable<decimal> Rat2 { get; set; }
        public string Stock3 { get; set; }
        public string Cov3 { get; set; }
        public Nullable<int> Si3 { get; set; }
        public Nullable<decimal> Rat3 { get; set; }
        public string Stock4 { get; set; }
        public string Cov4 { get; set; }
        public Nullable<int> Si4 { get; set; }
        public Nullable<decimal> Rat4 { get; set; }
        public string Stock5 { get; set; }
        public string Cov5 { get; set; }
        public Nullable<int> Si5 { get; set; }
        public Nullable<decimal> Rat5 { get; set; }
        public Nullable<int> Seasinc { get; set; }
        public string Stock6 { get; set; }
        public string Cov6 { get; set; }
        public Nullable<int> Si6 { get; set; }
        public Nullable<decimal> Rat6 { get; set; }
        public string Cov7 { get; set; }
        public Nullable<int> Si7 { get; set; }
        public Nullable<decimal> Rat7 { get; set; }
        public string Cov8 { get; set; }
        public Nullable<int> Si8 { get; set; }
        public Nullable<decimal> Rat8 { get; set; }
        public string Cov9 { get; set; }
        public Nullable<int> Si9 { get; set; }
        public Nullable<decimal> Rat9 { get; set; }
        public string Cov10 { get; set; }
        public Nullable<int> Si10 { get; set; }
        public Nullable<decimal> Rat10 { get; set; }
        public string Desc11 { get; set; }
        public string Cov11 { get; set; }
        public Nullable<int> Si11 { get; set; }
        public Nullable<decimal> Rat11 { get; set; }
        public string Cov12 { get; set; }
        public Nullable<int> Si12 { get; set; }
        public Nullable<decimal> Rat12 { get; set; }
        public Nullable<int> Indemper { get; set; }
        public string Cov13 { get; set; }
        public Nullable<int> Si13 { get; set; }
        public Nullable<decimal> Rat13 { get; set; }
        public string Cov14 { get; set; }
        public Nullable<int> Si14 { get; set; }
        public Nullable<decimal> Rat14 { get; set; }
        public string Cov15 { get; set; }
        public Nullable<int> Si15 { get; set; }
        public Nullable<decimal> Rat15 { get; set; }
        public string Cov16 { get; set; }
        public Nullable<int> Si16 { get; set; }
        public Nullable<decimal> Rat16 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
