//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_MT
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string RatBas { get; set; }
        public string Cover { get; set; }
        public Nullable<System.DateTime> NCBDate { get; set; }
        public Nullable<int> Excess { get; set; }
        public Nullable<int> No1 { get; set; }
        public Nullable<int> Pts1 { get; set; }
        public Nullable<int> No2 { get; set; }
        public Nullable<int> Pts2 { get; set; }
        public Nullable<int> No3 { get; set; }
        public Nullable<int> Pts3 { get; set; }
        public Nullable<int> No4 { get; set; }
        public Nullable<int> Pts4 { get; set; }
        public Nullable<int> No5 { get; set; }
        public Nullable<int> Pts5 { get; set; }
        public Nullable<int> No6 { get; set; }
        public Nullable<int> Pts6 { get; set; }
        public Nullable<int> PtsTot { get; set; }
        public string Cov1 { get; set; }
        public Nullable<decimal> Prem1 { get; set; }
        public string Cov2 { get; set; }
        public Nullable<decimal> Prem2 { get; set; }
        public string Cov3 { get; set; }
        public Nullable<decimal> Prem3 { get; set; }
        public string Cov4 { get; set; }
        public Nullable<decimal> Prem4 { get; set; }
        public string Cov5 { get; set; }
        public Nullable<decimal> Prem5 { get; set; }
        public string Cov6 { get; set; }
        public Nullable<decimal> Prem6 { get; set; }
        public Nullable<decimal> BasicPrem { get; set; }
        public string Driv1 { get; set; }
        public string Desc1 { get; set; }
        public string Driv2 { get; set; }
        public string Desc2 { get; set; }
        public string Driv3 { get; set; }
        public string Desc3 { get; set; }
        public string Driv4 { get; set; }
        public string Desc4 { get; set; }
        public string Driv5 { get; set; }
        public string Desc5 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
