//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_brsettle
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string C_Key { get; set; }
        public Nullable<int> Rtype { get; set; }
        public Nullable<int> Icno_INSC_VTId { get; set; }
        public string S1_polref { get; set; }
        public Nullable<System.DateTime> S1_ldate { get; set; }
        public Nullable<System.DateTime> S2_ldate { get; set; }
        public string S2_polref { get; set; }
        public Nullable<int> Suffix { get; set; }
        public string C_Order { get; set; }
        public Nullable<System.DateTime> Pdate { get; set; }
        public Nullable<decimal> Ptot { get; set; }
        public Nullable<decimal> Rtot { get; set; }
        public Nullable<decimal> Ctot { get; set; }
        public Nullable<decimal> Ttot { get; set; }
        public Nullable<int> List { get; set; }
        public string Hpstat { get; set; }
        public Nullable<int> Xeff { get; set; }
        public Nullable<int> Bacsonly { get; set; }
        public string Polno { get; set; }
        public string Ttype { get; set; }
        public string Pm { get; set; }
        public Nullable<decimal> To_set { get; set; }
        public Nullable<decimal> C_per { get; set; }
        public Nullable<decimal> C_amt { get; set; }
        public string Phold { get; set; }
        public string Ctype { get; set; }
        public Nullable<decimal> Poac { get; set; }
        public string Sflag { get; set; }
        public Nullable<int> Branch { get; set; }
        public string Pf { get; set; }
        public string Lpstat { get; set; }
        public Nullable<System.DateTime> Effdat { get; set; }
        public Nullable<decimal> Odebt { get; set; }
        public Nullable<decimal> Premdue { get; set; }
        public Nullable<decimal> Gross_exempt { get; set; }
        public Nullable<decimal> Ipt_rate { get; set; }
        public Nullable<decimal> Ipt_amount { get; set; }
        public Nullable<int> No_ipt { get; set; }
        public string Status { get; set; }
        public string C_Match { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
