//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_brinst
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public Nullable<int> C_Key { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Spare_key { get; set; }
        public Nullable<decimal> Int_amt_nb { get; set; }
        public Nullable<int> Int_fac_nb_FLAG_VTId { get; set; }
        public Nullable<decimal> Dep_amt_nb { get; set; }
        public Nullable<int> Dep_fac_nb_FLAG_VTId { get; set; }
        public Nullable<int> No_inst_nb { get; set; }
        public Nullable<decimal> Int_amt_ren { get; set; }
        public Nullable<int> Int_fac_ren_FLAG_VTId { get; set; }
        public Nullable<decimal> Dep_amt_ren { get; set; }
        public Nullable<int> Dep_fac_ren_FLAG_VTId { get; set; }
        public Nullable<int> No_inst_ren { get; set; }
        public Nullable<decimal> Int_amt_nb_s1 { get; set; }
        public Nullable<decimal> Int_amt_nb_s2 { get; set; }
        public Nullable<decimal> Int_amt_nb_s3 { get; set; }
        public Nullable<decimal> Int_amt_nb_s4 { get; set; }
        public Nullable<int> Int_fac_nb_s1_FLAG_VTId { get; set; }
        public Nullable<int> Int_fac_nb_s2_FLAG_VTId { get; set; }
        public Nullable<int> Int_fac_nb_s3_FLAG_VTId { get; set; }
        public Nullable<int> Int_fac_nb_s4_FLAG_VTId { get; set; }
        public Nullable<decimal> Dep_amt_nb_s1 { get; set; }
        public Nullable<decimal> Dep_amt_nb_s2 { get; set; }
        public Nullable<decimal> Dep_amt_nb_s3 { get; set; }
        public Nullable<decimal> Dep_amt_nb_s4 { get; set; }
        public Nullable<int> Dep_fac_nb_s1_FLAG_VTId { get; set; }
        public Nullable<int> Dep_fac_nb_s2_FLAG_VTId { get; set; }
        public Nullable<int> Dep_fac_nb_s3_FLAG_VTId { get; set; }
        public Nullable<int> Dep_fac_nb_s4_FLAG_VTId { get; set; }
        public Nullable<int> No_inst_nb_s1 { get; set; }
        public Nullable<int> No_inst_nb_s2 { get; set; }
        public Nullable<int> No_inst_nb_s3 { get; set; }
        public Nullable<int> No_inst_nb_s4 { get; set; }
        public Nullable<decimal> Int_amt_ren_s1 { get; set; }
        public Nullable<decimal> Int_amt_ren_s2 { get; set; }
        public Nullable<decimal> Int_amt_ren_s3 { get; set; }
        public Nullable<decimal> Int_amt_ren_s4 { get; set; }
        public Nullable<int> Int_fac_ren_s1_FLAG_VTId { get; set; }
        public Nullable<int> Int_fac_ren_s2_FLAG_VTId { get; set; }
        public Nullable<int> Int_fac_ren_s3_FLAG_VTId { get; set; }
        public Nullable<int> Int_fac_ren_s4_FLAG_VTId { get; set; }
        public Nullable<decimal> Dep_amt_ren_s1 { get; set; }
        public Nullable<decimal> Dep_amt_ren_s2 { get; set; }
        public Nullable<decimal> Dep_amt_ren_s3 { get; set; }
        public Nullable<decimal> Dep_amt_ren_s4 { get; set; }
        public Nullable<int> Dep_fac_ren_s1_FLAG_VTId { get; set; }
        public Nullable<int> Dep_fac_ren_s2_FLAG_VTId { get; set; }
        public Nullable<int> Dep_fac_ren_s3_FLAG_VTId { get; set; }
        public Nullable<int> Dep_fac_ren_s4_FLAG_VTId { get; set; }
        public Nullable<int> No_inst_ren_s1 { get; set; }
        public Nullable<int> No_inst_ren_s2 { get; set; }
        public Nullable<int> No_inst_ren_s3 { get; set; }
        public Nullable<int> No_inst_ren_s4 { get; set; }
        public string Add_chg_requo { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
