//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_ccwordings
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string Keycode { get; set; }
        public string Wording_1 { get; set; }
        public string Wording_2 { get; set; }
        public string Status { get; set; }
        public string Wording_3 { get; set; }
        public string Wording_4 { get; set; }
        public string Wording_5 { get; set; }
        public string Wording_6 { get; set; }
        public string Wording_7 { get; set; }
        public string Wording_8 { get; set; }
        public string Wording_9 { get; set; }
        public string Wording_10 { get; set; }
        public string Wording_11 { get; set; }
        public string C_Description { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
