//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_PCPR
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> pcins_YENO_VTId { get; set; }
        public Nullable<System.DateTime> rdat { get; set; }
        public string contact { get; set; }
        public string tel { get; set; }
        public Nullable<decimal> time_f { get; set; }
        public string am_pm1 { get; set; }
        public Nullable<decimal> time_t { get; set; }
        public string am_pm2 { get; set; }
        public string act1 { get; set; }
        public string act2 { get; set; }
        public Nullable<int> addveh_YENO_VTId { get; set; }
        public Nullable<System.DateTime> rdat1 { get; set; }
        public Nullable<System.DateTime> rdat2 { get; set; }
        public Nullable<System.DateTime> rdat3 { get; set; }
        public Nullable<System.DateTime> rdat4 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
