//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_yyabimap
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public Nullable<int> Insco_INSC_VTId { get; set; }
        public Nullable<int> Abino { get; set; }
        public string Status { get; set; }
        public string C_Key { get; set; }
        public string Brokerrcpts { get; set; }
        public Nullable<int> Air_electronic_YENO_VTId { get; set; }
        public Nullable<int> Air_prevent_add_YENO_VTId { get; set; }
        public Nullable<int> Abi_code_NW54_VTId { get; set; }
        public Nullable<int> Abi_name_QR54_VTId { get; set; }
        public Nullable<int> Air_date_tol { get; set; }
        public string Ins_type { get; set; }
        public Nullable<System.DateTime> Toba { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
