//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_brpoldesc
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string Poltype { get; set; }
        public string C_Description { get; set; }
        public string Frame1 { get; set; }
        public string Frame2 { get; set; }
        public string Frame3 { get; set; }
        public string Frame4 { get; set; }
        public string Frame5 { get; set; }
        public Nullable<int> Reg_seq { get; set; }
        public string Frame6 { get; set; }
        public string Frame7 { get; set; }
        public string Frame8 { get; set; }
        public string Frame9 { get; set; }
        public string Frame10 { get; set; }
        public string Frame11 { get; set; }
        public string Frame12 { get; set; }
        public string Frame13 { get; set; }
        public string Frame14 { get; set; }
        public string Frame15 { get; set; }
        public string Frame16 { get; set; }
        public string Frame17 { get; set; }
        public string Frame18 { get; set; }
        public string Frame19 { get; set; }
        public string Frame20 { get; set; }
        public string Frame21 { get; set; }
        public string Frame22 { get; set; }
        public string Frame23 { get; set; }
        public string Frame24 { get; set; }
        public string Frame25 { get; set; }
        public string Frame26 { get; set; }
        public string Frame27 { get; set; }
        public string Frame28 { get; set; }
        public string Frame29 { get; set; }
        public string Frame30 { get; set; }
        public string Frame31 { get; set; }
        public string Frame32 { get; set; }
        public string Frame33 { get; set; }
        public string Frame34 { get; set; }
        public string Frame35 { get; set; }
        public string Frame36 { get; set; }
        public string Frame37 { get; set; }
        public string Frame38 { get; set; }
        public string Frame39 { get; set; }
        public string Frame40 { get; set; }
        public string Long_desc { get; set; }
        public string Cc_override { get; set; }
        public string Cc_custclass { get; set; }
        public Nullable<int> Cc_product_CCM1_VTId { get; set; }
        public string Addon_pol { get; set; }
        public Nullable<int> Cc_salesdata_CCM3_VTId { get; set; }
        public string Authorisation { get; set; }
        public string C_Dummy { get; set; }
        public string Status { get; set; }
        public Nullable<int> Abi_code_BRPT_VTId { get; set; }
        public string Quoteeng { get; set; }
        public string Quoteeng_fromapm { get; set; }
        public Nullable<int> Prodserv_CCM4_VTId { get; set; }
        public Nullable<decimal> Charge { get; set; }
        public Nullable<decimal> Charge_n { get; set; }
        public Nullable<decimal> Charge_r { get; set; }
        public Nullable<decimal> Charge_e { get; set; }
        public Nullable<decimal> Charge_ca { get; set; }
        public Nullable<decimal> Charge_a { get; set; }
        public Nullable<decimal> Charge_t { get; set; }
        public Nullable<decimal> Charge_j { get; set; }
        public Nullable<decimal> Charge_cl { get; set; }
        public Nullable<int> Charge_code { get; set; }
        public Nullable<int> Charge_code_n { get; set; }
        public Nullable<int> Charge_code_r { get; set; }
        public Nullable<int> Charge_code_e { get; set; }
        public Nullable<int> Charge_code_ca { get; set; }
        public Nullable<int> Charge_code_a { get; set; }
        public Nullable<int> Charge_code_t { get; set; }
        public Nullable<int> Charge_code_j { get; set; }
        public Nullable<int> Charge_code_cl { get; set; }
        public string Charge_type { get; set; }
        public string Charge_type_n { get; set; }
        public string Charge_type_r { get; set; }
        public string Charge_type_e { get; set; }
        public string Charge_type_ca { get; set; }
        public string Charge_type_a { get; set; }
        public string Charge_type_t { get; set; }
        public string Charge_type_j { get; set; }
        public string Charge_type_cl { get; set; }
        public Nullable<decimal> Min_charge { get; set; }
        public Nullable<decimal> Min_charge_n { get; set; }
        public Nullable<decimal> Min_charge_r { get; set; }
        public Nullable<decimal> Min_charge_e { get; set; }
        public Nullable<decimal> Min_charge_ca { get; set; }
        public Nullable<decimal> Min_charge_a { get; set; }
        public Nullable<decimal> Min_charge_t { get; set; }
        public Nullable<decimal> Min_charge_j { get; set; }
        public Nullable<decimal> Min_charge_cl { get; set; }
        public string Aoproductid { get; set; }
        public string Aoproductname { get; set; }
        public string Mp_l2_type { get; set; }
        public string Mp_l2_type_used { get; set; }
        public string Usetraderff { get; set; }
        public Nullable<int> Traderff_formid { get; set; }
        public Nullable<int> Cc_psgroup2016_CCM6_VTId { get; set; }
        public Nullable<int> Cc_prodserv2016_CCM7_VTId { get; set; }
        public string Cc_psother2016 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
