//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_yycontactinf
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string C_Key { get; set; }
        public string Source { get; set; }
        public string Sourceref { get; set; }
        public string Brclientref { get; set; }
        public string Prospectref { get; set; }
        public Nullable<int> Suffix { get; set; }
        public string Status { get; set; }
        public string C_Default { get; set; }
        public Nullable<System.DateTime> Date_lastupd { get; set; }
        public string Time_lastupd { get; set; }
        public string Operator { get; set; }
        public string C_Name { get; set; }
        public string Ext_name { get; set; }
        public string Title { get; set; }
        public string Forenames { get; set; }
        public string C_Description { get; set; }
        public string Tel { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Tel4 { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public string Email { get; set; }
        public string Contactpref { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string Addr3 { get; set; }
        public string Addr4 { get; set; }
        public string Pcode { get; set; }
        public string Sanctionscheck { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Copytoframe { get; set; }
        public string Fromapmkey { get; set; }
        public string Fromapmsource { get; set; }
        public string Fromapmprospectref { get; set; }
        public Nullable<int> Fromapmsuffix { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
