//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_BQS
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> Yesno1_QR19_VTId { get; set; }
        public Nullable<int> Yesno2_QR19_VTId { get; set; }
        public Nullable<int> Yesno3_QR19_VTId { get; set; }
        public Nullable<int> Yesno4_QR19_VTId { get; set; }
        public Nullable<int> Yesno5_QR19_VTId { get; set; }
        public Nullable<int> Yesno6_QR19_VTId { get; set; }
        public Nullable<int> Yesno7_QR19_VTId { get; set; }
        public Nullable<int> Yesno8_QR19_VTId { get; set; }
        public Nullable<int> Yesno9_QR19_VTId { get; set; }
        public Nullable<int> Yesno10_QR19_VTId { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public Nullable<System.DateTime> Date4 { get; set; }
        public Nullable<System.DateTime> Date5 { get; set; }
        public Nullable<System.DateTime> Date6 { get; set; }
        public Nullable<System.DateTime> Date7 { get; set; }
        public Nullable<System.DateTime> Date8 { get; set; }
        public Nullable<System.DateTime> Date9 { get; set; }
        public Nullable<System.DateTime> Date10 { get; set; }
        public Nullable<int> C_Integer1 { get; set; }
        public Nullable<int> C_Integer2 { get; set; }
        public Nullable<int> Integer3 { get; set; }
        public Nullable<int> C_Integer4 { get; set; }
        public Nullable<int> Integer5 { get; set; }
        public Nullable<int> Integer6 { get; set; }
        public Nullable<int> Integer7 { get; set; }
        public Nullable<int> Integer8 { get; set; }
        public Nullable<int> Integer9 { get; set; }
        public Nullable<int> Integer10 { get; set; }
        public Nullable<decimal> Decimal1 { get; set; }
        public Nullable<decimal> Decimal2 { get; set; }
        public Nullable<decimal> Decimal3 { get; set; }
        public Nullable<decimal> Decimal4 { get; set; }
        public Nullable<decimal> Decimal5 { get; set; }
        public Nullable<decimal> Decimal6 { get; set; }
        public Nullable<decimal> Decimal7 { get; set; }
        public Nullable<decimal> Decimal8 { get; set; }
        public Nullable<decimal> Decimal9 { get; set; }
        public Nullable<decimal> Decimal10 { get; set; }
        public string Freetext1 { get; set; }
        public string Freetext2 { get; set; }
        public string Freetext3 { get; set; }
        public string Freetext4 { get; set; }
        public string Freetext5 { get; set; }
        public string Vtlist1desc { get; set; }
        public string Vtlist2desc { get; set; }
        public string Vtlist3desc { get; set; }
        public string Vtlist4desc { get; set; }
        public string Vtlist5desc { get; set; }
        public Nullable<int> Vtlist1slot { get; set; }
        public Nullable<int> Vtlist2slot { get; set; }
        public Nullable<int> Vtlist3slot { get; set; }
        public Nullable<int> Vtlist4slot { get; set; }
        public Nullable<int> Vtlist5slot { get; set; }
        public string Endofrecord { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
