//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_ERB_History
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> Buffersizeinwords { get; set; }
        public Nullable<int> Currenterb { get; set; }
        public Nullable<int> Totalerb { get; set; }
        public string C_Result { get; set; }
        public string Quotesource { get; set; }
        public string Insurererrormsg1 { get; set; }
        public string Insurererrormsg2 { get; set; }
        public string Ogierrorcode { get; set; }
        public string Ogierrormsg1 { get; set; }
        public string Ogierrormsg2 { get; set; }
        public string Insurerscheme { get; set; }
        public Nullable<int> Ic { get; set; }
        public string Enrichmentstring { get; set; }
        public string Enrichmentstring1 { get; set; }
        public string Enrichmentstring2 { get; set; }
        public string Enrichmentstring3 { get; set; }
        public string Enrichmentstring4 { get; set; }
        public string Ratedpostcodeareatermstr_comp { get; set; }
        public string Ratedpostcodeareagrpstr_comp { get; set; }
        public string Ratedpostcodeareatermstr_tpft { get; set; }
        public string Ratedpostcodeareagrpstr_tpft { get; set; }
        public string Ratedpostcodeareatermstr_tpo { get; set; }
        public string Ratedpostcodeareagrpstr_tpo { get; set; }
        public string Proposerpostcodeareatermstr_comp { get; set; }
        public string Proposerpostcodeareagrpstr_comp { get; set; }
        public string Proposerpostcodeareatermstr_tpft { get; set; }
        public string Proposerpostcodeareagrpstr_tpft { get; set; }
        public string Proposerpostcodeareatermstr_tpo { get; set; }
        public string Proposerpostcodeareagrpstr_tpo { get; set; }
        public string Enrichmentrequestid { get; set; }
        public Nullable<System.DateTime> Enrichmentdate { get; set; }
        public string Enrichmenttime { get; set; }
        public string Quotereference { get; set; }
        public string Ogixmllogid { get; set; }
        public string Service { get; set; }
        public Nullable<int> Enrichmenttimeinsecs { get; set; }
        public string Fprversion { get; set; }
        public string Provider { get; set; }
        public string Endofrecord { get; set; }
        public Nullable<int> Brokerenrichment_QR19_VTId { get; set; }
        public Nullable<int> Brokerenrichmentitemdesc_QEBD_VTId { get; set; }
        public string Brokerenrichmentitemvalue { get; set; }
        public Nullable<int> Brokerenrichmentitemvaluetypeid { get; set; }
        public string Brokerenrichmentitemvaluetypevt { get; set; }
        public Nullable<int> Brokerenrichmentitemdesc1_QEBD_VTId { get; set; }
        public string Brokerenrichmentitemvalue1 { get; set; }
        public Nullable<int> Brokerenrichmentitemvaluetypeid1 { get; set; }
        public string Brokerenrichmentitemvaluetypevt1 { get; set; }
        public Nullable<int> Brokerenrichmentitemdesc2_QEBD_VTId { get; set; }
        public string Brokerenrichmentitemvalue2 { get; set; }
        public Nullable<int> Brokerenrichmentitemvaluetypeid2 { get; set; }
        public string Brokerenrichmentitemvaluetypevt2 { get; set; }
        public Nullable<int> Brokerenrichmentitemdesc3_QEBD_VTId { get; set; }
        public string Brokerenrichmentitemvalue3 { get; set; }
        public Nullable<int> Brokerenrichmentitemvaluetypeid3 { get; set; }
        public string Brokerenrichmentitemvaluetypevt3 { get; set; }
        public Nullable<int> Brokerenrichmentitemdesc4_QEBD_VTId { get; set; }
        public string Brokerenrichmentitemvalue4 { get; set; }
        public Nullable<int> Brokerenrichmentitemvaluetypeid4 { get; set; }
        public string Brokerenrichmentitemvaluetypevt4 { get; set; }
        public Nullable<int> Brokerenrichmentitemdesc5_QEBD_VTId { get; set; }
        public string Brokerenrichmentitemvalue5 { get; set; }
        public Nullable<int> Brokerenrichmentitemvaluetypeid5 { get; set; }
        public string Brokerenrichmentitemvaluetypevt5 { get; set; }
        public Nullable<int> Brokerenrichmentitemdesc6_QEBD_VTId { get; set; }
        public string Brokerenrichmentitemvalue6 { get; set; }
        public Nullable<int> Brokerenrichmentitemvaluetypeid6 { get; set; }
        public string Brokerenrichmentitemvaluetypevt6 { get; set; }
        public Nullable<int> Brokerenrichmentitemdesc7_QEBD_VTId { get; set; }
        public string Brokerenrichmentitemvalue7 { get; set; }
        public Nullable<int> Brokerenrichmentitemvaluetypeid7 { get; set; }
        public string Brokerenrichmentitemvaluetypevt7 { get; set; }
        public Nullable<int> Brokerenrichmentitemdesc8_QEBD_VTId { get; set; }
        public string Brokerenrichmentitemvalue8 { get; set; }
        public Nullable<int> Brokerenrichmentitemvaluetypeid8 { get; set; }
        public string Brokerenrichmentitemvaluetypevt8 { get; set; }
        public string Auditfilename { get; set; }
        public Nullable<int> Brokerenrichmentitemindex { get; set; }
        public Nullable<int> Brokerenrichmentitemindex1 { get; set; }
        public Nullable<int> Brokerenrichmentitemindex2 { get; set; }
        public Nullable<int> Brokerenrichmentitemindex3 { get; set; }
        public Nullable<int> Brokerenrichmentitemindex4 { get; set; }
        public Nullable<int> Brokerenrichmentitemindex5 { get; set; }
        public Nullable<int> Brokerenrichmentitemindex6 { get; set; }
        public Nullable<int> Brokerenrichmentitemindex7 { get; set; }
        public Nullable<int> Brokerenrichmentitemindex8 { get; set; }
        public string Brokerenrichmentprovider { get; set; }
        public string Bericprovider { get; set; }
        public Nullable<System.DateTime> History_ { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
