//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_LE
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string PolType { get; set; }
        public string SlfEmp { get; set; }
        public string MotProt { get; set; }
        public Nullable<int> NoCars { get; set; }
        public Nullable<int> NoMotCyc { get; set; }
        public string AccLss { get; set; }
        public string GenProt { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string ADdr3 { get; set; }
        public string Addr4 { get; set; }
        public string Addr5 { get; set; }
        public string TenDisp { get; set; }
        public string IllOcc { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string RegNo { get; set; }
        public string Comm1 { get; set; }
        public string Comm2 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
