//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_NEDM
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string C_Comp { get; set; }
        public string TPFT { get; set; }
        public string Prot { get; set; }
        public string AnyD { get; set; }
        public string Youd { get; set; }
        public string Req1 { get; set; }
        public string Req2 { get; set; }
        public string Req3 { get; set; }
        public string Advise1 { get; set; }
        public string Advise2 { get; set; }
        public string Advise3 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
