//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_EV_SWAP
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Suffix_ { get; set; }
        public string C_From { get; set; }
        public string C_To { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public string Det1 { get; set; }
        public string Det2 { get; set; }
        public string Det3 { get; set; }
        public string Det4 { get; set; }
        public string Det5 { get; set; }
        public string Det6 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
