//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_pfinstscheme
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string C_def_on_create { get; set; }
        public string C_def_on_pay { get; set; }
        public Nullable<int> Finance_provider_B006_VTId { get; set; }
        public string Scheme_id { get; set; }
        public string C_Key { get; set; }
        public string Scheme_name { get; set; }
        public string Scheme_desc1 { get; set; }
        public string Scheme_desc2 { get; set; }
        public string Fp_scheme_id { get; set; }
        public Nullable<decimal> Min_prem { get; set; }
        public Nullable<decimal> Min_credit { get; set; }
        public Nullable<decimal> Min_deposit { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public string Min_prem_type { get; set; }
        public string Min_credit_type { get; set; }
        public string Min_dep_type { get; set; }
        public string Dep_type { get; set; }
        public string Fp_collect_dep { get; set; }
        public string Freq { get; set; }
        public Nullable<int> Instalments { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> Ppi { get; set; }
        public string Ppi_type { get; set; }
        public string Ppi_code { get; set; }
        public Nullable<int> Pref_pay_days { get; set; }
        public string Dd_print { get; set; }
        public string Ca_print { get; set; }
        public string Netgross { get; set; }
        public string Add_le_charge { get; set; }
        public Nullable<int> Dd_letter_DOCT_VTId { get; set; }
        public Nullable<int> Ca_letter_DOCT_VTId { get; set; }
        public Nullable<decimal> Max_interest { get; set; }
        public Nullable<decimal> Min_interest { get; set; }
        public Nullable<decimal> Max_le_charge { get; set; }
        public string Instal_opt { get; set; }
        public string C_all_receipts { get; set; }
        public string Min_dep_eutype { get; set; }
        public string Dep_eutype { get; set; }
        public string Ppi_eutype { get; set; }
        public string C_training { get; set; }
        public string C_system_set { get; set; }
        public Nullable<int> Mta_min_pays { get; set; }
        public string Renewal_only { get; set; }
        public Nullable<decimal> Min_end_ap { get; set; }
        public Nullable<decimal> Min_end_rp { get; set; }
        public string Add_addons { get; set; }
        public string Fp_scheme_id2 { get; set; }
        public string C_offer_in_apm { get; set; }
        public string C_bypass_fp { get; set; }
        public string Typeofscheme { get; set; }
        public string C_iscd_check { get; set; }
        public string C_ei_auth_code { get; set; }
        public Nullable<decimal> Max_prem { get; set; }
        public string Typeofplan { get; set; }
        public Nullable<decimal> Max_end_ap { get; set; }
        public string C_pf_auth_code { get; set; }
        public string C_compare { get; set; }
        public string C_compareppi { get; set; }
        public string Compexc { get; set; }
        public string C_charge_code { get; set; }
        public Nullable<decimal> Annual_fee { get; set; }
        public Nullable<decimal> Month_fee { get; set; }
        public string C_bank_auth_code { get; set; }
        public string C_prop_auth_code { get; set; }
        public string C_canc_auth_code { get; set; }
        public string C_decl_auth_code { get; set; }
        public string C_freq_auth_code { get; set; }
        public string C_agdc_auth_code { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
