//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_EV_SMS
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Suffix_ { get; set; }
        public string C_From { get; set; }
        public string C_To { get; set; }
        public string Mobile { get; set; }
        public string Time2besent { get; set; }
        public Nullable<System.DateTime> Date2besent { get; set; }
        public Nullable<System.DateTime> Datesent { get; set; }
        public string Timesent { get; set; }
        public Nullable<int> Replydue { get; set; }
        public string C_Exec { get; set; }
        public string Replystatus { get; set; }
        public string Priority { get; set; }
        public string Smsstatus { get; set; }
        public string Thirdparty { get; set; }
        public string Messagetext1 { get; set; }
        public string Messagetext2 { get; set; }
        public string Messagetext3 { get; set; }
        public string Diarymesstext { get; set; }
        public string Reasonforfail1 { get; set; }
        public string Reasonforfail2 { get; set; }
        public string Reasonforfail3 { get; set; }
        public Nullable<int> Claim_ref { get; set; }
        public string Claim_type { get; set; }
        public string Claim_loss { get; set; }
        public string Claim_stat { get; set; }
        public string Operator { get; set; }
        public string Smqkey { get; set; }
        public string Execln { get; set; }
        public string Messagetext3_old { get; set; }
        public string Messagetext4 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
