//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_ERM_History
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> Buffersizeinwords { get; set; }
        public Nullable<int> Currenterm { get; set; }
        public Nullable<int> Totalerm { get; set; }
        public string C_Result { get; set; }
        public string Quotesource { get; set; }
        public string Insurererrormsg1 { get; set; }
        public string Insurererrormsg2 { get; set; }
        public string Ogierrorcode { get; set; }
        public string Ogierrormsg1 { get; set; }
        public string Ogierrormsg2 { get; set; }
        public string Insurerscheme { get; set; }
        public string Enrichmentstring { get; set; }
        public string Enrichmentstring1 { get; set; }
        public string Enrichmentstring2 { get; set; }
        public string Enrichmentstring3 { get; set; }
        public string Enrichmentstring4 { get; set; }
        public string Enrichmentrequestid { get; set; }
        public Nullable<System.DateTime> Enrichmentdate { get; set; }
        public string Enrichmenttime { get; set; }
        public string Quotereference { get; set; }
        public string Ogixmllogid { get; set; }
        public Nullable<int> Enrichmenttimeinsecs { get; set; }
        public string Endofrecord { get; set; }
        public string Ratedpostcodeareatermstr_comp { get; set; }
        public string Ratedpostcodeareagrpstr_comp { get; set; }
        public string Baseofficepostcodearea2termstr_comp { get; set; }
        public string Baseofficepostcodearea2grpstr_comp { get; set; }
        public string Ratedpostcodeareatermstr_tpft { get; set; }
        public string Ratedpostcodeareagrpstr_tpft { get; set; }
        public string Baseofficepostcodearea2termstr_tpft { get; set; }
        public string Baseofficepostcodearea2grpstr_tpft { get; set; }
        public string Ratedpostcodeareatermstr_tpo { get; set; }
        public string Ratedpostcodeareagrpstr_tpo { get; set; }
        public string Baseofficepostcodearea2termstr_tpo { get; set; }
        public string Baseofficepostcodearea2grpstr_tpo { get; set; }
        public string Fprversion { get; set; }
        public string Service { get; set; }
        public string Propaddrpcareatermstr_comp { get; set; }
        public string Propaddrpcareagrpstr_comp { get; set; }
        public string Propaddrpcareatermstr_tpft { get; set; }
        public string Propaddrpcareagrpstr_tpft { get; set; }
        public string Propaddrpcareatermstr_tpo { get; set; }
        public string Propaddrpcareagrpstr_tpo { get; set; }
        public string Rteproductversion { get; set; }
        public string Brokerenrichmentprovider { get; set; }
        public string Bericprovider { get; set; }
        public string Ihpextendedquoteref { get; set; }
        public string Riiinsurercodeid { get; set; }
        public Nullable<int> Riivehicleprimarycode { get; set; }
        public Nullable<System.DateTime> Riidateofsale { get; set; }
        public Nullable<System.DateTime> History_ { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
