//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_HRS1
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string C_Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string PCodeBase { get; set; }
        public string PCodeHome { get; set; }
        public Nullable<int> NCB { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<int> EnSize { get; set; }
        public string Reg { get; set; }
        public Nullable<int> YrMade { get; set; }
        public Nullable<int> C_Value { get; set; }
        public Nullable<System.DateTime> RDat { get; set; }
        public string Period { get; set; }
        public Nullable<decimal> CurrPrem { get; set; }
        public string CurrInsCo { get; set; }
        public Nullable<decimal> NewPrem { get; set; }
        public string NewInsCo { get; set; }
        public string Driver1 { get; set; }
        public string Driver2 { get; set; }
        public string Driver3 { get; set; }
        public string Driver4 { get; set; }
        public string Driver5 { get; set; }
        public string Driver6 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
