//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_QRR
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Currname { get; set; }
        public string Currcode { get; set; }
        public string Currloaddisc { get; set; }
        public Nullable<decimal> Currprem { get; set; }
        public string Currqflag { get; set; }
        public string Currstarrate { get; set; }
        public string Currrefuse { get; set; }
        public Nullable<int> Topncount { get; set; }
        public string Topnname { get; set; }
        public string Topncode { get; set; }
        public Nullable<decimal> Topnpremium { get; set; }
        public string Topnqflag { get; set; }
        public string Topnloaddisc { get; set; }
        public string Topnstarrate { get; set; }
        public string Topnrefuse { get; set; }
        public string Top1name { get; set; }
        public string Top1code { get; set; }
        public Nullable<decimal> Top1premium { get; set; }
        public string Top1qflag { get; set; }
        public string Top1loaddisc { get; set; }
        public string Top1starrate { get; set; }
        public string Top1refuse { get; set; }
        public string Top2name { get; set; }
        public string Top2code { get; set; }
        public Nullable<decimal> Top2premium { get; set; }
        public string Top2qflag { get; set; }
        public string Top2loaddisc { get; set; }
        public string Top2starrate { get; set; }
        public string Top2refuse { get; set; }
        public string Top3name { get; set; }
        public string Top3code { get; set; }
        public Nullable<decimal> Top3premium { get; set; }
        public string Top3qflag { get; set; }
        public string Top3loaddisc { get; set; }
        public string Top3starrate { get; set; }
        public string Top3refuse { get; set; }
        public string Top4name { get; set; }
        public string Top4code { get; set; }
        public Nullable<decimal> Top4premium { get; set; }
        public string Top4qflag { get; set; }
        public string Top4loaddisc { get; set; }
        public string Top4starrate { get; set; }
        public string Top4refuse { get; set; }
        public string Top5name { get; set; }
        public string Top5code { get; set; }
        public Nullable<decimal> Top5premium { get; set; }
        public string Top5qflag { get; set; }
        public string Top5loaddisc { get; set; }
        public string Top5starrate { get; set; }
        public string Top5refuse { get; set; }
        public string Altschemename { get; set; }
        public string Altschemecode { get; set; }
        public Nullable<decimal> Altschemepremium { get; set; }
        public string Altschemeqflag { get; set; }
        public string Altschemeloaddisc { get; set; }
        public string Altschemestarrate { get; set; }
        public string Altschemerefuse { get; set; }
        public Nullable<int> Riskframesupdated_QR19_VTId { get; set; }
        public string Riskframesbyscheme { get; set; }
        public Nullable<System.DateTime> Coverdate { get; set; }
        public string Ratesused { get; set; }
        public string Operator { get; set; }
        public Nullable<int> Selectlist { get; set; }
        public Nullable<System.DateTime> Quotedate { get; set; }
        public string Quotetime { get; set; }
        public string Framecalcresult { get; set; }
        public string Endofrecord { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
