//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_pfcontrol
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public Nullable<int> Branch { get; set; }
        public Nullable<int> Finance_provider_B006_VTId { get; set; }
        public string Dummy_policy { get; set; }
        public Nullable<decimal> Tolerance_plus { get; set; }
        public Nullable<decimal> Tolerance_minus { get; set; }
        public string Tol_plus_type { get; set; }
        public string Tol_minus_type { get; set; }
        public Nullable<int> Transmission_no { get; set; }
        public Nullable<int> Reception_no { get; set; }
        public string Data_centre { get; set; }
        public string Centre_desc { get; set; }
        public string Status { get; set; }
        public string C_Key { get; set; }
        public Nullable<int> C_traffic_seqno { get; set; }
        public Nullable<System.DateTime> C_traffic_date { get; set; }
        public Nullable<System.DateTime> C_traffic_sent { get; set; }
        public string Tol_plus_eutype { get; set; }
        public string Tol_minus_eutype { get; set; }
        public Nullable<int> Agree_start { get; set; }
        public Nullable<int> Agree_end { get; set; }
        public Nullable<int> Agree_next { get; set; }
        public string Suppress_district_code { get; set; }
        public string External_call { get; set; }
        public Nullable<int> Ext_call_to { get; set; }
        public string Url_part1 { get; set; }
        public string Url_part2 { get; set; }
        public string Web_logon { get; set; }
        public string Web_password { get; set; }
        public Nullable<int> Web_trans_id { get; set; }
        public string Proxy_host { get; set; }
        public Nullable<int> Proxy_port { get; set; }
        public string Proxy_logon { get; set; }
        public string Proxy_pwd { get; set; }
        public string Office_code { get; set; }
        public string Office_code1 { get; set; }
        public string Office_code2 { get; set; }
        public string Office_code3 { get; set; }
        public string Office_code4 { get; set; }
        public string Office_code5 { get; set; }
        public string Office_code6 { get; set; }
        public string Office_code7 { get; set; }
        public string Office_code8 { get; set; }
        public string Office_code9 { get; set; }
        public string Office_code10 { get; set; }
        public string Agency_num { get; set; }
        public string Agency_num1 { get; set; }
        public string Agency_num2 { get; set; }
        public string Agency_num3 { get; set; }
        public string Agency_num4 { get; set; }
        public string Agency_num5 { get; set; }
        public string Agency_num6 { get; set; }
        public string Agency_num7 { get; set; }
        public string Agency_num8 { get; set; }
        public string Agency_num9 { get; set; }
        public string Agency_num10 { get; set; }
        public Nullable<int> Report_request_date { get; set; }
        public string Default_agency_num { get; set; }
        public string System_id { get; set; }
        public string Encryption_key_path { get; set; }
        public Nullable<System.DateTime> Last_report_date { get; set; }
        public Nullable<System.DateTime> Last_report_date1 { get; set; }
        public Nullable<System.DateTime> Last_report_date2 { get; set; }
        public Nullable<System.DateTime> Last_report_date3 { get; set; }
        public Nullable<System.DateTime> Last_report_date4 { get; set; }
        public Nullable<System.DateTime> Last_report_date5 { get; set; }
        public Nullable<System.DateTime> Last_report_date6 { get; set; }
        public Nullable<System.DateTime> Last_report_date7 { get; set; }
        public Nullable<System.DateTime> Last_report_date8 { get; set; }
        public Nullable<System.DateTime> Last_report_date9 { get; set; }
        public Nullable<System.DateTime> Last_report_date10 { get; set; }
        public string Rnl_delay { get; set; }
        public Nullable<int> Rnl_delay_days { get; set; }
        public string Report_request_weekday { get; set; }
        public string Report_request_option { get; set; }
        public Nullable<int> Report_request_monthd2 { get; set; }
        public Nullable<System.DateTime> Basedate { get; set; }
        public Nullable<int> Basedate_year { get; set; }
        public Nullable<int> Basedate_day { get; set; }
        public string Agency_logon { get; set; }
        public string Agency_logon1 { get; set; }
        public string Agency_logon2 { get; set; }
        public string Agency_logon3 { get; set; }
        public string Agency_logon4 { get; set; }
        public string Agency_logon5 { get; set; }
        public string Agency_logon6 { get; set; }
        public string Agency_logon7 { get; set; }
        public string Agency_logon8 { get; set; }
        public string Agency_logon9 { get; set; }
        public string Agency_logon10 { get; set; }
        public string Agency_password { get; set; }
        public string Agency_password1 { get; set; }
        public string Agency_password2 { get; set; }
        public string Agency_password3 { get; set; }
        public string Agency_password4 { get; set; }
        public string Agency_password5 { get; set; }
        public string Agency_password6 { get; set; }
        public string Agency_password7 { get; set; }
        public string Agency_password8 { get; set; }
        public string Agency_password9 { get; set; }
        public string Agency_password10 { get; set; }
        public string Agency_selection { get; set; }
        public Nullable<int> Agency_count { get; set; }
        public Nullable<int> Finance_provider_manual_B037_VTId { get; set; }
        public Nullable<int> Agency_brand_QCBR_VTId { get; set; }
        public Nullable<int> Agency_brand1_QCBR_VTId { get; set; }
        public Nullable<int> Agency_brand2_QCBR_VTId { get; set; }
        public Nullable<int> Agency_brand3_QCBR_VTId { get; set; }
        public Nullable<int> Agency_brand4_QCBR_VTId { get; set; }
        public Nullable<int> Agency_brand5_QCBR_VTId { get; set; }
        public Nullable<int> Agency_brand6_QCBR_VTId { get; set; }
        public Nullable<int> Agency_brand7_QCBR_VTId { get; set; }
        public Nullable<int> Agency_brand8_QCBR_VTId { get; set; }
        public Nullable<int> Agency_brand9_QCBR_VTId { get; set; }
        public Nullable<int> Agency_brand10_QCBR_VTId { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
