//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_HB
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Buildingpol { get; set; }
        public Nullable<int> Buildingcover { get; set; }
        public Nullable<int> Buildingexcess { get; set; }
        public string Storm { get; set; }
        public string Landslip { get; set; }
        public string Construction { get; set; }
        public string Rooftype { get; set; }
        public Nullable<int> Yearbuilt { get; set; }
        public string Indexlink { get; set; }
        public Nullable<System.DateTime> Lastindexed { get; set; }
        public Nullable<System.DateTime> Buildclaimdate1 { get; set; }
        public Nullable<int> Buildclaimval1 { get; set; }
        public string Buildclaimtype1 { get; set; }
        public Nullable<System.DateTime> Buildclaimdate2 { get; set; }
        public Nullable<int> Buildclaimval2 { get; set; }
        public string Buildclaimtype2 { get; set; }
        public Nullable<System.DateTime> Buildclaimdate3 { get; set; }
        public Nullable<int> Buildclaimval3 { get; set; }
        public string Buildclaimtype3 { get; set; }
        public Nullable<System.DateTime> Buildclaimdate4 { get; set; }
        public Nullable<int> Buildclaimval4 { get; set; }
        public string Buildclaimtype4 { get; set; }
        public Nullable<System.DateTime> Buildclaimdate5 { get; set; }
        public Nullable<int> Buildclaimval5 { get; set; }
        public string Buildclaimtype5 { get; set; }
        public string Contentspol { get; set; }
        public string Allrisksflag { get; set; }
        public Nullable<int> Contsgoods { get; set; }
        public Nullable<int> Contsgoodslimit { get; set; }
        public Nullable<int> Contsvals { get; set; }
        public Nullable<int> Contsvalslimit { get; set; }
        public Nullable<int> Contentsexcess { get; set; }
        public Nullable<System.DateTime> Contsclaimdate1 { get; set; }
        public Nullable<int> Contsclaimval1 { get; set; }
        public string Contsclaimtype1 { get; set; }
        public Nullable<System.DateTime> Contsclaimdate2 { get; set; }
        public Nullable<int> Contsclaimval2 { get; set; }
        public string Contsclaimtype2 { get; set; }
        public Nullable<System.DateTime> Contsclaimdate3 { get; set; }
        public Nullable<int> Contsclaimval3 { get; set; }
        public string Contsclaimtype3 { get; set; }
        public Nullable<System.DateTime> Contsclaimdate4 { get; set; }
        public Nullable<int> Contsclaimval4 { get; set; }
        public string Contsclaimtype4 { get; set; }
        public Nullable<System.DateTime> Contsclaimdate5 { get; set; }
        public Nullable<int> Contsclaimval5 { get; set; }
        public string Contsclaimtype5 { get; set; }
        public string Cindexlink { get; set; }
        public Nullable<System.DateTime> Clastindex { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
