//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_CM_History
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public string Cover1 { get; set; }
        public string Clmref1 { get; set; }
        public Nullable<int> Loss1 { get; set; }
        public Nullable<decimal> Amm1 { get; set; }
        public string Rem1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public string Cover2 { get; set; }
        public string Clmref2 { get; set; }
        public Nullable<int> Loss2 { get; set; }
        public Nullable<decimal> Amm2 { get; set; }
        public string Rem2 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public string Cover3 { get; set; }
        public string Clmref3 { get; set; }
        public Nullable<int> Loss3 { get; set; }
        public Nullable<decimal> Amm3 { get; set; }
        public string Rem3 { get; set; }
        public Nullable<System.DateTime> Date4 { get; set; }
        public string Cover4 { get; set; }
        public string Clmref4 { get; set; }
        public Nullable<int> Loss4 { get; set; }
        public Nullable<decimal> Amm4 { get; set; }
        public string Rem4 { get; set; }
        public Nullable<System.DateTime> Date5 { get; set; }
        public string Cover5 { get; set; }
        public string Clmref5 { get; set; }
        public Nullable<int> Loss5 { get; set; }
        public Nullable<decimal> Amm5 { get; set; }
        public string Rem5 { get; set; }
        public Nullable<System.DateTime> Date6 { get; set; }
        public string Cover6 { get; set; }
        public string Clmref6 { get; set; }
        public Nullable<int> Loss6 { get; set; }
        public Nullable<decimal> Amm6 { get; set; }
        public string Rem6 { get; set; }
        public Nullable<System.DateTime> Date7 { get; set; }
        public string Cover7 { get; set; }
        public string Clmref7 { get; set; }
        public Nullable<int> Loss7 { get; set; }
        public Nullable<decimal> Amm7 { get; set; }
        public string Rem7 { get; set; }
        public Nullable<System.DateTime> Date8 { get; set; }
        public string Cover8 { get; set; }
        public string Clmref8 { get; set; }
        public Nullable<int> Loss8 { get; set; }
        public Nullable<decimal> Amm8 { get; set; }
        public string Rem8 { get; set; }
        public Nullable<System.DateTime> Date9 { get; set; }
        public string Cover9 { get; set; }
        public string Clmref9 { get; set; }
        public Nullable<int> Loss9 { get; set; }
        public Nullable<decimal> Amm9 { get; set; }
        public string Rem9 { get; set; }
        public Nullable<System.DateTime> Date10 { get; set; }
        public string Cover10 { get; set; }
        public string Clmref10 { get; set; }
        public Nullable<int> Loss10 { get; set; }
        public Nullable<decimal> Amm10 { get; set; }
        public string Rem10 { get; set; }
        public Nullable<System.DateTime> Date11 { get; set; }
        public string Cover11 { get; set; }
        public string Clmref11 { get; set; }
        public Nullable<int> Loss11 { get; set; }
        public Nullable<decimal> Amm11 { get; set; }
        public string Rem11 { get; set; }
        public Nullable<System.DateTime> History_ { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
