//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_BFD
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public string Transkey { get; set; }
        public string Pol_ref { get; set; }
        public Nullable<int> Key_suffix { get; set; }
        public Nullable<int> Fp_B006_VTId { get; set; }
        public string Freq_period { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<int> Instalments { get; set; }
        public Nullable<decimal> P_charge { get; set; }
        public Nullable<decimal> P_le { get; set; }
        public Nullable<decimal> P_totprem { get; set; }
        public Nullable<decimal> P_deposit { get; set; }
        public Nullable<decimal> P_balance { get; set; }
        public Nullable<decimal> P_interest { get; set; }
        public Nullable<decimal> P_tot_amt_pay { get; set; }
        public Nullable<decimal> P_instalment { get; set; }
        public Nullable<decimal> P_pay_protect { get; set; }
        public Nullable<decimal> P_payments { get; set; }
        public Nullable<decimal> P_apr { get; set; }
        public string P_overlap { get; set; }
        public Nullable<decimal> R_charge { get; set; }
        public Nullable<decimal> R_le { get; set; }
        public Nullable<decimal> R_totprem { get; set; }
        public Nullable<decimal> R_deposit { get; set; }
        public Nullable<decimal> R_balance { get; set; }
        public Nullable<decimal> R_interest { get; set; }
        public Nullable<decimal> R_tot_amt_pay { get; set; }
        public Nullable<decimal> R_instalment { get; set; }
        public Nullable<decimal> R_pay_protect { get; set; }
        public Nullable<decimal> R_payments { get; set; }
        public Nullable<decimal> R_apr { get; set; }
        public string R_overlap { get; set; }
        public Nullable<decimal> Premium { get; set; }
        public Nullable<decimal> Requote { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Incept_date { get; set; }
        public string Options { get; set; }
        public string Cheque_no { get; set; }
        public string Scheme_id { get; set; }
        public string Pay_protect { get; set; }
        public string Rec_event { get; set; }
        public Nullable<int> Rec_count { get; set; }
        public string Sent_event { get; set; }
        public Nullable<int> Sent_count { get; set; }
        public Nullable<int> Current_fp_B006_VTId { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
        public string Canc_by { get; set; }
        public string Curr_scheme { get; set; }
        public string Override_int { get; set; }
        public Nullable<decimal> Curr_interest { get; set; }
        public string Curr_fp_scheme { get; set; }
        public Nullable<int> P_fp_B006_VTId { get; set; }
        public string P_freq_period { get; set; }
        public Nullable<decimal> P_rate { get; set; }
        public Nullable<int> P_no_instals { get; set; }
        public string P_pay_protind { get; set; }
        public string P_scheme_id { get; set; }
        public Nullable<int> R_fp_B006_VTId { get; set; }
        public string R_freq_period { get; set; }
        public string R_pay_protind { get; set; }
        public string R_scheme_id { get; set; }
        public Nullable<decimal> R_rate { get; set; }
        public Nullable<int> R_no_instals { get; set; }
        public string P_fp_code { get; set; }
        public string R_fp_code { get; set; }
        public Nullable<System.DateTime> Start_date { get; set; }
        public string Curr_transkey { get; set; }
        public string Crd_refcode { get; set; }
        public Nullable<decimal> Dep_less_rfnd { get; set; }
        public Nullable<int> P_chargecode { get; set; }
        public Nullable<decimal> P_annfee { get; set; }
        public Nullable<decimal> P_monthfee { get; set; }
        public Nullable<decimal> R_annfee { get; set; }
        public Nullable<decimal> R_monthfee { get; set; }
        public string Rt_web_scheme { get; set; }
        public string Rt_net_scheme { get; set; }
        public Nullable<decimal> Rt_cred_chg_per { get; set; }
        public string Rt_already_selected { get; set; }
        public string Rt_call_success { get; set; }
        public string Rt_cad_needed { get; set; }
        public string Rt_cad_supplied { get; set; }
        public string P_fp_scheme { get; set; }
        public string R_fp_scheme { get; set; }
        public Nullable<decimal> Rt_msc { get; set; }
        public Nullable<decimal> Rt_scheme_msc { get; set; }
        public string Rt_override_rate { get; set; }
        public string Agency_number { get; set; }
        public string Previous_ref { get; set; }
        public Nullable<int> Business_code_B028_VTId { get; set; }
        public Nullable<int> Trader_code_B029_VTId { get; set; }
        public Nullable<System.DateTime> Stamp_date { get; set; }
        public Nullable<decimal> Add_charge { get; set; }
        public string Add_charge_set { get; set; }
        public string Current_rt_web_scheme { get; set; }
        public string Rt_gross { get; set; }
        public string Rt_interest_free { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public string Curr_fp_scheme_id2 { get; set; }
    }
}
