//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_DP_TW1
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> Truck_code { get; set; }
        public Nullable<int> Category_QRTA_VTId { get; set; }
        public Nullable<int> Make_vt_QRTK_VTId { get; set; }
        public string Model { get; set; }
        public string C_Type { get; set; }
        public Nullable<int> Engine_size { get; set; }
        public Nullable<int> Gvw { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string Reg_mark { get; set; }
        public Nullable<System.DateTime> Date_made { get; set; }
        public string Cover { get; set; }
        public Nullable<int> Vol_xs { get; set; }
        public Nullable<int> C_Value { get; set; }
        public Nullable<int> Origin_QR43_VTId { get; set; }
        public Nullable<int> Owner_QR08_VTId { get; set; }
        public Nullable<int> Keeper_QR08_VTId { get; set; }
        public Nullable<int> Trailers_QR19_VTId { get; set; }
        public Nullable<int> Containers_QR19_VTId { get; set; }
        public Nullable<int> Modified_QR19_VTId { get; set; }
        public Nullable<int> Lhd_QR19_VTId { get; set; }
        public Nullable<int> Winch_hoist_QR19_VTId { get; set; }
        public Nullable<int> Compressor_QR19_VTId { get; set; }
        public Nullable<System.DateTime> Purchase_date { get; set; }
        public Nullable<int> Purchase_price { get; set; }
        public Nullable<int> Doors { get; set; }
        public Nullable<int> Seats { get; set; }
        public Nullable<int> Transmission_QR42_VTId { get; set; }
        public Nullable<int> Fuel_type_QR32_VTId { get; set; }
        public Nullable<int> Mileage { get; set; }
        public Nullable<int> Parking_QR33_VTId { get; set; }
        public string Garagestructure { get; set; }
        public string Parkingpostcode { get; set; }
        public Nullable<int> Audio { get; set; }
        public Nullable<int> Telephone { get; set; }
        public Nullable<int> Abs_QR19_VTId { get; set; }
        public Nullable<int> Passenger_belts_QR19_VTId { get; set; }
        public Nullable<int> C_Use_QRTB_VTId { get; set; }
        public Nullable<int> Radius { get; set; }
        public Nullable<int> Immob_type_QRTC_VTId { get; set; }
        public Nullable<int> Immob_fitted_by_QR37_VTId { get; set; }
        public Nullable<int> Alarm_type_QRTD_VTId { get; set; }
        public Nullable<int> Alarm_fitted_by_QR37_VTId { get; set; }
        public Nullable<int> Track_type_QR03_VTId { get; set; }
        public Nullable<int> Track_fitted_by_QR37_VTId { get; set; }
        public Nullable<int> Rev_alarm_type_QRTE_VTId { get; set; }
        public Nullable<int> Rev_fitted_by_QR37_VTId { get; set; }
        public Nullable<int> Modification1_QRTF_VTId { get; set; }
        public Nullable<int> Modification2_QRTF_VTId { get; set; }
        public Nullable<int> Modification3_QRTF_VTId { get; set; }
        public Nullable<int> Modification4_QRTF_VTId { get; set; }
        public Nullable<int> Modification5_QRTF_VTId { get; set; }
        public string Unlisted_modification { get; set; }
        public Nullable<int> Load_type1_QRTG_VTId { get; set; }
        public Nullable<int> Load_type2_QRTG_VTId { get; set; }
        public Nullable<int> Load_type3_QRTG_VTId { get; set; }
        public Nullable<int> Load_type4_QRTG_VTId { get; set; }
        public Nullable<int> Load_type5_QRTG_VTId { get; set; }
        public Nullable<System.DateTime> Ncb_base_date { get; set; }
        public Nullable<int> Ncb_type_QR44_VTId { get; set; }
        public Nullable<int> Protected_bonus_QR19_VTId { get; set; }
        public Nullable<int> Ncb_years { get; set; }
        public Nullable<int> Ncb_country_QR43_VTId { get; set; }
        public Nullable<int> Windscreencover_QR19_VTId { get; set; }
        public Nullable<int> No_models_QR19_VTId { get; set; }
        public Nullable<int> Usewordingflg { get; set; }
        public Nullable<int> Radius_given { get; set; }
        public string Garageaddr1 { get; set; }
        public string Garageaddr2 { get; set; }
        public string Garageaddr3 { get; set; }
        public string Garageaddr4 { get; set; }
        public string Garagepcode { get; set; }
        public Nullable<int> Volxstruck { get; set; }
        public Nullable<int> Comxstruck { get; set; }
        public Nullable<int> Polxstruck { get; set; }
        public string Vxstypetruck { get; set; }
        public string Cxstypetruck { get; set; }
        public Nullable<int> Vehicleoverride_QR19_VTId { get; set; }
        public string Make_vt_vo { get; set; }
        public Nullable<int> Truckprfn { get; set; }
        public string Authorisation_vo { get; set; }
        public Nullable<int> Year_made_vo { get; set; }
        public Nullable<decimal> Percentncb { get; set; }
        public Nullable<int> Veh_grp { get; set; }
        public string Veh_termstr { get; set; }
        public string Parking_area_grpstr { get; set; }
        public Nullable<int> Quotesncbyears { get; set; }
        public Nullable<int> Temptruck_QR19_VTId { get; set; }
        public Nullable<System.DateTime> Temptruckexpirydate { get; set; }
        public string Temptruckexpirytime { get; set; }
        public Nullable<int> Granted_protected_bonus_QR19_VTId { get; set; }
        public Nullable<int> Stepback_QR19_VTId { get; set; }
        public string Endofrecord { get; set; }
        public Nullable<decimal> Ncbperc { get; set; }
        public Nullable<int> Ncbtype_QR55_VTId { get; set; }
        public Nullable<int> Ncbdisc_QR56_VTId { get; set; }
        public Nullable<int> Appsec { get; set; }
        public Nullable<int> Aqquoteorigin_QREA_VTId { get; set; }
        public string Aqaffiliate { get; set; }
        public Nullable<int> Wstruck_QR19_VTId { get; set; }
        public Nullable<int> Businesssourcecode_QREA_VTId { get; set; }
        public Nullable<int> Businesssrccode_QREA_VTId { get; set; }
        public string Parkingeircode { get; set; }
        public Nullable<int> Ratesyear { get; set; }
        public Nullable<int> Ratesmonth { get; set; }
        public Nullable<int> Ratesversion { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
