//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_briptrate
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string Poltype { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string C_Key { get; set; }
        public string Amend { get; set; }
        public Nullable<System.DateTime> Date_adj { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
