//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class icp_BD_EN
    {
        public int Branch_ { get; set; }
        public string Key_ { get; set; }
        public string ClientRef_ { get; set; }
        public string PolicyRef_ { get; set; }
        public Nullable<int> Sequence_ { get; set; }
        public Nullable<int> F_1 { get; set; }
        public string Item1 { get; set; }
        public string Des1 { get; set; }
        public string CovCo1 { get; set; }
        public Nullable<int> SI1 { get; set; }
        public Nullable<decimal> Prem1 { get; set; }
        public string PLEx1 { get; set; }
        public string CovCo2 { get; set; }
        public string CovCo3 { get; set; }
        public string Item2 { get; set; }
        public string Des2 { get; set; }
        public string CovCo4 { get; set; }
        public Nullable<int> SI2 { get; set; }
        public Nullable<decimal> Prem2 { get; set; }
        public string PLEx2 { get; set; }
        public string CovCo5 { get; set; }
        public string CovCo6 { get; set; }
        public string Item3 { get; set; }
        public string Des3 { get; set; }
        public string CovCo7 { get; set; }
        public Nullable<int> SI3 { get; set; }
        public Nullable<decimal> Prem3 { get; set; }
        public string PLEx3 { get; set; }
        public string CovCo8 { get; set; }
        public string CovCo9 { get; set; }
        public string Item4 { get; set; }
        public string Des4 { get; set; }
        public string CovCo10 { get; set; }
        public Nullable<int> SI4 { get; set; }
        public Nullable<decimal> Prem4 { get; set; }
        public string PLEx4 { get; set; }
        public string CovCo11 { get; set; }
        public string CovCo12 { get; set; }
        public string Item5 { get; set; }
        public string Des5 { get; set; }
        public string CovCo13 { get; set; }
        public Nullable<int> SI5 { get; set; }
        public Nullable<decimal> Prem5 { get; set; }
        public string PLEx5 { get; set; }
        public string CovCo14 { get; set; }
        public string CovCo15 { get; set; }
        public string Item6 { get; set; }
        public string Des6 { get; set; }
        public string CovCo16 { get; set; }
        public Nullable<int> SI6 { get; set; }
        public Nullable<decimal> Prem6 { get; set; }
        public string PLEx6 { get; set; }
        public string CovCo17 { get; set; }
        public string CovCo18 { get; set; }
        public string Item7 { get; set; }
        public string Des7 { get; set; }
        public string CovCo19 { get; set; }
        public Nullable<int> SI7 { get; set; }
        public Nullable<decimal> Prem7 { get; set; }
        public string PLEx7 { get; set; }
        public string CovCo20 { get; set; }
        public string CovCo21 { get; set; }
        public string Item8 { get; set; }
        public string Des8 { get; set; }
        public string CovCo22 { get; set; }
        public Nullable<int> SI8 { get; set; }
        public Nullable<decimal> Prem8 { get; set; }
        public string PLEx8 { get; set; }
        public string CovCo23 { get; set; }
        public string CovCo24 { get; set; }
        public Nullable<int> RefreshGenerationId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
    }
}
