//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test__Connection.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Phone_SystemEntities30 : DbContext
    {
        public Phone_SystemEntities30()
            : base("name=Phone_SystemEntities30")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CallOutcome> CallOutcomes { get; set; }
        public virtual DbSet<CallOutcomeList> CallOutcomeLists { get; set; }
    
        public virtual ObjectResult<pr_RenewalListtest_Result> pr_RenewalListtest(Nullable<System.DateTime> lowerDate, Nullable<System.DateTime> upperDate)
        {
            var lowerDateParameter = lowerDate.HasValue ?
                new ObjectParameter("LowerDate", lowerDate) :
                new ObjectParameter("LowerDate", typeof(System.DateTime));
    
            var upperDateParameter = upperDate.HasValue ?
                new ObjectParameter("UpperDate", upperDate) :
                new ObjectParameter("UpperDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_RenewalListtest_Result>("pr_RenewalListtest", lowerDateParameter, upperDateParameter);
        }
    }
}
